###用户登录
POST {{host}}/api/sys/user/login
Content-Type: application/json

{
  "account": "admin",
  "password": "123456"
}
> {%
    client.global.set("token", response.body.data.token);
%}

### 添加推荐品牌
POST {{host}}/api/sms/homeBrand/addHomeBrand
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "brandIds": [
    8
  ]
}

### 删除推荐品牌
GET {{host}}/api/sms/homeBrand/deleteHomeBrand?brandIds=8
Authorization: Bearer {{token}}


### 修改推荐品牌排序
POST {{host}}/api/sms/homeBrand/updateHomeBrandSort
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "brandId": 13,
  "sort": 200
}


### 查询推荐品牌列表
GET {{host}}/api/sms/homeBrand/queryHomeBrandList
Authorization: Bearer {{token}}
