###用户登录
POST {{host}}/api/sys/user/login
Content-Type: application/json

{
  "account": "admin",
  "password": "123456"
}
> {%
    client.global.set("token", response.body.data.token);
%}

### 添加人气商品推荐
POST {{host}}/api/sms/homeRecommendProduct/addHomeRecommendProduct
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "productIds": [
    36
  ]
}

### 删除人气商品推荐
GET {{host}}/api/sms/homeRecommendProduct/deleteHomeRecommendProduct?productIds=36
Authorization: Bearer {{token}}


### 修改人气商品推荐排序
POST {{host}}/api/sms/homeRecommendProduct/updateRecommendProductSort
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "productId": 36,
  "sort": 21
}

### 查询人气商品推荐列表
GET {{host}}/api/sms/homeRecommendProduct/queryHomeRecommendProductList
Authorization: Bearer {{token}}
