###用户登录
POST {{host}}/api/consumer/auth
Content-Type: application/json

{
  "account": "admin",
  "password": "123456"
}
> {%
    client.global.set("token", response.body.data.token);
%}

### 添加商品索引
POST {{host}}/api/consumer/addProductToEs
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "ids": [
    1,2,3
  ]
}

### 删除商品索引
POST {{host}}/api/consumer/deleteProductFromEs
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "ids": [
    1,2,3
  ]
}

### 测试订单相关操作
POST {{host}}/api/consumer/testOrder
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "id": 1
}

