// Code generated by goctl. DO NOT EDIT.
// Source: ums.proto

package server

import (
	"context"

	"zero-admin/rpc/ums/internal/logic/memberproductcollectionservice"
	"zero-admin/rpc/ums/internal/svc"
	"zero-admin/rpc/ums/umsclient"
)

type MemberProductCollectionServiceServer struct {
	svcCtx *svc.ServiceContext
	umsclient.UnimplementedMemberProductCollectionServiceServer
}

func NewMemberProductCollectionServiceServer(svcCtx *svc.ServiceContext) *MemberProductCollectionServiceServer {
	return &MemberProductCollectionServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *MemberProductCollectionServiceServer) MemberProductCollectionAdd(ctx context.Context, in *umsclient.MemberProductCollectionAddReq) (*umsclient.MemberProductCollectionAddResp, error) {
	l := memberproductcollectionservicelogic.NewMemberProductCollectionAddLogic(ctx, s.svcCtx)
	return l.MemberProductCollectionAdd(in)
}

func (s *MemberProductCollectionServiceServer) MemberProductCollectionDelete(ctx context.Context, in *umsclient.MemberProductCollectionDeleteReq) (*umsclient.MemberProductCollectionDeleteResp, error) {
	l := memberproductcollectionservicelogic.NewMemberProductCollectionDeleteLogic(ctx, s.svcCtx)
	return l.MemberProductCollectionDelete(in)
}

func (s *MemberProductCollectionServiceServer) MemberProductCollectionUpdate(ctx context.Context, in *umsclient.MemberProductCollectionUpdateReq) (*umsclient.MemberProductCollectionUpdateResp, error) {
	l := memberproductcollectionservicelogic.NewMemberProductCollectionUpdateLogic(ctx, s.svcCtx)
	return l.MemberProductCollectionUpdate(in)
}

func (s *MemberProductCollectionServiceServer) MemberProductCollectionList(ctx context.Context, in *umsclient.MemberProductCollectionListReq) (*umsclient.MemberProductCollectionListResp, error) {
	l := memberproductcollectionservicelogic.NewMemberProductCollectionListLogic(ctx, s.svcCtx)
	return l.MemberProductCollectionList(in)
}
