// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: pms.proto

package productfullreductionservice

import (
	"context"

	"github.com/feihua/zero-admin/rpc/pms/pmsclient"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddProductFullReductionReq        = pmsclient.AddProductFullReductionReq
	AddProductFullReductionResp       = pmsclient.AddProductFullReductionResp
	DeleteProductFullReductionReq     = pmsclient.DeleteProductFullReductionReq
	DeleteProductFullReductionResp    = pmsclient.DeleteProductFullReductionResp
	ProductFullReductionListData      = pmsclient.ProductFullReductionListData
	QueryProductFullReductionListReq  = pmsclient.QueryProductFullReductionListReq
	QueryProductFullReductionListResp = pmsclient.QueryProductFullReductionListResp

	ProductFullReductionService interface {
		// 添加产品满减表(只针对同商品)
		AddProductFullReduction(ctx context.Context, in *AddProductFullReductionReq, opts ...grpc.CallOption) (*AddProductFullReductionResp, error)
		// 删除产品满减表(只针对同商品)
		DeleteProductFullReduction(ctx context.Context, in *DeleteProductFullReductionReq, opts ...grpc.CallOption) (*DeleteProductFullReductionResp, error)
		// 查询产品满减表(只针对同商品)列表
		QueryProductFullReductionList(ctx context.Context, in *QueryProductFullReductionListReq, opts ...grpc.CallOption) (*QueryProductFullReductionListResp, error)
	}

	defaultProductFullReductionService struct {
		cli zrpc.Client
	}
)

func NewProductFullReductionService(cli zrpc.Client) ProductFullReductionService {
	return &defaultProductFullReductionService{
		cli: cli,
	}
}

// 添加产品满减表(只针对同商品)
func (m *defaultProductFullReductionService) AddProductFullReduction(ctx context.Context, in *AddProductFullReductionReq, opts ...grpc.CallOption) (*AddProductFullReductionResp, error) {
	client := pmsclient.NewProductFullReductionServiceClient(m.cli.Conn())
	return client.AddProductFullReduction(ctx, in, opts...)
}

// 删除产品满减表(只针对同商品)
func (m *defaultProductFullReductionService) DeleteProductFullReduction(ctx context.Context, in *DeleteProductFullReductionReq, opts ...grpc.CallOption) (*DeleteProductFullReductionResp, error) {
	client := pmsclient.NewProductFullReductionServiceClient(m.cli.Conn())
	return client.DeleteProductFullReduction(ctx, in, opts...)
}

// 查询产品满减表(只针对同商品)列表
func (m *defaultProductFullReductionService) QueryProductFullReductionList(ctx context.Context, in *QueryProductFullReductionListReq, opts ...grpc.CallOption) (*QueryProductFullReductionListResp, error) {
	client := pmsclient.NewProductFullReductionServiceClient(m.cli.Conn())
	return client.QueryProductFullReductionList(ctx, in, opts...)
}
