// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2
// Source: ums.proto

package memberreadhistoryservice

import (
	"context"

	"github.com/feihua/zero-admin/rpc/ums/umsclient"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddGrowthChangeHistoryReq                  = umsclient.AddGrowthChangeHistoryReq
	AddGrowthChangeHistoryResp                 = umsclient.AddGrowthChangeHistoryResp
	AddIntegrationChangeHistoryReq             = umsclient.AddIntegrationChangeHistoryReq
	AddIntegrationChangeHistoryResp            = umsclient.AddIntegrationChangeHistoryResp
	AddIntegrationConsumeSettingReq            = umsclient.AddIntegrationConsumeSettingReq
	AddIntegrationConsumeSettingResp           = umsclient.AddIntegrationConsumeSettingResp
	AddMemberAddressReq                        = umsclient.AddMemberAddressReq
	AddMemberAddressResp                       = umsclient.AddMemberAddressResp
	AddMemberBrandAttentionReq                 = umsclient.AddMemberBrandAttentionReq
	AddMemberBrandAttentionResp                = umsclient.AddMemberBrandAttentionResp
	AddMemberLevelReq                          = umsclient.AddMemberLevelReq
	AddMemberLevelResp                         = umsclient.AddMemberLevelResp
	AddMemberMemberTagRelationReq              = umsclient.AddMemberMemberTagRelationReq
	AddMemberMemberTagRelationResp             = umsclient.AddMemberMemberTagRelationResp
	AddMemberProductCategoryRelationReq        = umsclient.AddMemberProductCategoryRelationReq
	AddMemberProductCategoryRelationResp       = umsclient.AddMemberProductCategoryRelationResp
	AddMemberProductCollectionReq              = umsclient.AddMemberProductCollectionReq
	AddMemberProductCollectionResp             = umsclient.AddMemberProductCollectionResp
	AddMemberReadHistoryReq                    = umsclient.AddMemberReadHistoryReq
	AddMemberReadHistoryResp                   = umsclient.AddMemberReadHistoryResp
	AddMemberRuleSettingReq                    = umsclient.AddMemberRuleSettingReq
	AddMemberRuleSettingResp                   = umsclient.AddMemberRuleSettingResp
	AddMemberStatisticsInfoReq                 = umsclient.AddMemberStatisticsInfoReq
	AddMemberStatisticsInfoResp                = umsclient.AddMemberStatisticsInfoResp
	AddMemberTagReq                            = umsclient.AddMemberTagReq
	AddMemberTagResp                           = umsclient.AddMemberTagResp
	AddMemberTaskReq                           = umsclient.AddMemberTaskReq
	AddMemberTaskResp                          = umsclient.AddMemberTaskResp
	DeleteGrowthChangeHistoryReq               = umsclient.DeleteGrowthChangeHistoryReq
	DeleteGrowthChangeHistoryResp              = umsclient.DeleteGrowthChangeHistoryResp
	DeleteIntegrationChangeHistoryReq          = umsclient.DeleteIntegrationChangeHistoryReq
	DeleteIntegrationChangeHistoryResp         = umsclient.DeleteIntegrationChangeHistoryResp
	DeleteIntegrationConsumeSettingReq         = umsclient.DeleteIntegrationConsumeSettingReq
	DeleteIntegrationConsumeSettingResp        = umsclient.DeleteIntegrationConsumeSettingResp
	DeleteMemberAddressReq                     = umsclient.DeleteMemberAddressReq
	DeleteMemberAddressResp                    = umsclient.DeleteMemberAddressResp
	DeleteMemberBrandAttentionReq              = umsclient.DeleteMemberBrandAttentionReq
	DeleteMemberBrandAttentionResp             = umsclient.DeleteMemberBrandAttentionResp
	DeleteMemberInfoReq                        = umsclient.DeleteMemberInfoReq
	DeleteMemberInfoResp                       = umsclient.DeleteMemberInfoResp
	DeleteMemberLevelReq                       = umsclient.DeleteMemberLevelReq
	DeleteMemberLevelResp                      = umsclient.DeleteMemberLevelResp
	DeleteMemberLoginLogReq                    = umsclient.DeleteMemberLoginLogReq
	DeleteMemberLoginLogResp                   = umsclient.DeleteMemberLoginLogResp
	DeleteMemberMemberTagRelationReq           = umsclient.DeleteMemberMemberTagRelationReq
	DeleteMemberMemberTagRelationResp          = umsclient.DeleteMemberMemberTagRelationResp
	DeleteMemberProductCollectionReq           = umsclient.DeleteMemberProductCollectionReq
	DeleteMemberProductCollectionResp          = umsclient.DeleteMemberProductCollectionResp
	DeleteMemberReadHistoryReq                 = umsclient.DeleteMemberReadHistoryReq
	DeleteMemberReadHistoryResp                = umsclient.DeleteMemberReadHistoryResp
	DeleteMemberRuleSettingReq                 = umsclient.DeleteMemberRuleSettingReq
	DeleteMemberRuleSettingResp                = umsclient.DeleteMemberRuleSettingResp
	DeleteMemberTagReq                         = umsclient.DeleteMemberTagReq
	DeleteMemberTagResp                        = umsclient.DeleteMemberTagResp
	DeleteMemberTaskReq                        = umsclient.DeleteMemberTaskReq
	DeleteMemberTaskResp                       = umsclient.DeleteMemberTaskResp
	GrowthChangeHistoryListData                = umsclient.GrowthChangeHistoryListData
	IntegrationChangeHistoryListData           = umsclient.IntegrationChangeHistoryListData
	IntegrationConsumeSettingListData          = umsclient.IntegrationConsumeSettingListData
	LoginReq                                   = umsclient.LoginReq
	LoginResp                                  = umsclient.LoginResp
	MemberAddressListData                      = umsclient.MemberAddressListData
	MemberBrandAttentionListData               = umsclient.MemberBrandAttentionListData
	MemberInfoListData                         = umsclient.MemberInfoListData
	MemberLevelListData                        = umsclient.MemberLevelListData
	MemberLoginLogListData                     = umsclient.MemberLoginLogListData
	MemberMemberTagRelationListData            = umsclient.MemberMemberTagRelationListData
	MemberProductCategoryRelationListData      = umsclient.MemberProductCategoryRelationListData
	MemberProductCollectionListData            = umsclient.MemberProductCollectionListData
	MemberReadHistoryListData                  = umsclient.MemberReadHistoryListData
	MemberRuleSettingListData                  = umsclient.MemberRuleSettingListData
	MemberTagListData                          = umsclient.MemberTagListData
	MemberTaskListData                         = umsclient.MemberTaskListData
	QueryGrowthChangeHistoryDetailReq          = umsclient.QueryGrowthChangeHistoryDetailReq
	QueryGrowthChangeHistoryDetailResp         = umsclient.QueryGrowthChangeHistoryDetailResp
	QueryGrowthChangeHistoryListReq            = umsclient.QueryGrowthChangeHistoryListReq
	QueryGrowthChangeHistoryListResp           = umsclient.QueryGrowthChangeHistoryListResp
	QueryIntegrationChangeHistoryDetailReq     = umsclient.QueryIntegrationChangeHistoryDetailReq
	QueryIntegrationChangeHistoryDetailResp    = umsclient.QueryIntegrationChangeHistoryDetailResp
	QueryIntegrationChangeHistoryListReq       = umsclient.QueryIntegrationChangeHistoryListReq
	QueryIntegrationChangeHistoryListResp      = umsclient.QueryIntegrationChangeHistoryListResp
	QueryIntegrationConsumeSettingDetailReq    = umsclient.QueryIntegrationConsumeSettingDetailReq
	QueryIntegrationConsumeSettingDetailResp   = umsclient.QueryIntegrationConsumeSettingDetailResp
	QueryIntegrationConsumeSettingListReq      = umsclient.QueryIntegrationConsumeSettingListReq
	QueryIntegrationConsumeSettingListResp     = umsclient.QueryIntegrationConsumeSettingListResp
	QueryMemberAddressDetailReq                = umsclient.QueryMemberAddressDetailReq
	QueryMemberAddressDetailResp               = umsclient.QueryMemberAddressDetailResp
	QueryMemberAddressListReq                  = umsclient.QueryMemberAddressListReq
	QueryMemberAddressListResp                 = umsclient.QueryMemberAddressListResp
	QueryMemberBrandAttentionDetailReq         = umsclient.QueryMemberBrandAttentionDetailReq
	QueryMemberBrandAttentionDetailResp        = umsclient.QueryMemberBrandAttentionDetailResp
	QueryMemberBrandAttentionListReq           = umsclient.QueryMemberBrandAttentionListReq
	QueryMemberBrandAttentionListResp          = umsclient.QueryMemberBrandAttentionListResp
	QueryMemberInfoDetailReq                   = umsclient.QueryMemberInfoDetailReq
	QueryMemberInfoDetailResp                  = umsclient.QueryMemberInfoDetailResp
	QueryMemberInfoListReq                     = umsclient.QueryMemberInfoListReq
	QueryMemberInfoListResp                    = umsclient.QueryMemberInfoListResp
	QueryMemberLevelDetailReq                  = umsclient.QueryMemberLevelDetailReq
	QueryMemberLevelDetailResp                 = umsclient.QueryMemberLevelDetailResp
	QueryMemberLevelListReq                    = umsclient.QueryMemberLevelListReq
	QueryMemberLevelListResp                   = umsclient.QueryMemberLevelListResp
	QueryMemberLoginLogListReq                 = umsclient.QueryMemberLoginLogListReq
	QueryMemberLoginLogListResp                = umsclient.QueryMemberLoginLogListResp
	QueryMemberMemberTagRelationListReq        = umsclient.QueryMemberMemberTagRelationListReq
	QueryMemberMemberTagRelationListResp       = umsclient.QueryMemberMemberTagRelationListResp
	QueryMemberProductCategoryRelationListReq  = umsclient.QueryMemberProductCategoryRelationListReq
	QueryMemberProductCategoryRelationListResp = umsclient.QueryMemberProductCategoryRelationListResp
	QueryMemberProductCollectionDetailReq      = umsclient.QueryMemberProductCollectionDetailReq
	QueryMemberProductCollectionDetailResp     = umsclient.QueryMemberProductCollectionDetailResp
	QueryMemberProductCollectionListReq        = umsclient.QueryMemberProductCollectionListReq
	QueryMemberProductCollectionListResp       = umsclient.QueryMemberProductCollectionListResp
	QueryMemberReadHistoryDetailReq            = umsclient.QueryMemberReadHistoryDetailReq
	QueryMemberReadHistoryDetailResp           = umsclient.QueryMemberReadHistoryDetailResp
	QueryMemberReadHistoryListReq              = umsclient.QueryMemberReadHistoryListReq
	QueryMemberReadHistoryListResp             = umsclient.QueryMemberReadHistoryListResp
	QueryMemberRuleSettingDetailReq            = umsclient.QueryMemberRuleSettingDetailReq
	QueryMemberRuleSettingDetailResp           = umsclient.QueryMemberRuleSettingDetailResp
	QueryMemberRuleSettingListReq              = umsclient.QueryMemberRuleSettingListReq
	QueryMemberRuleSettingListResp             = umsclient.QueryMemberRuleSettingListResp
	QueryMemberStatisticsInfoDetailReq         = umsclient.QueryMemberStatisticsInfoDetailReq
	QueryMemberStatisticsInfoDetailResp        = umsclient.QueryMemberStatisticsInfoDetailResp
	QueryMemberStatisticsInfoListData          = umsclient.QueryMemberStatisticsInfoListData
	QueryMemberStatisticsInfoListReq           = umsclient.QueryMemberStatisticsInfoListReq
	QueryMemberStatisticsInfoListResp          = umsclient.QueryMemberStatisticsInfoListResp
	QueryMemberTagDetailReq                    = umsclient.QueryMemberTagDetailReq
	QueryMemberTagDetailResp                   = umsclient.QueryMemberTagDetailResp
	QueryMemberTagListReq                      = umsclient.QueryMemberTagListReq
	QueryMemberTagListResp                     = umsclient.QueryMemberTagListResp
	QueryMemberTaskDetailReq                   = umsclient.QueryMemberTaskDetailReq
	QueryMemberTaskDetailResp                  = umsclient.QueryMemberTaskDetailResp
	QueryMemberTaskListReq                     = umsclient.QueryMemberTaskListReq
	QueryMemberTaskListResp                    = umsclient.QueryMemberTaskListResp
	RegisterReq                                = umsclient.RegisterReq
	RegisterResp                               = umsclient.RegisterResp
	UpdateIntegrationConsumeSettingReq         = umsclient.UpdateIntegrationConsumeSettingReq
	UpdateIntegrationConsumeSettingResp        = umsclient.UpdateIntegrationConsumeSettingResp
	UpdateIntegrationConsumeSettingStatusReq   = umsclient.UpdateIntegrationConsumeSettingStatusReq
	UpdateIntegrationConsumeSettingStatusResp  = umsclient.UpdateIntegrationConsumeSettingStatusResp
	UpdateMemberAddressReq                     = umsclient.UpdateMemberAddressReq
	UpdateMemberAddressResp                    = umsclient.UpdateMemberAddressResp
	UpdateMemberAddressStatusReq               = umsclient.UpdateMemberAddressStatusReq
	UpdateMemberAddressStatusResp              = umsclient.UpdateMemberAddressStatusResp
	UpdateMemberInfoReq                        = umsclient.UpdateMemberInfoReq
	UpdateMemberInfoResp                       = umsclient.UpdateMemberInfoResp
	UpdateMemberInfoStatusReq                  = umsclient.UpdateMemberInfoStatusReq
	UpdateMemberInfoStatusResp                 = umsclient.UpdateMemberInfoStatusResp
	UpdateMemberLevelReq                       = umsclient.UpdateMemberLevelReq
	UpdateMemberLevelResp                      = umsclient.UpdateMemberLevelResp
	UpdateMemberLevelStatusReq                 = umsclient.UpdateMemberLevelStatusReq
	UpdateMemberLevelStatusResp                = umsclient.UpdateMemberLevelStatusResp
	UpdateMemberPointsReq                      = umsclient.UpdateMemberPointsReq
	UpdateMemberPointsResp                     = umsclient.UpdateMemberPointsResp
	UpdateMemberRuleSettingReq                 = umsclient.UpdateMemberRuleSettingReq
	UpdateMemberRuleSettingResp                = umsclient.UpdateMemberRuleSettingResp
	UpdateMemberRuleSettingStatusReq           = umsclient.UpdateMemberRuleSettingStatusReq
	UpdateMemberRuleSettingStatusResp          = umsclient.UpdateMemberRuleSettingStatusResp
	UpdateMemberTagReq                         = umsclient.UpdateMemberTagReq
	UpdateMemberTagResp                        = umsclient.UpdateMemberTagResp
	UpdateMemberTagStatusReq                   = umsclient.UpdateMemberTagStatusReq
	UpdateMemberTagStatusResp                  = umsclient.UpdateMemberTagStatusResp
	UpdateMemberTaskReq                        = umsclient.UpdateMemberTaskReq
	UpdateMemberTaskResp                       = umsclient.UpdateMemberTaskResp
	UpdateMemberTaskStatusReq                  = umsclient.UpdateMemberTaskStatusReq
	UpdateMemberTaskStatusResp                 = umsclient.UpdateMemberTaskStatusResp

	MemberReadHistoryService interface {
		// 添加用户商品浏览历史记录
		AddMemberReadHistory(ctx context.Context, in *AddMemberReadHistoryReq, opts ...grpc.CallOption) (*AddMemberReadHistoryResp, error)
		// 清空浏览记录/删除浏览记录
		DeleteMemberReadHistory(ctx context.Context, in *DeleteMemberReadHistoryReq, opts ...grpc.CallOption) (*DeleteMemberReadHistoryResp, error)
		// 查询用户商品浏览历史记录详情
		QueryMemberReadHistoryDetail(ctx context.Context, in *QueryMemberReadHistoryDetailReq, opts ...grpc.CallOption) (*QueryMemberReadHistoryDetailResp, error)
		// 查询用户商品浏览历史记录列表
		QueryMemberReadHistoryList(ctx context.Context, in *QueryMemberReadHistoryListReq, opts ...grpc.CallOption) (*QueryMemberReadHistoryListResp, error)
	}

	defaultMemberReadHistoryService struct {
		cli zrpc.Client
	}
)

func NewMemberReadHistoryService(cli zrpc.Client) MemberReadHistoryService {
	return &defaultMemberReadHistoryService{
		cli: cli,
	}
}

// 添加用户商品浏览历史记录
func (m *defaultMemberReadHistoryService) AddMemberReadHistory(ctx context.Context, in *AddMemberReadHistoryReq, opts ...grpc.CallOption) (*AddMemberReadHistoryResp, error) {
	client := umsclient.NewMemberReadHistoryServiceClient(m.cli.Conn())
	return client.AddMemberReadHistory(ctx, in, opts...)
}

// 清空浏览记录/删除浏览记录
func (m *defaultMemberReadHistoryService) DeleteMemberReadHistory(ctx context.Context, in *DeleteMemberReadHistoryReq, opts ...grpc.CallOption) (*DeleteMemberReadHistoryResp, error) {
	client := umsclient.NewMemberReadHistoryServiceClient(m.cli.Conn())
	return client.DeleteMemberReadHistory(ctx, in, opts...)
}

// 查询用户商品浏览历史记录详情
func (m *defaultMemberReadHistoryService) QueryMemberReadHistoryDetail(ctx context.Context, in *QueryMemberReadHistoryDetailReq, opts ...grpc.CallOption) (*QueryMemberReadHistoryDetailResp, error) {
	client := umsclient.NewMemberReadHistoryServiceClient(m.cli.Conn())
	return client.QueryMemberReadHistoryDetail(ctx, in, opts...)
}

// 查询用户商品浏览历史记录列表
func (m *defaultMemberReadHistoryService) QueryMemberReadHistoryList(ctx context.Context, in *QueryMemberReadHistoryListReq, opts ...grpc.CallOption) (*QueryMemberReadHistoryListResp, error) {
	client := umsclient.NewMemberReadHistoryServiceClient(m.cli.Conn())
	return client.QueryMemberReadHistoryList(ctx, in, opts...)
}
