// Code generated by goctl. DO NOT EDIT!
// Source: sys.proto

//go:generate mockgen -destination ./sys_mock.go -package sysclient -source $GOFILE

package sysclient

import (
	"context"

	"go-zero-admin/rpc/sys/sys"

	"github.com/tal-tech/go-zero/zrpc"
)

type (
	MenuListTree          = sys.MenuListTree
	LoginLogAddReq        = sys.LoginLogAddReq
	SysLogListData        = sys.SysLogListData
	RoleListResp          = sys.RoleListResp
	RoleUpdateResp        = sys.RoleUpdateResp
	UpdateRoleRoleReq     = sys.UpdateRoleRoleReq
	MenuAddReq            = sys.MenuAddReq
	MenuListReq           = sys.MenuListReq
	DictListReq           = sys.DictListReq
	ConfigListReq         = sys.ConfigListReq
	UpdateConfigRoleReq   = sys.UpdateConfigRoleReq
	QueryMenuByRoleIdResp = sys.QueryMenuByRoleIdResp
	MenuDeleteResp        = sys.MenuDeleteResp
	DeptAddReq            = sys.DeptAddReq
	LoginLogListReq       = sys.LoginLogListReq
	LoginLogListData      = sys.LoginLogListData
	LoginResp             = sys.LoginResp
	DictDeleteReq         = sys.DictDeleteReq
	ConfigListData        = sys.ConfigListData
	ConfigListResp        = sys.ConfigListResp
	ConfigDeleteReq       = sys.ConfigDeleteReq
	UpdateConfigRoleResp  = sys.UpdateConfigRoleResp
	InfoReq               = sys.InfoReq
	UserAddResp           = sys.UserAddResp
	UserStatusReq         = sys.UserStatusReq
	LoginLogDeleteReq     = sys.LoginLogDeleteReq
	SysLogAddReq          = sys.SysLogAddReq
	SysLogListReq         = sys.SysLogListReq
	UserDeleteReq         = sys.UserDeleteReq
	UserStatusResp        = sys.UserStatusResp
	RoleListReq           = sys.RoleListReq
	MenuUpdateResp        = sys.MenuUpdateResp
	MenuDeleteReq         = sys.MenuDeleteReq
	DictUpdateReq         = sys.DictUpdateReq
	MenuListResp          = sys.MenuListResp
	UpdateMenuRoleReq     = sys.UpdateMenuRoleReq
	DictAddResp           = sys.DictAddResp
	DeptDeleteReq         = sys.DeptDeleteReq
	ConfigUpdateReq       = sys.ConfigUpdateReq
	InfoResp              = sys.InfoResp
	RoleAddReq            = sys.RoleAddReq
	RoleDeleteReq         = sys.RoleDeleteReq
	MenuAddResp           = sys.MenuAddResp
	UpdateMenuRoleResp    = sys.UpdateMenuRoleResp
	DeptListReq           = sys.DeptListReq
	UserUpdateReq         = sys.UserUpdateReq
	UserUpdateResp        = sys.UserUpdateResp
	UpdateRoleRoleResp    = sys.UpdateRoleRoleResp
	MenuUpdateReq         = sys.MenuUpdateReq
	LoginLogAddResp       = sys.LoginLogAddResp
	SysLogDeleteResp      = sys.SysLogDeleteResp
	DictAddReq            = sys.DictAddReq
	DeptListResp          = sys.DeptListResp
	DeptUpdateResp        = sys.DeptUpdateResp
	UserListReq           = sys.UserListReq
	RoleDeleteResp        = sys.RoleDeleteResp
	DictUpdateResp        = sys.DictUpdateResp
	DictDeleteResp        = sys.DictDeleteResp
	ConfigAddReq          = sys.ConfigAddReq
	ConfigAddResp         = sys.ConfigAddResp
	UserListData          = sys.UserListData
	UserListResp          = sys.UserListResp
	RoleAddResp           = sys.RoleAddResp
	LoginLogListResp      = sys.LoginLogListResp
	SysLogListResp        = sys.SysLogListResp
	SysLogDeleteReq       = sys.SysLogDeleteReq
	LoginLogDeleteResp    = sys.LoginLogDeleteResp
	LoginReq              = sys.LoginReq
	ReSetPasswordReq      = sys.ReSetPasswordReq
	RoleListData          = sys.RoleListData
	QueryMenuByRoleIdReq  = sys.QueryMenuByRoleIdReq
	DictListResp          = sys.DictListResp
	DeptUpdateReq         = sys.DeptUpdateReq
	ReSetPasswordResp     = sys.ReSetPasswordResp
	MenuListData          = sys.MenuListData
	DictListData          = sys.DictListData
	DeptDeleteResp        = sys.DeptDeleteResp
	ConfigUpdateResp      = sys.ConfigUpdateResp
	ConfigDeleteResp      = sys.ConfigDeleteResp
	UserAddReq            = sys.UserAddReq
	UserDeleteResp        = sys.UserDeleteResp
	RoleUpdateReq         = sys.RoleUpdateReq
	DeptAddResp           = sys.DeptAddResp
	DeptListData          = sys.DeptListData
	SysLogAddResp         = sys.SysLogAddResp

	Sys interface {
		Login(ctx context.Context, in *LoginReq) (*LoginResp, error)
		UserInfo(ctx context.Context, in *InfoReq) (*InfoResp, error)
		UserAdd(ctx context.Context, in *UserAddReq) (*UserAddResp, error)
		UserList(ctx context.Context, in *UserListReq) (*UserListResp, error)
		UserUpdate(ctx context.Context, in *UserUpdateReq) (*UserUpdateResp, error)
		UserDelete(ctx context.Context, in *UserDeleteReq) (*UserDeleteResp, error)
		ReSetPassword(ctx context.Context, in *ReSetPasswordReq) (*ReSetPasswordResp, error)
		UpdateUserStatus(ctx context.Context, in *UserStatusReq) (*UserStatusResp, error)
		RoleAdd(ctx context.Context, in *RoleAddReq) (*RoleAddResp, error)
		RoleList(ctx context.Context, in *RoleListReq) (*RoleListResp, error)
		RoleUpdate(ctx context.Context, in *RoleUpdateReq) (*RoleUpdateResp, error)
		RoleDelete(ctx context.Context, in *RoleDeleteReq) (*RoleDeleteResp, error)
		UpdateRoleRole(ctx context.Context, in *UpdateRoleRoleReq) (*UpdateRoleRoleResp, error)
		QueryMenuByRoleId(ctx context.Context, in *QueryMenuByRoleIdReq) (*QueryMenuByRoleIdResp, error)
		MenuAdd(ctx context.Context, in *MenuAddReq) (*MenuAddResp, error)
		MenuList(ctx context.Context, in *MenuListReq) (*MenuListResp, error)
		MenuUpdate(ctx context.Context, in *MenuUpdateReq) (*MenuUpdateResp, error)
		MenuDelete(ctx context.Context, in *MenuDeleteReq) (*MenuDeleteResp, error)
		UpdateMenuRole(ctx context.Context, in *UpdateMenuRoleReq) (*UpdateMenuRoleResp, error)
		DictAdd(ctx context.Context, in *DictAddReq) (*DictAddResp, error)
		DictList(ctx context.Context, in *DictListReq) (*DictListResp, error)
		DictUpdate(ctx context.Context, in *DictUpdateReq) (*DictUpdateResp, error)
		DictDelete(ctx context.Context, in *DictDeleteReq) (*DictDeleteResp, error)
		DeptAdd(ctx context.Context, in *DeptAddReq) (*DeptAddResp, error)
		DeptList(ctx context.Context, in *DeptListReq) (*DeptListResp, error)
		DeptUpdate(ctx context.Context, in *DeptUpdateReq) (*DeptUpdateResp, error)
		DeptDelete(ctx context.Context, in *DeptDeleteReq) (*DeptDeleteResp, error)
		LoginLogAdd(ctx context.Context, in *LoginLogAddReq) (*LoginLogAddResp, error)
		LoginLogList(ctx context.Context, in *LoginLogListReq) (*LoginLogListResp, error)
		LoginLogDelete(ctx context.Context, in *LoginLogDeleteReq) (*LoginLogDeleteResp, error)
		SysLogAdd(ctx context.Context, in *SysLogAddReq) (*SysLogAddResp, error)
		SysLogList(ctx context.Context, in *SysLogListReq) (*SysLogListResp, error)
		SysLogDelete(ctx context.Context, in *SysLogDeleteReq) (*SysLogDeleteResp, error)
		ConfigAdd(ctx context.Context, in *ConfigAddReq) (*ConfigAddResp, error)
		ConfigList(ctx context.Context, in *ConfigListReq) (*ConfigListResp, error)
		ConfigUpdate(ctx context.Context, in *ConfigUpdateReq) (*ConfigUpdateResp, error)
		ConfigDelete(ctx context.Context, in *ConfigDeleteReq) (*ConfigDeleteResp, error)
		UpdateConfigRole(ctx context.Context, in *UpdateConfigRoleReq) (*UpdateConfigRoleResp, error)
	}

	defaultSys struct {
		cli zrpc.Client
	}
)

func NewSys(cli zrpc.Client) Sys {
	return &defaultSys{
		cli: cli,
	}
}

func (m *defaultSys) Login(ctx context.Context, in *LoginReq) (*LoginResp, error) {
	client := sys.NewSysClient(m.cli.Conn())
	return client.Login(ctx, in)
}

func (m *defaultSys) UserInfo(ctx context.Context, in *InfoReq) (*InfoResp, error) {
	client := sys.NewSysClient(m.cli.Conn())
	return client.UserInfo(ctx, in)
}

func (m *defaultSys) UserAdd(ctx context.Context, in *UserAddReq) (*UserAddResp, error) {
	client := sys.NewSysClient(m.cli.Conn())
	return client.UserAdd(ctx, in)
}

func (m *defaultSys) UserList(ctx context.Context, in *UserListReq) (*UserListResp, error) {
	client := sys.NewSysClient(m.cli.Conn())
	return client.UserList(ctx, in)
}

func (m *defaultSys) UserUpdate(ctx context.Context, in *UserUpdateReq) (*UserUpdateResp, error) {
	client := sys.NewSysClient(m.cli.Conn())
	return client.UserUpdate(ctx, in)
}

func (m *defaultSys) UserDelete(ctx context.Context, in *UserDeleteReq) (*UserDeleteResp, error) {
	client := sys.NewSysClient(m.cli.Conn())
	return client.UserDelete(ctx, in)
}

func (m *defaultSys) ReSetPassword(ctx context.Context, in *ReSetPasswordReq) (*ReSetPasswordResp, error) {
	client := sys.NewSysClient(m.cli.Conn())
	return client.ReSetPassword(ctx, in)
}

func (m *defaultSys) UpdateUserStatus(ctx context.Context, in *UserStatusReq) (*UserStatusResp, error) {
	client := sys.NewSysClient(m.cli.Conn())
	return client.UpdateUserStatus(ctx, in)
}

func (m *defaultSys) RoleAdd(ctx context.Context, in *RoleAddReq) (*RoleAddResp, error) {
	client := sys.NewSysClient(m.cli.Conn())
	return client.RoleAdd(ctx, in)
}

func (m *defaultSys) RoleList(ctx context.Context, in *RoleListReq) (*RoleListResp, error) {
	client := sys.NewSysClient(m.cli.Conn())
	return client.RoleList(ctx, in)
}

func (m *defaultSys) RoleUpdate(ctx context.Context, in *RoleUpdateReq) (*RoleUpdateResp, error) {
	client := sys.NewSysClient(m.cli.Conn())
	return client.RoleUpdate(ctx, in)
}

func (m *defaultSys) RoleDelete(ctx context.Context, in *RoleDeleteReq) (*RoleDeleteResp, error) {
	client := sys.NewSysClient(m.cli.Conn())
	return client.RoleDelete(ctx, in)
}

func (m *defaultSys) UpdateRoleRole(ctx context.Context, in *UpdateRoleRoleReq) (*UpdateRoleRoleResp, error) {
	client := sys.NewSysClient(m.cli.Conn())
	return client.UpdateRoleRole(ctx, in)
}

func (m *defaultSys) QueryMenuByRoleId(ctx context.Context, in *QueryMenuByRoleIdReq) (*QueryMenuByRoleIdResp, error) {
	client := sys.NewSysClient(m.cli.Conn())
	return client.QueryMenuByRoleId(ctx, in)
}

func (m *defaultSys) MenuAdd(ctx context.Context, in *MenuAddReq) (*MenuAddResp, error) {
	client := sys.NewSysClient(m.cli.Conn())
	return client.MenuAdd(ctx, in)
}

func (m *defaultSys) MenuList(ctx context.Context, in *MenuListReq) (*MenuListResp, error) {
	client := sys.NewSysClient(m.cli.Conn())
	return client.MenuList(ctx, in)
}

func (m *defaultSys) MenuUpdate(ctx context.Context, in *MenuUpdateReq) (*MenuUpdateResp, error) {
	client := sys.NewSysClient(m.cli.Conn())
	return client.MenuUpdate(ctx, in)
}

func (m *defaultSys) MenuDelete(ctx context.Context, in *MenuDeleteReq) (*MenuDeleteResp, error) {
	client := sys.NewSysClient(m.cli.Conn())
	return client.MenuDelete(ctx, in)
}

func (m *defaultSys) UpdateMenuRole(ctx context.Context, in *UpdateMenuRoleReq) (*UpdateMenuRoleResp, error) {
	client := sys.NewSysClient(m.cli.Conn())
	return client.UpdateMenuRole(ctx, in)
}

func (m *defaultSys) DictAdd(ctx context.Context, in *DictAddReq) (*DictAddResp, error) {
	client := sys.NewSysClient(m.cli.Conn())
	return client.DictAdd(ctx, in)
}

func (m *defaultSys) DictList(ctx context.Context, in *DictListReq) (*DictListResp, error) {
	client := sys.NewSysClient(m.cli.Conn())
	return client.DictList(ctx, in)
}

func (m *defaultSys) DictUpdate(ctx context.Context, in *DictUpdateReq) (*DictUpdateResp, error) {
	client := sys.NewSysClient(m.cli.Conn())
	return client.DictUpdate(ctx, in)
}

func (m *defaultSys) DictDelete(ctx context.Context, in *DictDeleteReq) (*DictDeleteResp, error) {
	client := sys.NewSysClient(m.cli.Conn())
	return client.DictDelete(ctx, in)
}

func (m *defaultSys) DeptAdd(ctx context.Context, in *DeptAddReq) (*DeptAddResp, error) {
	client := sys.NewSysClient(m.cli.Conn())
	return client.DeptAdd(ctx, in)
}

func (m *defaultSys) DeptList(ctx context.Context, in *DeptListReq) (*DeptListResp, error) {
	client := sys.NewSysClient(m.cli.Conn())
	return client.DeptList(ctx, in)
}

func (m *defaultSys) DeptUpdate(ctx context.Context, in *DeptUpdateReq) (*DeptUpdateResp, error) {
	client := sys.NewSysClient(m.cli.Conn())
	return client.DeptUpdate(ctx, in)
}

func (m *defaultSys) DeptDelete(ctx context.Context, in *DeptDeleteReq) (*DeptDeleteResp, error) {
	client := sys.NewSysClient(m.cli.Conn())
	return client.DeptDelete(ctx, in)
}

func (m *defaultSys) LoginLogAdd(ctx context.Context, in *LoginLogAddReq) (*LoginLogAddResp, error) {
	client := sys.NewSysClient(m.cli.Conn())
	return client.LoginLogAdd(ctx, in)
}

func (m *defaultSys) LoginLogList(ctx context.Context, in *LoginLogListReq) (*LoginLogListResp, error) {
	client := sys.NewSysClient(m.cli.Conn())
	return client.LoginLogList(ctx, in)
}

func (m *defaultSys) LoginLogDelete(ctx context.Context, in *LoginLogDeleteReq) (*LoginLogDeleteResp, error) {
	client := sys.NewSysClient(m.cli.Conn())
	return client.LoginLogDelete(ctx, in)
}

func (m *defaultSys) SysLogAdd(ctx context.Context, in *SysLogAddReq) (*SysLogAddResp, error) {
	client := sys.NewSysClient(m.cli.Conn())
	return client.SysLogAdd(ctx, in)
}

func (m *defaultSys) SysLogList(ctx context.Context, in *SysLogListReq) (*SysLogListResp, error) {
	client := sys.NewSysClient(m.cli.Conn())
	return client.SysLogList(ctx, in)
}

func (m *defaultSys) SysLogDelete(ctx context.Context, in *SysLogDeleteReq) (*SysLogDeleteResp, error) {
	client := sys.NewSysClient(m.cli.Conn())
	return client.SysLogDelete(ctx, in)
}

func (m *defaultSys) ConfigAdd(ctx context.Context, in *ConfigAddReq) (*ConfigAddResp, error) {
	client := sys.NewSysClient(m.cli.Conn())
	return client.ConfigAdd(ctx, in)
}

func (m *defaultSys) ConfigList(ctx context.Context, in *ConfigListReq) (*ConfigListResp, error) {
	client := sys.NewSysClient(m.cli.Conn())
	return client.ConfigList(ctx, in)
}

func (m *defaultSys) ConfigUpdate(ctx context.Context, in *ConfigUpdateReq) (*ConfigUpdateResp, error) {
	client := sys.NewSysClient(m.cli.Conn())
	return client.ConfigUpdate(ctx, in)
}

func (m *defaultSys) ConfigDelete(ctx context.Context, in *ConfigDeleteReq) (*ConfigDeleteResp, error) {
	client := sys.NewSysClient(m.cli.Conn())
	return client.ConfigDelete(ctx, in)
}

func (m *defaultSys) UpdateConfigRole(ctx context.Context, in *UpdateConfigRoleReq) (*UpdateConfigRoleResp, error) {
	client := sys.NewSysClient(m.cli.Conn())
	return client.UpdateConfigRole(ctx, in)
}
