// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: pms.proto

package productspecvalueservice

import (
	"context"

	"github.com/feihua/zero-admin/rpc/pms/pmsclient"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddProductSpecValueReq           = pmsclient.AddProductSpecValueReq
	AddProductSpecValueResp          = pmsclient.AddProductSpecValueResp
	DeleteProductSpecValueReq        = pmsclient.DeleteProductSpecValueReq
	DeleteProductSpecValueResp       = pmsclient.DeleteProductSpecValueResp
	ProductSpecValueListData         = pmsclient.ProductSpecValueListData
	QueryProductSpecValueDetailReq   = pmsclient.QueryProductSpecValueDetailReq
	QueryProductSpecValueDetailResp  = pmsclient.QueryProductSpecValueDetailResp
	QueryProductSpecValueListReq     = pmsclient.QueryProductSpecValueListReq
	QueryProductSpecValueListResp    = pmsclient.QueryProductSpecValueListResp
	UpdateProductSpecValueReq        = pmsclient.UpdateProductSpecValueReq
	UpdateProductSpecValueResp       = pmsclient.UpdateProductSpecValueResp
	UpdateProductSpecValueStatusReq  = pmsclient.UpdateProductSpecValueStatusReq
	UpdateProductSpecValueStatusResp = pmsclient.UpdateProductSpecValueStatusResp

	ProductSpecValueService interface {
		// 添加商品规格值
		AddProductSpecValue(ctx context.Context, in *AddProductSpecValueReq, opts ...grpc.CallOption) (*AddProductSpecValueResp, error)
		// 删除商品规格值
		DeleteProductSpecValue(ctx context.Context, in *DeleteProductSpecValueReq, opts ...grpc.CallOption) (*DeleteProductSpecValueResp, error)
		// 更新商品规格值
		UpdateProductSpecValue(ctx context.Context, in *UpdateProductSpecValueReq, opts ...grpc.CallOption) (*UpdateProductSpecValueResp, error)
		// 更新商品规格值状态
		UpdateProductSpecValueStatus(ctx context.Context, in *UpdateProductSpecValueStatusReq, opts ...grpc.CallOption) (*UpdateProductSpecValueStatusResp, error)
		// 查询商品规格值详情
		QueryProductSpecValueDetail(ctx context.Context, in *QueryProductSpecValueDetailReq, opts ...grpc.CallOption) (*QueryProductSpecValueDetailResp, error)
		// 查询商品规格值列表
		QueryProductSpecValueList(ctx context.Context, in *QueryProductSpecValueListReq, opts ...grpc.CallOption) (*QueryProductSpecValueListResp, error)
	}

	defaultProductSpecValueService struct {
		cli zrpc.Client
	}
)

func NewProductSpecValueService(cli zrpc.Client) ProductSpecValueService {
	return &defaultProductSpecValueService{
		cli: cli,
	}
}

// 添加商品规格值
func (m *defaultProductSpecValueService) AddProductSpecValue(ctx context.Context, in *AddProductSpecValueReq, opts ...grpc.CallOption) (*AddProductSpecValueResp, error) {
	client := pmsclient.NewProductSpecValueServiceClient(m.cli.Conn())
	return client.AddProductSpecValue(ctx, in, opts...)
}

// 删除商品规格值
func (m *defaultProductSpecValueService) DeleteProductSpecValue(ctx context.Context, in *DeleteProductSpecValueReq, opts ...grpc.CallOption) (*DeleteProductSpecValueResp, error) {
	client := pmsclient.NewProductSpecValueServiceClient(m.cli.Conn())
	return client.DeleteProductSpecValue(ctx, in, opts...)
}

// 更新商品规格值
func (m *defaultProductSpecValueService) UpdateProductSpecValue(ctx context.Context, in *UpdateProductSpecValueReq, opts ...grpc.CallOption) (*UpdateProductSpecValueResp, error) {
	client := pmsclient.NewProductSpecValueServiceClient(m.cli.Conn())
	return client.UpdateProductSpecValue(ctx, in, opts...)
}

// 更新商品规格值状态
func (m *defaultProductSpecValueService) UpdateProductSpecValueStatus(ctx context.Context, in *UpdateProductSpecValueStatusReq, opts ...grpc.CallOption) (*UpdateProductSpecValueStatusResp, error) {
	client := pmsclient.NewProductSpecValueServiceClient(m.cli.Conn())
	return client.UpdateProductSpecValueStatus(ctx, in, opts...)
}

// 查询商品规格值详情
func (m *defaultProductSpecValueService) QueryProductSpecValueDetail(ctx context.Context, in *QueryProductSpecValueDetailReq, opts ...grpc.CallOption) (*QueryProductSpecValueDetailResp, error) {
	client := pmsclient.NewProductSpecValueServiceClient(m.cli.Conn())
	return client.QueryProductSpecValueDetail(ctx, in, opts...)
}

// 查询商品规格值列表
func (m *defaultProductSpecValueService) QueryProductSpecValueList(ctx context.Context, in *QueryProductSpecValueListReq, opts ...grpc.CallOption) (*QueryProductSpecValueListResp, error) {
	client := pmsclient.NewProductSpecValueServiceClient(m.cli.Conn())
	return client.QueryProductSpecValueList(ctx, in, opts...)
}
