// Code generated by goctl. DO NOT EDIT.
// Source: sms.proto

package server

import (
	"context"

	"github.com/feihua/zero-admin/rpc/sms/internal/logic/homenewproductservice"
	"github.com/feihua/zero-admin/rpc/sms/internal/svc"
	"github.com/feihua/zero-admin/rpc/sms/smsclient"
)

type HomeNewProductServiceServer struct {
	svcCtx *svc.ServiceContext
	smsclient.UnimplementedHomeNewProductServiceServer
}

func NewHomeNewProductServiceServer(svcCtx *svc.ServiceContext) *HomeNewProductServiceServer {
	return &HomeNewProductServiceServer{
		svcCtx: svcCtx,
	}
}

// 添加新鲜好物表
func (s *HomeNewProductServiceServer) AddHomeNewProduct(ctx context.Context, in *smsclient.AddHomeNewProductReq) (*smsclient.AddHomeNewProductResp, error) {
	l := homenewproductservicelogic.NewAddHomeNewProductLogic(ctx, s.svcCtx)
	return l.AddHomeNewProduct(in)
}

// 删除新鲜好物表
func (s *HomeNewProductServiceServer) DeleteHomeNewProduct(ctx context.Context, in *smsclient.DeleteHomeNewProductReq) (*smsclient.DeleteHomeNewProductResp, error) {
	l := homenewproductservicelogic.NewDeleteHomeNewProductLogic(ctx, s.svcCtx)
	return l.DeleteHomeNewProduct(in)
}

// 修改首页新品排序
func (s *HomeNewProductServiceServer) UpdateNewProductSort(ctx context.Context, in *smsclient.UpdateNewProductSortReq) (*smsclient.UpdateNewProductSortResp, error) {
	l := homenewproductservicelogic.NewUpdateNewProductSortLogic(ctx, s.svcCtx)
	return l.UpdateNewProductSort(in)
}

// 更新新鲜好物表状态
func (s *HomeNewProductServiceServer) UpdateHomeNewProductStatus(ctx context.Context, in *smsclient.UpdateHomeNewProductStatusReq) (*smsclient.UpdateHomeNewProductStatusResp, error) {
	l := homenewproductservicelogic.NewUpdateHomeNewProductStatusLogic(ctx, s.svcCtx)
	return l.UpdateHomeNewProductStatus(in)
}

// 查询新鲜好物表详情
func (s *HomeNewProductServiceServer) QueryHomeNewProductDetail(ctx context.Context, in *smsclient.QueryHomeNewProductDetailReq) (*smsclient.QueryHomeNewProductDetailResp, error) {
	l := homenewproductservicelogic.NewQueryHomeNewProductDetailLogic(ctx, s.svcCtx)
	return l.QueryHomeNewProductDetail(in)
}

// 查询新鲜好物表列表
func (s *HomeNewProductServiceServer) QueryHomeNewProductList(ctx context.Context, in *smsclient.QueryHomeNewProductListReq) (*smsclient.QueryHomeNewProductListResp, error) {
	l := homenewproductservicelogic.NewQueryHomeNewProductListLogic(ctx, s.svcCtx)
	return l.QueryHomeNewProductList(in)
}
