// Code generated by goctl. DO NOT EDIT.
// Source: cms.proto

package helpcategoryservice

import (
	"context"

	"github.com/feihua/zero-admin/rpc/cms/cmsclient"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddHelpCategoryReq                        = cmsclient.AddHelpCategoryReq
	AddHelpCategoryResp                       = cmsclient.AddHelpCategoryResp
	AddHelpReq                                = cmsclient.AddHelpReq
	AddHelpResp                               = cmsclient.AddHelpResp
	AddMemberReportReq                        = cmsclient.AddMemberReportReq
	AddMemberReportResp                       = cmsclient.AddMemberReportResp
	AddPreferredAreaProductRelationReq        = cmsclient.AddPreferredAreaProductRelationReq
	AddPreferredAreaProductRelationResp       = cmsclient.AddPreferredAreaProductRelationResp
	AddPreferredAreaReq                       = cmsclient.AddPreferredAreaReq
	AddPreferredAreaResp                      = cmsclient.AddPreferredAreaResp
	AddSubjectCategoryReq                     = cmsclient.AddSubjectCategoryReq
	AddSubjectCategoryResp                    = cmsclient.AddSubjectCategoryResp
	AddSubjectCommentReq                      = cmsclient.AddSubjectCommentReq
	AddSubjectCommentResp                     = cmsclient.AddSubjectCommentResp
	AddSubjectProductRelationReq              = cmsclient.AddSubjectProductRelationReq
	AddSubjectProductRelationResp             = cmsclient.AddSubjectProductRelationResp
	AddSubjectReq                             = cmsclient.AddSubjectReq
	AddSubjectResp                            = cmsclient.AddSubjectResp
	AddTopicCategoryReq                       = cmsclient.AddTopicCategoryReq
	AddTopicCategoryResp                      = cmsclient.AddTopicCategoryResp
	AddTopicCommentReq                        = cmsclient.AddTopicCommentReq
	AddTopicCommentResp                       = cmsclient.AddTopicCommentResp
	AddTopicReq                               = cmsclient.AddTopicReq
	AddTopicResp                              = cmsclient.AddTopicResp
	DeleteHelpCategoryReq                     = cmsclient.DeleteHelpCategoryReq
	DeleteHelpCategoryResp                    = cmsclient.DeleteHelpCategoryResp
	DeleteHelpReq                             = cmsclient.DeleteHelpReq
	DeleteHelpResp                            = cmsclient.DeleteHelpResp
	DeleteMemberReportReq                     = cmsclient.DeleteMemberReportReq
	DeleteMemberReportResp                    = cmsclient.DeleteMemberReportResp
	DeletePreferredAreaReq                    = cmsclient.DeletePreferredAreaReq
	DeletePreferredAreaResp                   = cmsclient.DeletePreferredAreaResp
	DeleteSubjectCategoryReq                  = cmsclient.DeleteSubjectCategoryReq
	DeleteSubjectCategoryResp                 = cmsclient.DeleteSubjectCategoryResp
	DeleteSubjectCommentReq                   = cmsclient.DeleteSubjectCommentReq
	DeleteSubjectCommentResp                  = cmsclient.DeleteSubjectCommentResp
	DeleteSubjectReq                          = cmsclient.DeleteSubjectReq
	DeleteSubjectResp                         = cmsclient.DeleteSubjectResp
	DeleteTopicCategoryReq                    = cmsclient.DeleteTopicCategoryReq
	DeleteTopicCategoryResp                   = cmsclient.DeleteTopicCategoryResp
	DeleteTopicCommentReq                     = cmsclient.DeleteTopicCommentReq
	DeleteTopicCommentResp                    = cmsclient.DeleteTopicCommentResp
	DeleteTopicReq                            = cmsclient.DeleteTopicReq
	DeleteTopicResp                           = cmsclient.DeleteTopicResp
	HelpCategoryListData                      = cmsclient.HelpCategoryListData
	HelpListData                              = cmsclient.HelpListData
	MemberReportListData                      = cmsclient.MemberReportListData
	PreferredAreaListData                     = cmsclient.PreferredAreaListData
	QueryHelpCategoryDetailReq                = cmsclient.QueryHelpCategoryDetailReq
	QueryHelpCategoryDetailResp               = cmsclient.QueryHelpCategoryDetailResp
	QueryHelpCategoryListReq                  = cmsclient.QueryHelpCategoryListReq
	QueryHelpCategoryListResp                 = cmsclient.QueryHelpCategoryListResp
	QueryHelpDetailReq                        = cmsclient.QueryHelpDetailReq
	QueryHelpDetailResp                       = cmsclient.QueryHelpDetailResp
	QueryHelpListReq                          = cmsclient.QueryHelpListReq
	QueryHelpListResp                         = cmsclient.QueryHelpListResp
	QueryMemberReportDetailReq                = cmsclient.QueryMemberReportDetailReq
	QueryMemberReportDetailResp               = cmsclient.QueryMemberReportDetailResp
	QueryMemberReportListReq                  = cmsclient.QueryMemberReportListReq
	QueryMemberReportListResp                 = cmsclient.QueryMemberReportListResp
	QueryPreferredAreaDetailReq               = cmsclient.QueryPreferredAreaDetailReq
	QueryPreferredAreaDetailResp              = cmsclient.QueryPreferredAreaDetailResp
	QueryPreferredAreaListReq                 = cmsclient.QueryPreferredAreaListReq
	QueryPreferredAreaListResp                = cmsclient.QueryPreferredAreaListResp
	QueryPreferredAreaProductRelationListReq  = cmsclient.QueryPreferredAreaProductRelationListReq
	QueryPreferredAreaProductRelationListResp = cmsclient.QueryPreferredAreaProductRelationListResp
	QuerySubjectCategoryDetailReq             = cmsclient.QuerySubjectCategoryDetailReq
	QuerySubjectCategoryDetailResp            = cmsclient.QuerySubjectCategoryDetailResp
	QuerySubjectCategoryListReq               = cmsclient.QuerySubjectCategoryListReq
	QuerySubjectCategoryListResp              = cmsclient.QuerySubjectCategoryListResp
	QuerySubjectCommentDetailReq              = cmsclient.QuerySubjectCommentDetailReq
	QuerySubjectCommentDetailResp             = cmsclient.QuerySubjectCommentDetailResp
	QuerySubjectCommentListReq                = cmsclient.QuerySubjectCommentListReq
	QuerySubjectCommentListResp               = cmsclient.QuerySubjectCommentListResp
	QuerySubjectDetailReq                     = cmsclient.QuerySubjectDetailReq
	QuerySubjectDetailResp                    = cmsclient.QuerySubjectDetailResp
	QuerySubjectListReq                       = cmsclient.QuerySubjectListReq
	QuerySubjectListResp                      = cmsclient.QuerySubjectListResp
	QuerySubjectProductRelationListReq        = cmsclient.QuerySubjectProductRelationListReq
	QuerySubjectProductRelationListResp       = cmsclient.QuerySubjectProductRelationListResp
	QueryTopicCategoryDetailReq               = cmsclient.QueryTopicCategoryDetailReq
	QueryTopicCategoryDetailResp              = cmsclient.QueryTopicCategoryDetailResp
	QueryTopicCategoryListReq                 = cmsclient.QueryTopicCategoryListReq
	QueryTopicCategoryListResp                = cmsclient.QueryTopicCategoryListResp
	QueryTopicCommentDetailReq                = cmsclient.QueryTopicCommentDetailReq
	QueryTopicCommentDetailResp               = cmsclient.QueryTopicCommentDetailResp
	QueryTopicCommentListReq                  = cmsclient.QueryTopicCommentListReq
	QueryTopicCommentListResp                 = cmsclient.QueryTopicCommentListResp
	QueryTopicDetailReq                       = cmsclient.QueryTopicDetailReq
	QueryTopicDetailResp                      = cmsclient.QueryTopicDetailResp
	QueryTopicListReq                         = cmsclient.QueryTopicListReq
	QueryTopicListResp                        = cmsclient.QueryTopicListResp
	SubjectCategoryListData                   = cmsclient.SubjectCategoryListData
	SubjectCommentListData                    = cmsclient.SubjectCommentListData
	SubjectListByIdsReq                       = cmsclient.SubjectListByIdsReq
	SubjectListData                           = cmsclient.SubjectListData
	TopicCategoryListData                     = cmsclient.TopicCategoryListData
	TopicCommentListData                      = cmsclient.TopicCommentListData
	TopicListData                             = cmsclient.TopicListData
	UpdateHelpCategoryReq                     = cmsclient.UpdateHelpCategoryReq
	UpdateHelpCategoryResp                    = cmsclient.UpdateHelpCategoryResp
	UpdateHelpCategoryStatusReq               = cmsclient.UpdateHelpCategoryStatusReq
	UpdateHelpCategoryStatusResp              = cmsclient.UpdateHelpCategoryStatusResp
	UpdateHelpReq                             = cmsclient.UpdateHelpReq
	UpdateHelpResp                            = cmsclient.UpdateHelpResp
	UpdateHelpStatusReq                       = cmsclient.UpdateHelpStatusReq
	UpdateHelpStatusResp                      = cmsclient.UpdateHelpStatusResp
	UpdateMemberReportReq                     = cmsclient.UpdateMemberReportReq
	UpdateMemberReportResp                    = cmsclient.UpdateMemberReportResp
	UpdateMemberReportStatusReq               = cmsclient.UpdateMemberReportStatusReq
	UpdateMemberReportStatusResp              = cmsclient.UpdateMemberReportStatusResp
	UpdatePreferredAreaReq                    = cmsclient.UpdatePreferredAreaReq
	UpdatePreferredAreaResp                   = cmsclient.UpdatePreferredAreaResp
	UpdatePreferredAreaStatusReq              = cmsclient.UpdatePreferredAreaStatusReq
	UpdatePreferredAreaStatusResp             = cmsclient.UpdatePreferredAreaStatusResp
	UpdateSubjectCategoryReq                  = cmsclient.UpdateSubjectCategoryReq
	UpdateSubjectCategoryResp                 = cmsclient.UpdateSubjectCategoryResp
	UpdateSubjectCategoryStatusReq            = cmsclient.UpdateSubjectCategoryStatusReq
	UpdateSubjectCategoryStatusResp           = cmsclient.UpdateSubjectCategoryStatusResp
	UpdateSubjectCommentReq                   = cmsclient.UpdateSubjectCommentReq
	UpdateSubjectCommentResp                  = cmsclient.UpdateSubjectCommentResp
	UpdateSubjectCommentStatusReq             = cmsclient.UpdateSubjectCommentStatusReq
	UpdateSubjectCommentStatusResp            = cmsclient.UpdateSubjectCommentStatusResp
	UpdateSubjectRecommendStatusReq           = cmsclient.UpdateSubjectRecommendStatusReq
	UpdateSubjectRecommendStatusResp          = cmsclient.UpdateSubjectRecommendStatusResp
	UpdateSubjectReq                          = cmsclient.UpdateSubjectReq
	UpdateSubjectResp                         = cmsclient.UpdateSubjectResp
	UpdateSubjectStatusReq                    = cmsclient.UpdateSubjectStatusReq
	UpdateSubjectStatusResp                   = cmsclient.UpdateSubjectStatusResp
	UpdateTopicCategoryReq                    = cmsclient.UpdateTopicCategoryReq
	UpdateTopicCategoryResp                   = cmsclient.UpdateTopicCategoryResp
	UpdateTopicCategoryStatusReq              = cmsclient.UpdateTopicCategoryStatusReq
	UpdateTopicCategoryStatusResp             = cmsclient.UpdateTopicCategoryStatusResp
	UpdateTopicCommentReq                     = cmsclient.UpdateTopicCommentReq
	UpdateTopicCommentResp                    = cmsclient.UpdateTopicCommentResp
	UpdateTopicCommentStatusReq               = cmsclient.UpdateTopicCommentStatusReq
	UpdateTopicCommentStatusResp              = cmsclient.UpdateTopicCommentStatusResp
	UpdateTopicReq                            = cmsclient.UpdateTopicReq
	UpdateTopicResp                           = cmsclient.UpdateTopicResp
	UpdateTopicStatusReq                      = cmsclient.UpdateTopicStatusReq
	UpdateTopicStatusResp                     = cmsclient.UpdateTopicStatusResp

	HelpCategoryService interface {
		// 添加帮助分类
		AddHelpCategory(ctx context.Context, in *AddHelpCategoryReq, opts ...grpc.CallOption) (*AddHelpCategoryResp, error)
		// 删除帮助分类
		DeleteHelpCategory(ctx context.Context, in *DeleteHelpCategoryReq, opts ...grpc.CallOption) (*DeleteHelpCategoryResp, error)
		// 更新帮助分类
		UpdateHelpCategory(ctx context.Context, in *UpdateHelpCategoryReq, opts ...grpc.CallOption) (*UpdateHelpCategoryResp, error)
		// 更新帮助分类状态
		UpdateHelpCategoryStatus(ctx context.Context, in *UpdateHelpCategoryStatusReq, opts ...grpc.CallOption) (*UpdateHelpCategoryStatusResp, error)
		// 查询帮助分类详情
		QueryHelpCategoryDetail(ctx context.Context, in *QueryHelpCategoryDetailReq, opts ...grpc.CallOption) (*QueryHelpCategoryDetailResp, error)
		// 查询帮助分类列表
		QueryHelpCategoryList(ctx context.Context, in *QueryHelpCategoryListReq, opts ...grpc.CallOption) (*QueryHelpCategoryListResp, error)
	}

	defaultHelpCategoryService struct {
		cli zrpc.Client
	}
)

func NewHelpCategoryService(cli zrpc.Client) HelpCategoryService {
	return &defaultHelpCategoryService{
		cli: cli,
	}
}

// 添加帮助分类
func (m *defaultHelpCategoryService) AddHelpCategory(ctx context.Context, in *AddHelpCategoryReq, opts ...grpc.CallOption) (*AddHelpCategoryResp, error) {
	client := cmsclient.NewHelpCategoryServiceClient(m.cli.Conn())
	return client.AddHelpCategory(ctx, in, opts...)
}

// 删除帮助分类
func (m *defaultHelpCategoryService) DeleteHelpCategory(ctx context.Context, in *DeleteHelpCategoryReq, opts ...grpc.CallOption) (*DeleteHelpCategoryResp, error) {
	client := cmsclient.NewHelpCategoryServiceClient(m.cli.Conn())
	return client.DeleteHelpCategory(ctx, in, opts...)
}

// 更新帮助分类
func (m *defaultHelpCategoryService) UpdateHelpCategory(ctx context.Context, in *UpdateHelpCategoryReq, opts ...grpc.CallOption) (*UpdateHelpCategoryResp, error) {
	client := cmsclient.NewHelpCategoryServiceClient(m.cli.Conn())
	return client.UpdateHelpCategory(ctx, in, opts...)
}

// 更新帮助分类状态
func (m *defaultHelpCategoryService) UpdateHelpCategoryStatus(ctx context.Context, in *UpdateHelpCategoryStatusReq, opts ...grpc.CallOption) (*UpdateHelpCategoryStatusResp, error) {
	client := cmsclient.NewHelpCategoryServiceClient(m.cli.Conn())
	return client.UpdateHelpCategoryStatus(ctx, in, opts...)
}

// 查询帮助分类详情
func (m *defaultHelpCategoryService) QueryHelpCategoryDetail(ctx context.Context, in *QueryHelpCategoryDetailReq, opts ...grpc.CallOption) (*QueryHelpCategoryDetailResp, error) {
	client := cmsclient.NewHelpCategoryServiceClient(m.cli.Conn())
	return client.QueryHelpCategoryDetail(ctx, in, opts...)
}

// 查询帮助分类列表
func (m *defaultHelpCategoryService) QueryHelpCategoryList(ctx context.Context, in *QueryHelpCategoryListReq, opts ...grpc.CallOption) (*QueryHelpCategoryListResp, error) {
	client := cmsclient.NewHelpCategoryServiceClient(m.cli.Conn())
	return client.QueryHelpCategoryList(ctx, in, opts...)
}
