// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: cms.proto

package helpcategoryservice

import (
	"context"

	"github.com/feihua/zero-admin/rpc/cms/cmsclient"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddHelpCategoryReq           = cmsclient.AddHelpCategoryReq
	AddHelpCategoryResp          = cmsclient.AddHelpCategoryResp
	DeleteHelpCategoryReq        = cmsclient.DeleteHelpCategoryReq
	DeleteHelpCategoryResp       = cmsclient.DeleteHelpCategoryResp
	HelpCategoryListData         = cmsclient.HelpCategoryListData
	QueryHelpCategoryDetailReq   = cmsclient.QueryHelpCategoryDetailReq
	QueryHelpCategoryDetailResp  = cmsclient.QueryHelpCategoryDetailResp
	QueryHelpCategoryListReq     = cmsclient.QueryHelpCategoryListReq
	QueryHelpCategoryListResp    = cmsclient.QueryHelpCategoryListResp
	UpdateHelpCategoryReq        = cmsclient.UpdateHelpCategoryReq
	UpdateHelpCategoryResp       = cmsclient.UpdateHelpCategoryResp
	UpdateHelpCategoryStatusReq  = cmsclient.UpdateHelpCategoryStatusReq
	UpdateHelpCategoryStatusResp = cmsclient.UpdateHelpCategoryStatusResp

	HelpCategoryService interface {
		// 添加帮助分类
		AddHelpCategory(ctx context.Context, in *AddHelpCategoryReq, opts ...grpc.CallOption) (*AddHelpCategoryResp, error)
		// 删除帮助分类
		DeleteHelpCategory(ctx context.Context, in *DeleteHelpCategoryReq, opts ...grpc.CallOption) (*DeleteHelpCategoryResp, error)
		// 更新帮助分类
		UpdateHelpCategory(ctx context.Context, in *UpdateHelpCategoryReq, opts ...grpc.CallOption) (*UpdateHelpCategoryResp, error)
		// 更新帮助分类状态
		UpdateHelpCategoryStatus(ctx context.Context, in *UpdateHelpCategoryStatusReq, opts ...grpc.CallOption) (*UpdateHelpCategoryStatusResp, error)
		// 查询帮助分类详情
		QueryHelpCategoryDetail(ctx context.Context, in *QueryHelpCategoryDetailReq, opts ...grpc.CallOption) (*QueryHelpCategoryDetailResp, error)
		// 查询帮助分类列表
		QueryHelpCategoryList(ctx context.Context, in *QueryHelpCategoryListReq, opts ...grpc.CallOption) (*QueryHelpCategoryListResp, error)
	}

	defaultHelpCategoryService struct {
		cli zrpc.Client
	}
)

func NewHelpCategoryService(cli zrpc.Client) HelpCategoryService {
	return &defaultHelpCategoryService{
		cli: cli,
	}
}

// 添加帮助分类
func (m *defaultHelpCategoryService) AddHelpCategory(ctx context.Context, in *AddHelpCategoryReq, opts ...grpc.CallOption) (*AddHelpCategoryResp, error) {
	client := cmsclient.NewHelpCategoryServiceClient(m.cli.Conn())
	return client.AddHelpCategory(ctx, in, opts...)
}

// 删除帮助分类
func (m *defaultHelpCategoryService) DeleteHelpCategory(ctx context.Context, in *DeleteHelpCategoryReq, opts ...grpc.CallOption) (*DeleteHelpCategoryResp, error) {
	client := cmsclient.NewHelpCategoryServiceClient(m.cli.Conn())
	return client.DeleteHelpCategory(ctx, in, opts...)
}

// 更新帮助分类
func (m *defaultHelpCategoryService) UpdateHelpCategory(ctx context.Context, in *UpdateHelpCategoryReq, opts ...grpc.CallOption) (*UpdateHelpCategoryResp, error) {
	client := cmsclient.NewHelpCategoryServiceClient(m.cli.Conn())
	return client.UpdateHelpCategory(ctx, in, opts...)
}

// 更新帮助分类状态
func (m *defaultHelpCategoryService) UpdateHelpCategoryStatus(ctx context.Context, in *UpdateHelpCategoryStatusReq, opts ...grpc.CallOption) (*UpdateHelpCategoryStatusResp, error) {
	client := cmsclient.NewHelpCategoryServiceClient(m.cli.Conn())
	return client.UpdateHelpCategoryStatus(ctx, in, opts...)
}

// 查询帮助分类详情
func (m *defaultHelpCategoryService) QueryHelpCategoryDetail(ctx context.Context, in *QueryHelpCategoryDetailReq, opts ...grpc.CallOption) (*QueryHelpCategoryDetailResp, error) {
	client := cmsclient.NewHelpCategoryServiceClient(m.cli.Conn())
	return client.QueryHelpCategoryDetail(ctx, in, opts...)
}

// 查询帮助分类列表
func (m *defaultHelpCategoryService) QueryHelpCategoryList(ctx context.Context, in *QueryHelpCategoryListReq, opts ...grpc.CallOption) (*QueryHelpCategoryListResp, error) {
	client := cmsclient.NewHelpCategoryServiceClient(m.cli.Conn())
	return client.QueryHelpCategoryList(ctx, in, opts...)
}
