### app会员登录
POST {{host}}/api/member/login
Content-Type: application/json

{
  "account": "koobe",
  "password": "123456"
}
> {% client.global.set("token", response.body.data.token); %}

### 添加会员个人的收货地址
POST {{host}}/api/member/address/addMemberAddress
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "koobe",
  "phoneNumber": "13144410222",
  "defaultStatus": 0,
  "postCode": "228000",
  "province": "广东省",
  "city": "广州市",
  "region": "天河区",
  "detailAddress": "测试详细地址2"
}

### 删除会员个人的收货地址
GET {{host}}/api/member/address/deleteMemberAddress?ids=5
Authorization: Bearer {{token}}

### 修改会员个人的收货地址
POST {{host}}/api/member/address/updateMemberAddress
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id": 4,
  "memberId": 2,
  "name": "koobe",
  "phoneNumber": "13144410222",
  "defaultStatus": 0,
  "postCode": "647000",
  "province": "广东省",
  "city": "广州市",
  "region": "天河区",
  "detailAddress": "测试详细地址2"
}

### 获取会员个人的收货地址
GET {{host}}/api/member/address/queryMemberAddressList
Authorization: Bearer {{token}}
