### app会员登录
POST {{host}}/api/member/login
Content-Type: application/json

{
  "account": "koobe",
  "password": "123456"
}
> {% client.global.set("token", response.body.data.token); %}

### 添加会员个人的收货地址
POST {{host}}/api/member/address/addMemberAddress
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "receiverName": "张三111111111111",
  "receiverPhone": "13800138001",
  "province": "广东省",
  "city": "深圳市",
  "district": "南山区",
  "detailAddress": "科技园科兴科学园B座",
  "postalCode": "518057",
  "tag": "公司",
  "isDefault": 1
}

### 删除会员个人的收货地址
GET {{host}}/api/member/address/deleteMemberAddress?ids=16
Authorization: Bearer {{token}}

### 修改会员个人的收货地址
POST {{host}}/api/member/address/updateMemberAddress
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id": 13,
  "receiverName": "张三1123213",
  "receiverPhone": "13800138001",
  "province": "广东省",
  "city": "深圳市",
  "district": "南山区",
  "detailAddress": "科技园科兴科学园B座",
  "postalCode": "518057",
  "tag": "公司",
  "isDefault": 1
}

### 修改会员个人的收货地址状态
POST {{host}}/api/member/address/updateMemberAddressStatus
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id": 1,
  "isDefault": 1
}

### 根据会员id获取会员个人的收货地址详细信息
GET {{host}}/api/member/address/queryMemberAddressDetail?id=15
Authorization: Bearer {{token}}

### 获取会员个人的收货地址
GET {{host}}/api/member/address/queryMemberAddressList
Authorization: Bearer {{token}}
