### app会员登录
POST {{host}}/api/member/login
Content-Type: application/json

{
  "mobile": "13800138001",
  "password": "123456"
}
> {% client.global.set("token", response.body.data.token); %}



### 添加会员个人的收藏
POST {{host}}/api/member/addtCollection
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "memberIcon": "http://129.204.203.29/apple_c.jpg",
  "productId": 6,
  "productName": "苹果（Apple）MacBook Pro Air 超薄商务办公 剪辑设计学生游戏99新13寸Pro丨i5+8G+512G固态丨",
  "productPic": "http://129.204.203.29/apple_c.jpg",
  "productSubTitle": "春节特卖会，精选好物五折起，不容错过",
  "productPrice": 12999
}

### 删除会员个人的收藏
GET {{host}}/api/member/deleteCollection?ids=13
Authorization: Bearer {{token}}

### 获取会员个人的收藏
GET {{host}}/api/member/queryCollectionList
Authorization: Bearer {{token}}

### 清空会员个人的收藏
GET {{host}}/api/member/clearCollection
Authorization: Bearer {{token}}

