### app会员登录
POST {{host}}/api/member/login
Content-Type: application/json

{
  "mobile": "13800138001",
  "password": "123456"
}
> {% client.global.set("token", response.body.data.token); %}


### 添加会员个人的浏览记录
POST {{host}}/api/member/addReadHistory
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "memberIcon": "http://129.204.203.29/xiaomi_s.jpg",
  "productId": 2,
  "productName": "小米（MI）REDMI Note15 Pro 天玑7400-Ultra 7000mAh 龙晶玻璃十倍抗摔 IP68 8+256 子夜黑 红米 5G手机",
  "productPic": "http://129.204.203.29/xiaomi_s.jpg",
  "productSubTitle": "新年狂欢购，限时特惠价，品质好物带回家",
  "productPrice": 5999
}

### 删除会员个人的浏览记录
GET {{host}}/api/member/deleteReadHistory?ids=13
Authorization: Bearer {{token}}

### 获取会员个人的浏览记录
GET {{host}}/api/member/queryReadHistoryList
Authorization: Bearer {{token}}

### 清空会员个人的浏览记录
GET {{host}}/api/member/clearReadHistory
Authorization: Bearer {{token}}
