// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: cms.proto

package subjectcommentservice

import (
	"context"

	"github.com/feihua/zero-admin/rpc/cms/cmsclient"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddSubjectCommentReq           = cmsclient.AddSubjectCommentReq
	AddSubjectCommentResp          = cmsclient.AddSubjectCommentResp
	DeleteSubjectCommentReq        = cmsclient.DeleteSubjectCommentReq
	DeleteSubjectCommentResp       = cmsclient.DeleteSubjectCommentResp
	QuerySubjectCommentDetailReq   = cmsclient.QuerySubjectCommentDetailReq
	QuerySubjectCommentDetailResp  = cmsclient.QuerySubjectCommentDetailResp
	QuerySubjectCommentListReq     = cmsclient.QuerySubjectCommentListReq
	QuerySubjectCommentListResp    = cmsclient.QuerySubjectCommentListResp
	SubjectCommentListData         = cmsclient.SubjectCommentListData
	UpdateSubjectCommentReq        = cmsclient.UpdateSubjectCommentReq
	UpdateSubjectCommentResp       = cmsclient.UpdateSubjectCommentResp
	UpdateSubjectCommentStatusReq  = cmsclient.UpdateSubjectCommentStatusReq
	UpdateSubjectCommentStatusResp = cmsclient.UpdateSubjectCommentStatusResp

	SubjectCommentService interface {
		// 添加专题评论
		AddSubjectComment(ctx context.Context, in *AddSubjectCommentReq, opts ...grpc.CallOption) (*AddSubjectCommentResp, error)
		// 删除专题评论
		DeleteSubjectComment(ctx context.Context, in *DeleteSubjectCommentReq, opts ...grpc.CallOption) (*DeleteSubjectCommentResp, error)
		// 更新专题评论
		UpdateSubjectComment(ctx context.Context, in *UpdateSubjectCommentReq, opts ...grpc.CallOption) (*UpdateSubjectCommentResp, error)
		// 更新专题评论状态
		UpdateSubjectCommentStatus(ctx context.Context, in *UpdateSubjectCommentStatusReq, opts ...grpc.CallOption) (*UpdateSubjectCommentStatusResp, error)
		// 查询专题评论详情
		QuerySubjectCommentDetail(ctx context.Context, in *QuerySubjectCommentDetailReq, opts ...grpc.CallOption) (*QuerySubjectCommentDetailResp, error)
		// 查询专题评论列表
		QuerySubjectCommentList(ctx context.Context, in *QuerySubjectCommentListReq, opts ...grpc.CallOption) (*QuerySubjectCommentListResp, error)
	}

	defaultSubjectCommentService struct {
		cli zrpc.Client
	}
)

func NewSubjectCommentService(cli zrpc.Client) SubjectCommentService {
	return &defaultSubjectCommentService{
		cli: cli,
	}
}

// 添加专题评论
func (m *defaultSubjectCommentService) AddSubjectComment(ctx context.Context, in *AddSubjectCommentReq, opts ...grpc.CallOption) (*AddSubjectCommentResp, error) {
	client := cmsclient.NewSubjectCommentServiceClient(m.cli.Conn())
	return client.AddSubjectComment(ctx, in, opts...)
}

// 删除专题评论
func (m *defaultSubjectCommentService) DeleteSubjectComment(ctx context.Context, in *DeleteSubjectCommentReq, opts ...grpc.CallOption) (*DeleteSubjectCommentResp, error) {
	client := cmsclient.NewSubjectCommentServiceClient(m.cli.Conn())
	return client.DeleteSubjectComment(ctx, in, opts...)
}

// 更新专题评论
func (m *defaultSubjectCommentService) UpdateSubjectComment(ctx context.Context, in *UpdateSubjectCommentReq, opts ...grpc.CallOption) (*UpdateSubjectCommentResp, error) {
	client := cmsclient.NewSubjectCommentServiceClient(m.cli.Conn())
	return client.UpdateSubjectComment(ctx, in, opts...)
}

// 更新专题评论状态
func (m *defaultSubjectCommentService) UpdateSubjectCommentStatus(ctx context.Context, in *UpdateSubjectCommentStatusReq, opts ...grpc.CallOption) (*UpdateSubjectCommentStatusResp, error) {
	client := cmsclient.NewSubjectCommentServiceClient(m.cli.Conn())
	return client.UpdateSubjectCommentStatus(ctx, in, opts...)
}

// 查询专题评论详情
func (m *defaultSubjectCommentService) QuerySubjectCommentDetail(ctx context.Context, in *QuerySubjectCommentDetailReq, opts ...grpc.CallOption) (*QuerySubjectCommentDetailResp, error) {
	client := cmsclient.NewSubjectCommentServiceClient(m.cli.Conn())
	return client.QuerySubjectCommentDetail(ctx, in, opts...)
}

// 查询专题评论列表
func (m *defaultSubjectCommentService) QuerySubjectCommentList(ctx context.Context, in *QuerySubjectCommentListReq, opts ...grpc.CallOption) (*QuerySubjectCommentListResp, error) {
	client := cmsclient.NewSubjectCommentServiceClient(m.cli.Conn())
	return client.QuerySubjectCommentList(ctx, in, opts...)
}
