###用户登录
POST {{host}}/api/sys/user/login
Content-Type: application/json

{
  "userName": "admin",
  "password": "123456"
}
> {%
    client.global.set("token", response.body.token);
%}


### 删除订单退货申请
GET {{host}}/api/order/returnapply/deleteReturnApply?ids=[]
Authorization: Bearer {{token}}


### 修改订单退货申请
POST {{host}}/api/order/returnapply/updateReturnApply
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id": 0,
  "companyAddressId": 0,
  "returnAmount": 666,
  "handleNote": "str",
  "receiveNote": "str",
  "status": 0
}


### 查询订单退货申请列表
GET {{host}}/api/order/returnapply/queryReturnApplyList
Authorization: Bearer {{token}}
