// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: cms.proto

package subjectcategoryservice

import (
	"context"

	"github.com/feihua/zero-admin/rpc/cms/cmsclient"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddSubjectCategoryReq           = cmsclient.AddSubjectCategoryReq
	AddSubjectCategoryResp          = cmsclient.AddSubjectCategoryResp
	DeleteSubjectCategoryReq        = cmsclient.DeleteSubjectCategoryReq
	DeleteSubjectCategoryResp       = cmsclient.DeleteSubjectCategoryResp
	QuerySubjectCategoryDetailReq   = cmsclient.QuerySubjectCategoryDetailReq
	QuerySubjectCategoryDetailResp  = cmsclient.QuerySubjectCategoryDetailResp
	QuerySubjectCategoryListReq     = cmsclient.QuerySubjectCategoryListReq
	QuerySubjectCategoryListResp    = cmsclient.QuerySubjectCategoryListResp
	SubjectCategoryListData         = cmsclient.SubjectCategoryListData
	UpdateSubjectCategoryReq        = cmsclient.UpdateSubjectCategoryReq
	UpdateSubjectCategoryResp       = cmsclient.UpdateSubjectCategoryResp
	UpdateSubjectCategoryStatusReq  = cmsclient.UpdateSubjectCategoryStatusReq
	UpdateSubjectCategoryStatusResp = cmsclient.UpdateSubjectCategoryStatusResp

	SubjectCategoryService interface {
		// 添加专题分类
		AddSubjectCategory(ctx context.Context, in *AddSubjectCategoryReq, opts ...grpc.CallOption) (*AddSubjectCategoryResp, error)
		// 删除专题分类
		DeleteSubjectCategory(ctx context.Context, in *DeleteSubjectCategoryReq, opts ...grpc.CallOption) (*DeleteSubjectCategoryResp, error)
		// 更新专题分类
		UpdateSubjectCategory(ctx context.Context, in *UpdateSubjectCategoryReq, opts ...grpc.CallOption) (*UpdateSubjectCategoryResp, error)
		// 更新专题分类状态
		UpdateSubjectCategoryStatus(ctx context.Context, in *UpdateSubjectCategoryStatusReq, opts ...grpc.CallOption) (*UpdateSubjectCategoryStatusResp, error)
		// 查询专题分类详情
		QuerySubjectCategoryDetail(ctx context.Context, in *QuerySubjectCategoryDetailReq, opts ...grpc.CallOption) (*QuerySubjectCategoryDetailResp, error)
		// 查询专题分类列表
		QuerySubjectCategoryList(ctx context.Context, in *QuerySubjectCategoryListReq, opts ...grpc.CallOption) (*QuerySubjectCategoryListResp, error)
	}

	defaultSubjectCategoryService struct {
		cli zrpc.Client
	}
)

func NewSubjectCategoryService(cli zrpc.Client) SubjectCategoryService {
	return &defaultSubjectCategoryService{
		cli: cli,
	}
}

// 添加专题分类
func (m *defaultSubjectCategoryService) AddSubjectCategory(ctx context.Context, in *AddSubjectCategoryReq, opts ...grpc.CallOption) (*AddSubjectCategoryResp, error) {
	client := cmsclient.NewSubjectCategoryServiceClient(m.cli.Conn())
	return client.AddSubjectCategory(ctx, in, opts...)
}

// 删除专题分类
func (m *defaultSubjectCategoryService) DeleteSubjectCategory(ctx context.Context, in *DeleteSubjectCategoryReq, opts ...grpc.CallOption) (*DeleteSubjectCategoryResp, error) {
	client := cmsclient.NewSubjectCategoryServiceClient(m.cli.Conn())
	return client.DeleteSubjectCategory(ctx, in, opts...)
}

// 更新专题分类
func (m *defaultSubjectCategoryService) UpdateSubjectCategory(ctx context.Context, in *UpdateSubjectCategoryReq, opts ...grpc.CallOption) (*UpdateSubjectCategoryResp, error) {
	client := cmsclient.NewSubjectCategoryServiceClient(m.cli.Conn())
	return client.UpdateSubjectCategory(ctx, in, opts...)
}

// 更新专题分类状态
func (m *defaultSubjectCategoryService) UpdateSubjectCategoryStatus(ctx context.Context, in *UpdateSubjectCategoryStatusReq, opts ...grpc.CallOption) (*UpdateSubjectCategoryStatusResp, error) {
	client := cmsclient.NewSubjectCategoryServiceClient(m.cli.Conn())
	return client.UpdateSubjectCategoryStatus(ctx, in, opts...)
}

// 查询专题分类详情
func (m *defaultSubjectCategoryService) QuerySubjectCategoryDetail(ctx context.Context, in *QuerySubjectCategoryDetailReq, opts ...grpc.CallOption) (*QuerySubjectCategoryDetailResp, error) {
	client := cmsclient.NewSubjectCategoryServiceClient(m.cli.Conn())
	return client.QuerySubjectCategoryDetail(ctx, in, opts...)
}

// 查询专题分类列表
func (m *defaultSubjectCategoryService) QuerySubjectCategoryList(ctx context.Context, in *QuerySubjectCategoryListReq, opts ...grpc.CallOption) (*QuerySubjectCategoryListResp, error) {
	client := cmsclient.NewSubjectCategoryServiceClient(m.cli.Conn())
	return client.QuerySubjectCategoryList(ctx, in, opts...)
}
