###用户登录
POST {{host}}/api/sys/user/login
Content-Type: application/json

{
  "userName": "admin",
  "password": "123456"
}
> {%
    client.global.set("token", response.body.token);
%}

### 添加商品品牌
POST {{host}}/api/product/brand/addProductBrand
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "test",
  "firstLetter": "N",
  "sort": 0,
  "factoryStatus": 1,
  "showStatus": 1,
  "productCount": 33,
  "productCommentCount": 100,
  "logo": "http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20180615/timg (51).jpg",
  "bigPic": "",
  "brandStory": "NIKE的故事"
}
### 删除商品品牌
GET {{host}}/api/product/brand/deleteCompanyAddress?ids=[]
Authorization: Bearer {{token}}


### 修改商品品牌
POST {{host}}/api/product/brand/updateProductBrand
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id": 59,
  "name": "test123",
  "firstLetter": "N",
  "sort": 0,
  "factoryStatus": 1,
  "showStatus": 1,
  "productCount": 0,
  "productCommentCount": 0,
  "logo": "http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20180615/timg (51).jpg",
  "bigPic": "",
  "brandStory": "NIKE的故事"
}

### 批量更新显示状态
POST {{host}}/api/product/brand/updateBrandShowStatus
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "ids": [58,59],
  "status": 0
}

### 批量更新厂家制造商状态
POST {{host}}/api/product/brand/updateBrandFactoryStatus
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "ids": [58,59],
  "status": 0
}

### 查询商品品牌列表
GET {{host}}/api/product/brand/queryProductBrandList
Authorization: Bearer {{token}}
