create table sys_menu
(
    id             bigint auto_increment comment '编号'
        primary key,
    name           varchar(50)                         not null comment '菜单名称',
    parent_id      bigint                              not null comment '父菜单ID，一级菜单为0',
    url            varchar(200)                        null,
    perms          varchar(500)                        null comment '授权(多个用逗号分隔，如：sys:user:add,sys:user:edit)',
    type           int                                 not null comment '类型   0：目录   1：菜单   2：按钮',
    icon           varchar(50)                         null comment '菜单图标',
    order_num      int                                 null comment '排序',
    create_by      varchar(50)                         not null comment '创建人',
    create_time    timestamp default CURRENT_TIMESTAMP null comment '创建时间',
    update_by      varchar(50)                         null comment '更新人',
    update_time datetime  default CURRENT_TIMESTAMP null on update CURRENT_TIMESTAMP comment '更新时间',
    del_flag       tinyint   default 0                 not null comment '是否删除  -1：已删除  0：正常',
    vue_path       varchar(64)                         null comment 'vue系统的path',
    vue_component  varchar(64)                         null comment 'vue的页面',
    vue_icon       varchar(64)                         null comment 'vue的图标',
    vue_redirect   varchar(64)                         null comment 'vue的路由重定向',
    background_url varchar(128)                        not null comment '后台地址'
)
    comment '菜单管理';

INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (1, '欢迎', 0, '/welcome', '', 0, 'SmileOutlined', 1, 'liufeihua', '2021-02-26 14:45:04', 'liufeihua', '2021-02-26 14:45:04', 0, '', '', '', '', '');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (2, '系统管理', 0, '/system', '', 0, 'SettingOutlined', 2, 'liufeihua', '2021-02-26 14:45:04', 'liufeihua', '2021-02-26 14:45:04', 0, '/sys', 'Layout', 'el-icon-setting', '/sys/userList', '');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (3, '用户列表', 2, '/system/user/list', '', 1, '', 1, 'liufeihua', '2021-02-26 14:45:04', 'liufeihua', '2021-02-26 14:45:04', 0, 'userList', 'system/user/index', 'el-icon-user', '', '/api/sys/user/list');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (4, '角色列表', 2, '/system/role/list', '', 1, '', 2, 'liufeihua', '2021-02-26 14:45:04', 'liufeihua', '2021-02-26 14:45:04', 1, 'roleList', 'system/role/index', 'el-icon-female', '', '/api/sys/role/list');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (5, '菜单列表', 2, '/system/menu/list', '', 1, '', 3, 'liufeihua', '2021-02-26 14:45:04', 'liufeihua', '2021-02-26 14:45:04', 1, 'resourcesList', 'system/resource/index', 'el-icon-postcard', '', '/api/sys/menu/list');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (6, '机构列表', 2, '/system/dept/list', '', 1, '', 4, 'liufeihua', '2021-02-26 14:45:04', 'liufeihua', '2021-02-26 14:45:04', 1, 'deptList', 'system/dept/index', 'el-icon-bangzhu', '', '/api/sys/dept/list');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (7, '字典列表', 2, '/system/dict/list', '', 1, '', 5, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 1, 'dictList', 'system/dict/index', 'el-icon-delete-location', '', '/api/sys/dict/list');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (8, '日志管理', 0, '/log', '', 0, 'DeleteOutlined', 3, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 1, '/log', 'Layout', 'el-icon-delete', '/log/loginLogList', '');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (9, '登录日志', 8, '/log/loginLog/list', '', 1, '', 3, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 1, 'loginLogList', 'log/loginlog/index', 'el-icon-remove-outline', '', '/api/sys/loginLog/list');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (10, '操作日志', 8, '/log/sysLog/list', '', 1, '', 3, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 1, 'sysLogList', 'log/syslog/index', 'el-icon-camera', '', '/api/sys/sysLog/list');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (11, '会员管理', 0, '/ums', '', 0, 'FrownOutlined', 3, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 1, '/ums', 'Layout', 'el-icon-headset', '/ums/memberList', '');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (12, '会员列表', 11, '/ums/member/list', '', 1, '', 3, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 1, 'memberList', 'ums/member/index', 'el-icon-camera', '', '/api/member/member/list');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (13, '会员等级', 11, '/ums/memberLevel/list', '', 1, '', 3, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 1, 'memberLevelList', 'ums/member_level/index', 'el-icon-remove-outline', '', '/api/member/level/list');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (14, '会员地址', 11, '/ums/memberAddress/list', '', 1, '', 3, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 1, 'memberAddressList', 'ums/member_address/index', 'el-icon-remove-outline', '', '/api/member/address/list');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (15, '登录记录', 11, '/ums/memberLoginLog/list', '', 1, '', 3, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 1, 'memberLoginLogList', 'ums/member_login_log/index', 'el-icon-remove-outline', '', '/api/member/loginlog/list');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (16, '商品管理', 0, '/pms', '', 0, 'GiftOutlined', 3, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 1, '/pms', 'Layout', 'el-icon-coffee', '/pms/productList', '');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (17, '商品分类', 16, '/pms/productCategory/list', '', 1, '', 3, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 1, 'productCategoryList', 'pms/product_category/index', 'el-icon-remove-outline', '', '/api/product/category/list');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (18, '商品品牌', 16, '/pms/productBrand/list', '', 1, '', 3, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 1, 'productBrandList', 'pms/product_brand/index', 'el-icon-remove-outline', '', '/api/product/brand/list');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (19, '商品列表', 16, '/pms/product/list', '', 1, '', 3, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 1, 'productList', 'pms/product/index', 'el-icon-camera', '', '/api/product/product/list');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (20, '订单管理', 0, '/oms', '', 0, 'DollarCircleOutlined', 3, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 1, '/oms', 'Layout', 'el-icon-shopping-cart-full', '/oms/orderList', '');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (21, '订单设置', 20, '/oms/orderSetting/list', '', 1, '', 3, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 1, 'orderSetting', 'oms/order_setting/index', 'el-icon-remove-outline', '', '/api/order/setting/list');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (22, '退货列表', 20, '/oms/orderReturnApply/list', '', 1, '', 3, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 1, 'orderReturnApplyList', 'oms/order_return_apply/index', 'el-icon-remove-outline', '', '/api/order/returnapply/list');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (23, '退货原因', 20, '/oms/orderReturnReason/list', '', 1, '', 3, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 1, 'orderReturnReasonList', 'oms/order_return_reason/index', 'el-icon-remove-outline', '', '/api/order/returnreason/list');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (24, '订单列表', 20, '/oms/order/list', '', 1, '', 3, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 1, 'orderList', 'oms/order/index', 'el-icon-camera', '', '/api/order/order/list');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (25, '营销管理', 0, '/sms', '', 0, 'AlertOutlined', 3, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 1, '/sms', 'Layout', 'el-icon-cold-drink', '/sms/flashPromotionList', '');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (26, '秒杀活动', 25, '/sms/flashPromotion/list', '', 1, '', 3, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 1, 'flashPromotionList', 'sms/flash_promotion/index', 'el-icon-camera', '', '/api/sms/flashpromotion/list');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (27, '品牌推荐', 25, '/sms/homeBrand/list', '', 1, '', 3, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 1, 'homeBrandList', 'sms/home_brand/index', 'el-icon-remove-outline', '', '/api/sms/homebrand/list');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (28, '新品推荐', 25, '/sms/homeNewProduct/list', '', 1, '', 3, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 1, 'homeNewProductList', 'sms/home_new_product/index', 'el-icon-remove-outline', '', '/api/sms/homenewproduct/list');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (29, '人气推荐', 25, '/sms/homeRecommendProduct/list', '', 1, '', 3, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 1, 'homeRecommendProductList', 'sms/home_recommend_product/index', 'el-icon-remove-outline', '', '/api/sms/homerecommendproduct/list');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (30, '专题推荐', 25, '/sms/homeRecommendSubject/list', '', 1, '', 3, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 1, 'homeRecommendSubjectList', 'sms/home_recommend_subject/index', 'el-icon-remove-outline', '', '/api/sms/homerecommendsubject/list');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (31, '广告列表', 25, '/sms/homeAdvertise/list', '', 1, '', 3, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 1, 'homeAdvertiseList', 'sms/home_advertise/index', 'el-icon-remove-outline', '', '/api/sms/homeadvertise/list');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (32, '优惠券', 25, '/sms/coupon/list', '', 1, '', 3, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 1, 'couponList', 'sms/coupon/index', 'el-icon-remove-outline', '', '/api/sms/coupon/list');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (33, '职位列表', 2, '/system/job/list', '', 1, '', 6, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 1, 'jobList', 'system/job/index', 'el-icon-delete-location', '', '/api/sys/job/list');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (34, '新增用户', 3, '', '', 2, '', 1, 'liufeihua', '2021-02-26 14:45:04', 'liufeihua', '2021-02-26 14:45:04', 0, '', '', '', '', '/api/sys/user/add');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (35, '更新用户', 3, '', '', 2, '', 2, 'liufeihua', '2021-02-26 14:45:04', 'liufeihua', '2021-02-26 14:45:04', 0, '', '', '', '', '/api/sys/user/update');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (36, '删除用户', 3, '', '', 2, '', 3, 'liufeihua', '2021-02-26 14:45:04', 'liufeihua', '2021-02-26 14:45:04', 0, '', '', '', '', '/api/sys/user/delete');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (119, '上传文件', 3, '', '', 2, '', 4, 'liufeihua', '2021-02-26 14:45:04', 'liufeihua', '2021-02-26 14:45:04', 0, '', '', '', '', '/api/sys/upload');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (37, '新增角色', 4, '', '', 2, '', 1, 'liufeihua', '2021-02-26 14:45:04', 'liufeihua', '2021-02-26 14:45:04', 0, '', '', '', '', '/api/sys/role/add');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (38, '更新角色', 4, '', '', 2, '', 2, 'liufeihua', '2021-02-26 14:45:04', 'liufeihua', '2021-02-26 14:45:04', 0, '', '', '', '', '/api/sys/role/update');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (39, '删除角色', 4, '', '', 2, '', 3, 'liufeihua', '2021-02-26 14:45:04', 'liufeihua', '2021-02-26 14:45:04', 0, '', '', '', '', '/api/sys/role/delete');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (40, '根据角色查询菜单', 4, '', '', 2, '', 4, 'liufeihua', '2021-02-26 14:45:04', 'liufeihua', '2021-02-26 14:45:04', 0, '', '', '', '', '/api/sys/role/queryMenuByRoleId');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (41, '根据角色更新菜单', 4, '', '', 2, '', 5, 'liufeihua', '2021-02-26 14:45:04', 'liufeihua', '2021-02-26 14:45:04', 0, '', '', '', '', '/api/sys/role/updateRoleMenu');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (42, '新增菜单', 5, '', '', 2, '', 1, 'liufeihua', '2021-02-26 14:45:04', 'liufeihua', '2021-02-26 14:45:04', 0, '', '', '', '', '/api/sys/menu/add');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (43, '更新菜单', 5, '', '', 2, '', 2, 'liufeihua', '2021-02-26 14:45:04', 'liufeihua', '2021-02-26 14:45:04', 0, '', '', '', '', '/api/sys/menu/update');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (44, '删除菜单', 5, '', '', 2, '', 3, 'liufeihua', '2021-02-26 14:45:04', 'liufeihua', '2021-02-26 14:45:04', 0, '', '', '', '', '/api/sys/menu/delete');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (45, '新增机构', 6, '', '', 2, '', 1, 'liufeihua', '2021-02-26 14:45:04', 'liufeihua', '2021-02-26 14:45:04', 0, '', '', '', '', '/api/sys/dept/add');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (46, '更新机构', 6, '', '', 2, '', 2, 'liufeihua', '2021-02-26 14:45:04', 'liufeihua', '2021-02-26 14:45:04', 0, '', '', '', '', '/api/sys/dept/update');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (47, '删除机构', 6, '', '', 2, '', 3, 'liufeihua', '2021-02-26 14:45:04', 'liufeihua', '2021-02-26 14:45:04', 0, '', '', '', '', '/api/sys/dept/delete');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (48, '新增字典', 7, '', '', 2, '', 1, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 0, '', '', '', '', '/api/sys/dict/add');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (49, '更新字典', 7, '', '', 2, '', 2, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 0, '', '', '', '', '/api/sys/dict/update');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (50, '删除字典', 7, '', '', 2, '', 3, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 0, '', '', '', '', '/api/sys/dict/delete');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (51, '登录日志', 9, '', '', 2, '', 1, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 0, '', '', '', '', '/api/sys/loginLog/delete');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (52, '操作日志', 10, '', '', 2, '', 1, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 0, '', '', '', '', '/api/sys/sysLog/delete');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (53, '新增会员', 12, '', '', 2, '', 1, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 0, '', '', '', '', '/api/member/member/add');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (54, '更新会员', 12, '', '', 2, '', 2, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 0, '', '', '', '', '/api/member/member/update');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (55, '删除会员', 12, '', '', 2, '', 3, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 0, '', '', '', '', '/api/member/member/delete');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (56, '新增会员等级', 13, '', '', 2, '', 1, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 0, '', '', '', '', '/api/member/level/add');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (57, '更新会员等级', 13, '', '', 2, '', 2, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 0, '', '', '', '', '/api/member/level/update');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (58, '删除会员等级', 13, '', '', 2, '', 3, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 0, '', '', '', '', '/api/member/level/delete');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (59, '新增会员地址', 14, '', '', 2, '', 1, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 0, '', '', '', '', '/api/member/address/add');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (60, '更新会员地址', 14, '', '', 2, '', 2, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 0, '', '', '', '', '/api/member/address/update');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (61, '删除会员地址', 14, '', '', 2, '', 3, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 0, '', '', '', '', '/api/member/address/delete');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (62, '删除登录记录', 15, '', '', 2, '', 3, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 0, '', '', '', '', '/api/member/loginlog/delete');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (63, '新增商品类别', 17, '', '', 2, '', 1, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 0, '', '', '', '', '/api/product/category/add');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (64, '更新商品类别', 17, '', '', 2, '', 2, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 0, '', '', '', '', '/api/product/category/update');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (65, '删除商品类别', 17, '', '', 2, '', 3, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 0, '', '', '', '', '/api/product/category/delete');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (66, '新增商品品牌', 18, '', '', 2, '', 1, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 0, '', '', '', '', '/api/product/brand/add');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (67, '更新商品品牌', 18, '', '', 2, '', 2, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 0, '', '', '', '', '/api/product/brand/update');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (68, '删除商品品牌', 18, '', '', 2, '', 3, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 0, '', '', '', '', '/api/product/brand/delete');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (69, '新增商品', 19, '', '', 2, '', 1, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 0, '', '', '', '', '/api/product/product/add');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (70, '更新商品', 19, '', '', 2, '', 2, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 0, '', '', '', '', '/api/product/product/update');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (71, '删除商品', 19, '', '', 2, '', 3, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 0, '', '', '', '', '/api/product/product/delete');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (118, '查询商品优选', 19, '', '', 2, '', 3, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 0, '', '', '', '', '/api/cms/prefrenceArea/list');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (72, '新增订单设置', 21, '', '', 2, '', 1, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 0, '', '', '', '', '/api/order/setting/add');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (73, '更新订单设置', 21, '', '', 2, '', 2, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 0, '', '', '', '', '/api/order/setting/update');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (74, '删除订单设置', 21, '', '', 2, '', 3, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 0, '', '', '', '', '/api/order/setting/delete');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (75, '新增退货', 22, '', '', 2, '', 1, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 0, '', '', '', '', '/api/order/returnapply/add');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (76, '更新退货', 22, '', '', 2, '', 2, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 0, '', '', '', '', '/api/order/returnapply/update');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (77, '删除退货', 22, '', '', 2, '', 3, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 0, '', '', '', '', '/api/order/returnapply/delete');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (117, '查询公司地址列表', 22, '', '', 2, '', 3, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 0, '', '', '', '', '/api/order/compayaddress/list');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (78, '新增退货原因', 23, '', '', 2, '', 1, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 0, '', '', '', '', '/api/order/returnreason/add');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (79, '更新退货原因', 23, '', '', 2, '', 2, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 0, '', '', '', '', '/api/order/returnreason/update');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (80, '删除退货原因', 23, '', '', 2, '', 3, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 0, '', '', '', '', '/api/order/returnreason/delete');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (81, '新增订单', 24, '', '', 2, '', 1, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 0, '', '', '', '', '/api/order/order/add');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (82, '更新订单', 24, '', '', 2, '', 2, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 0, '', '', '', '', '/api/order/order/update');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (83, '删除订单', 24, '', '', 2, '', 3, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 0, '', '', '', '', '/api/order/order/delete');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (84, '新增秒杀活动', 26, '', '', 2, '', 1, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 0, '', '', '', '', '/api/sms/flashpromotion/add');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (85, '更新秒杀活动', 26, '', '', 2, '', 2, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 0, '', '', '', '', '/api/sms/flashpromotion/update');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (86, '删除秒杀活动', 26, '', '', 2, '', 3, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 0, '', '', '', '', '/api/sms/flashpromotion/delete');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (87, '新增品牌推荐', 27, '', '', 2, '', 1, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 0, '', '', '', '', '/api/sms/homebrand/add');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (88, '更新品牌推荐', 27, '', '', 2, '', 2, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 0, '', '', '', '', '/api/sms/homebrand/update');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (89, '删除品牌推荐', 27, '', '', 2, '', 3, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 0, '', '', '', '', '/api/sms/homebrand/delete');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (90, '新增新品推荐', 28, '', '', 2, '', 1, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 0, '', '', '', '', '/api/sms/homenewproduct/add');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (91, '更新新品推荐', 28, '', '', 2, '', 2, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 0, '', '', '', '', '/api/sms/homenewproduct/update');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (92, '删除新品推荐', 28, '', '', 2, '', 3, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 0, '', '', '', '', '/api/sms/homenewproduct/delete');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (93, '新增人气推荐', 29, '', '', 2, '', 1, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 0, '', '', '', '', '/api/sms/homerecommendproduct/add');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (94, '更新人气推荐', 29, '', '', 2, '', 2, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 0, '', '', '', '', '/api/sms/homerecommendproduct/update');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (95, '删除人气推荐', 29, '', '', 2, '', 3, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 0, '', '', '', '', '/api/sms/homerecommendproduct/delete');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (96, '新增广告', 31, '', '', 2, '', 1, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 0, '', '', '', '', '/api/sms/homeadvertise/add');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (97, '更新广告', 31, '', '', 2, '', 2, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 0, '', '', '', '', '/api/sms/homeadvertise/update');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (98, '删除广告', 31, '', '', 2, '', 3, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 0, '', '', '', '', '/api/sms/homeadvertise/delete');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (99, '新增优惠券', 32, '', '', 2, '', 1, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 0, '', '', '', '', '/api/sms/coupon/add');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (100, '更新优惠券', 32, '', '', 2, '', 2, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 0, '', '', '', '', '/api/sms/coupon/update');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (101, '删除优惠券', 32, '', '', 2, '', 3, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 0, '', '', '', '', '/api/sms/coupon/delete');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (102, '新增职位', 33, '', '', 2, '', 1, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 0, '', '', '', '', '/api/sys/job/add');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (103, '更新职位', 33, '', '', 2, '', 2, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 0, '', '', '', '', '/api/sys/job/update');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (104, '删除职位', 33, '', '', 2, '', 3, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 0, '', '', '', '', '/api/sys/job/delete');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (105, '新增专题推荐', 30, '', '', 2, '', 1, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 0, '', '', '', '', '/api/sms/homerecommendsubject/add');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (106, '更新专题推荐', 30, '', '', 2, '', 2, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 0, '', '', '', '', '/api/sms/homerecommendsubject/update');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (107, '删除专题推荐', 30, '', '', 2, '', 3, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 0, '', '', '', '', '/api/sms/homerecommendsubject/delete');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (108, '专题列表', 30, '', '', 2, '', 3, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 0, '', '', '', '', '/api/cms/subject/list');

INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (113, '属性分类', 16, '/pms/attributecategory/list', '', 1, '', 3, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 1, '', '', '', '', '/api/product/attributecategory/list');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (114, '新增属性分类', 113, '', '', 2, '', 1, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 0, '', '', '', '', '/api/product/attributecategory/add');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (115, '更新属性分类', 113, '', '', 2, '', 2, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 0, '', '', '', '', '/api/product/attributecategory/update');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (116, '删除属性分类', 113, '', '', 2, '', 3, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 0, '', '', '', '', '/api/product/attributecategory/delete');

INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (109, '属性选项', 16, '/pms/attribute/list', '', 1, '', 3, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 1, '', '', '', '', '/api/product/attribute/list');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (110, '新增属性选项', 109, '', '', 2, '', 1, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 0, '', '', '', '', '/api/product/attribute/add');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (111, '更新属性选项', 109, '', '', 2, '', 2, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 0, '', '', '', '', '/api/product/attribute/update');
INSERT INTO sys_menu (id, name, parent_id, url, perms, type, icon, order_num, create_by, create_time, update_by, update_time, del_flag, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (112, '删除属性选项', 109, '', '', 2, '', 3, 'liufeihua', '2021-02-26 14:45:05', 'liufeihua', '2021-02-26 14:45:05', 0, '', '', '', '', '/api/product/attribute/delete');
