// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: pms.proto

package productoperatelogservice

import (
	"context"

	"github.com/feihua/zero-admin/rpc/pms/pmsclient"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddProductOperateLogReq          = pmsclient.AddProductOperateLogReq
	AddProductOperateLogResp         = pmsclient.AddProductOperateLogResp
	DeleteProductOperateLogReq       = pmsclient.DeleteProductOperateLogReq
	DeleteProductOperateLogResp      = pmsclient.DeleteProductOperateLogResp
	ProductOperateLogListData        = pmsclient.ProductOperateLogListData
	QueryProductOperateLogDetailReq  = pmsclient.QueryProductOperateLogDetailReq
	QueryProductOperateLogDetailResp = pmsclient.QueryProductOperateLogDetailResp
	QueryProductOperateLogListReq    = pmsclient.QueryProductOperateLogListReq
	QueryProductOperateLogListResp   = pmsclient.QueryProductOperateLogListResp

	ProductOperateLogService interface {
		// 添加商品操作日志
		AddProductOperateLog(ctx context.Context, in *AddProductOperateLogReq, opts ...grpc.CallOption) (*AddProductOperateLogResp, error)
		// 删除商品操作日志
		DeleteProductOperateLog(ctx context.Context, in *DeleteProductOperateLogReq, opts ...grpc.CallOption) (*DeleteProductOperateLogResp, error)
		// 查询商品操作日志详情
		QueryProductOperateLogDetail(ctx context.Context, in *QueryProductOperateLogDetailReq, opts ...grpc.CallOption) (*QueryProductOperateLogDetailResp, error)
		// 查询商品操作日志列表
		QueryProductOperateLogList(ctx context.Context, in *QueryProductOperateLogListReq, opts ...grpc.CallOption) (*QueryProductOperateLogListResp, error)
	}

	defaultProductOperateLogService struct {
		cli zrpc.Client
	}
)

func NewProductOperateLogService(cli zrpc.Client) ProductOperateLogService {
	return &defaultProductOperateLogService{
		cli: cli,
	}
}

// 添加商品操作日志
func (m *defaultProductOperateLogService) AddProductOperateLog(ctx context.Context, in *AddProductOperateLogReq, opts ...grpc.CallOption) (*AddProductOperateLogResp, error) {
	client := pmsclient.NewProductOperateLogServiceClient(m.cli.Conn())
	return client.AddProductOperateLog(ctx, in, opts...)
}

// 删除商品操作日志
func (m *defaultProductOperateLogService) DeleteProductOperateLog(ctx context.Context, in *DeleteProductOperateLogReq, opts ...grpc.CallOption) (*DeleteProductOperateLogResp, error) {
	client := pmsclient.NewProductOperateLogServiceClient(m.cli.Conn())
	return client.DeleteProductOperateLog(ctx, in, opts...)
}

// 查询商品操作日志详情
func (m *defaultProductOperateLogService) QueryProductOperateLogDetail(ctx context.Context, in *QueryProductOperateLogDetailReq, opts ...grpc.CallOption) (*QueryProductOperateLogDetailResp, error) {
	client := pmsclient.NewProductOperateLogServiceClient(m.cli.Conn())
	return client.QueryProductOperateLogDetail(ctx, in, opts...)
}

// 查询商品操作日志列表
func (m *defaultProductOperateLogService) QueryProductOperateLogList(ctx context.Context, in *QueryProductOperateLogListReq, opts ...grpc.CallOption) (*QueryProductOperateLogListResp, error) {
	client := pmsclient.NewProductOperateLogServiceClient(m.cli.Conn())
	return client.QueryProductOperateLogList(ctx, in, opts...)
}
