// Code generated by goctl. DO NOT EDIT.
package types

type AddMemberAddressReq struct {
	Name          string `json:"name"` // 收货人名称
	PhoneNumber   string `json:"phoneNumber"`
	DefaultStatus int64  `json:"defaultStatus"` // 是否为默认
	PostCode      string `json:"postCode"`      // 邮政编码
	Province      string `json:"province"`      // 省份/直辖市
	City          string `json:"city"`          // 城市
	Region        string `json:"region"`        // 区
	DetailAddress string `json:"detailAddress"` // 详细地址(街道)
}

type AddMemberAddressResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type ListMemberAddressData struct {
	Id            int64  `json:"id"`
	MemberId      int64  `json:"memberId"`
	Name          string `json:"name"` // 收货人名称
	PhoneNumber   string `json:"phoneNumber"`
	DefaultStatus int64  `json:"defaultStatus"` // 是否为默认
	PostCode      string `json:"postCode"`      // 邮政编码
	Province      string `json:"province"`      // 省份/直辖市
	City          string `json:"city"`          // 城市
	Region        string `json:"region"`        // 区
	DetailAddress string `json:"detailAddress"` // 详细地址(街道)
}

type ListMemberAddressResp struct {
	Data    []ListMemberAddressData `json:"data"`
	Success bool                    `json:"success"`
	Code    int64                   `json:"code"`
	Message string                  `json:"message"`
}

type UpdateMemberAddressReq struct {
	Id            int64  `json:"id"`
	Name          string `json:"name"` // 收货人名称
	PhoneNumber   string `json:"phoneNumber"`
	DefaultStatus int64  `json:"defaultStatus"` // 是否为默认
	PostCode      string `json:"postCode"`      // 邮政编码
	Province      string `json:"province"`      // 省份/直辖市
	City          string `json:"city"`          // 城市
	Region        string `json:"region"`        // 区
	DetailAddress string `json:"detailAddress"` // 详细地址(街道)
}

type UpdateMemberAddressResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type DeleteMemberAddressReq struct {
	Id int64 `path:"id"`
}

type DeleteMemberAddressResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type LoginReq struct {
	Username string `json:"username,optional"` //会员名称
	Password string `json:"password"`          //密码
	Mobile   string `json:"mobile,optional"`   //手机号码
}

type LoginResp struct {
	Code    int64     `json:"code"`
	Message string    `json:"message"`
	Data    LoginData `json:"data"`
}

type LoginData struct {
	Token     string `json:"token"`
	TokenHead string `json:"tokenHead"`
}

type RegisterReq struct {
	Username string `json:"username"` //会员名称
	Password string `json:"password"` //密码
	Mobile   string `json:"mobile"`   //手机号码
}

type RegisterResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
	Data    string `json:"data"` //token
}

type InfoResp struct {
	Code    int64      `json:"code"`
	Message string     `json:"message"`
	Data    MemberData `json:"data"`
}

type MemberData struct {
	Id                    int64  `json:"id"`
	MemberLevelId         int64  `json:"memberLevelId"`
	Username              string `json:"username"`              // 用户名
	Nickname              string `json:"nickname"`              // 昵称
	Phone                 string `json:"phone"`                 // 手机号码
	Status                int64  `json:"status"`                // 帐号启用状态:0->禁用；1->启用
	CreateTime            string `json:"createTime"`            // 注册时间
	Icon                  string `json:"icon"`                  // 头像
	Gender                int64  `json:"gender"`                // 性别：0->未知；1->男；2->女
	Birthday              string `json:"birthday"`              // 生日
	City                  string `json:"city"`                  // 所做城市
	Job                   string `json:"job"`                   // 职业
	PersonalizedSignature string `json:"personalizedSignature"` // 个性签名
	SourceType            int64  `json:"sourceType"`            // 用户来源
	Integration           int64  `json:"integration"`           // 积分
	Growth                int64  `json:"growth"`                // 成长值
	LuckeyCount           int64  `json:"luckeyCount"`           // 剩余抽奖次数
	HistoryIntegration    int64  `json:"historyIntegration"`    // 历史积分数量
	CouponCount           int64  `json:"couponCount"`           // 优惠券数量
}

type UpdatePasswordReq struct {
	Password string `json:"password"` //密码
}

type UpdatePasswordResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type UpdateMemberReq struct {
	Id                    int64  `json:"id"`
	MemberLevelId         int64  `json:"memberLevelId"`
	Username              string `json:"username"`              // 用户名
	Password              string `json:"password"`              // 密码
	Nickname              string `json:"nickname"`              // 昵称
	Phone                 string `json:"phone"`                 // 手机号码
	Status                int64  `json:"status"`                // 帐号启用状态:0->禁用；1->启用
	CreateTime            string `json:"createTime"`            // 注册时间
	Icon                  string `json:"icon"`                  // 头像
	Gender                int64  `json:"gender"`                // 性别：0->未知；1->男；2->女
	Birthday              string `json:"birthday"`              // 生日
	City                  string `json:"city"`                  // 所做城市
	Job                   string `json:"job"`                   // 职业
	PersonalizedSignature string `json:"personalizedSignature"` // 个性签名
	SourceType            int64  `json:"sourceType"`            // 用户来源
	Integration           int64  `json:"integration"`           // 积分
	Growth                int64  `json:"growth"`                // 成长值
	LuckeyCount           int64  `json:"luckeyCount"`           // 剩余抽奖次数
	HistoryIntegration    int64  `json:"historyIntegration"`    // 历史积分数量
}

type UpdateMemberResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type CartItemAddReq struct {
	ProductId         int64   `json:"productId"`
	ProductSkuId      int64   `json:"productSkuId"`
	Quantity          int64   `json:"quantity"`          // 购买数量
	Price             float64 `json:"price"`             // 添加到购物车的价格
	ProductPic        string  `json:"productPic"`        // 商品主图
	ProductName       string  `json:"productName"`       // 商品名称
	ProductSubTitle   string  `json:"productSubTitle"`   // 商品副标题（卖点）
	ProductSkuCode    string  `json:"productSkuCode"`    // 商品sku条码
	ProductCategoryId int64   `json:"productCategoryId"` // 商品分类
	ProductBrand      string  `json:"productBrand"`
	ProductSn         string  `json:"productSn"`
	ProductAttr       string  `json:"productAttr"` // 商品销售属性:[{"key":"颜色","value":"颜色"},{"key":"容量","value":"4G"}]
}

type CartItemAddResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type CartItemDeleteReq struct {
	Ids []int64 `json:"ids"`
}

type CartItemDeleteResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type CartItemUpdateQuantityReq struct {
	Id       int64 `json:"id"`
	Quantity int64 `json:"quantity"` // 购买数量
}

type CartItemUpdateAttrReq struct {
	Id                int64   `json:"id"`
	ProductId         int64   `json:"productId"`
	ProductSkuId      int64   `json:"productSkuId"`
	Quantity          int64   `json:"quantity"`          // 购买数量
	Price             float64 `json:"price"`             // 添加到购物车的价格
	ProductPic        string  `json:"productPic"`        // 商品主图
	ProductName       string  `json:"productName"`       // 商品名称
	ProductSubTitle   string  `json:"productSubTitle"`   // 商品副标题（卖点）
	ProductSkuCode    string  `json:"productSkuCode"`    // 商品sku条码
	DeleteStatus      int64   `json:"deleteStatus"`      // 是否删除
	ProductCategoryId int64   `json:"productCategoryId"` // 商品分类
	ProductBrand      string  `json:"productBrand"`
	ProductSn         string  `json:"productSn"`
	ProductAttr       string  `json:"productAttr"` // 商品销售属性:[{"key":"颜色","value":"颜色"},{"key":"容量","value":"4G"}]
}

type CartItemUpdateResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type CartItemListResp struct {
	Code    int64          `json:"code"`
	Message string         `json:"message"`
	Data    []CartListData `json:"data"`
}

type CartListData struct {
	Id                int64   `json:"id"`
	ProductId         int64   `json:"productId"`
	ProductSkuId      int64   `json:"productSkuId"`
	MemberId          int64   `json:"memberId"`
	Quantity          int64   `json:"quantity"`          // 购买数量
	Price             float32 `json:"price"`             // 添加到购物车的价格
	ProductPic        string  `json:"productPic"`        // 商品主图
	ProductName       string  `json:"productName"`       // 商品名称
	ProductSubTitle   string  `json:"productSubTitle"`   // 商品副标题（卖点）
	ProductSkuCode    string  `json:"productSkuCode"`    // 商品sku条码
	MemberNickname    string  `json:"memberNickname"`    // 会员昵称
	CreateDate        string  `json:"createDate"`        // 创建时间
	ModifyDate        string  `json:"modifyDate"`        // 修改时间
	DeleteStatus      int64   `json:"deleteStatus"`      // 是否删除
	ProductCategoryId int64   `json:"productCategoryId"` // 商品分类
	ProductBrand      string  `json:"productBrand"`
	ProductSn         string  `json:"productSn"`
	ProductAttr       string  `json:"productAttr"` // 商品销售属性:[{"key":"颜色","value":"颜色"},{"key":"容量","value":"4G"}]
}

type CarItemListPromotionReq struct {
	Ids []int64 `json:"ids,optional"`
}

type CarItemtListPromotionResp struct {
	Code    int64                       `json:"code"`
	Message string                      `json:"message"`
	Data    []CarItemtPromotionListData `json:"data"`
}

type CarItemtPromotionListData struct {
	Id                int64   `json:"id"`
	ProductId         int64   `json:"productId"`
	ProductSkuId      int64   `json:"productSkuId"`
	MemberId          int64   `json:"memberId"`
	Quantity          int64   `json:"quantity"`          // 购买数量
	Price             float32 `json:"price"`             // 添加到购物车的价格
	ProductPic        string  `json:"productPic"`        // 商品主图
	ProductName       string  `json:"productName"`       // 商品名称
	ProductSubTitle   string  `json:"productSubTitle"`   // 商品副标题（卖点）
	ProductSkuCode    string  `json:"productSkuCode"`    // 商品sku条码
	MemberNickname    string  `json:"memberNickname"`    // 会员昵称
	CreateDate        string  `json:"createDate"`        // 创建时间
	ModifyDate        string  `json:"modifyDate"`        // 修改时间
	DeleteStatus      int64   `json:"deleteStatus"`      // 是否删除
	ProductCategoryId int64   `json:"productCategoryId"` // 商品分类
	ProductBrand      string  `json:"productBrand"`
	ProductSn         string  `json:"productSn"`
	ProductAttr       string  `json:"productAttr"`      // 商品销售属性:[{"key":"颜色","value":"颜色"},{"key":"容量","value":"4G"}]
	PromotionMessage  string  `json:"promotionMessage"` //促销活动信息
	ReduceAmount      float32 `json:"reduceAmount"`     //促销活动减去的金额，针对每个商品
	RealStock         int64   `json:"realStock"`        //商品的真实库存（剩余库存-锁定库存）
	Integration       int64   `json:"integration"`      //购买商品赠送积分
	Growth            int64   `json:"growth"`           //购买商品赠送成长值
}

type CartProductReq struct {
	ProductId int64 `path:"productId"`
}

type CartProductResp struct {
	Code    int64           `json:"code"`
	Message string          `json:"message"`
	Data    CartProductData `json:"data"`
}

type CartProductData struct {
	ProductAttributeList []CartItemProductAttributeList `json:"productAttributeList"`
	SkuStockList         []CartItemSkuStockList         `json:"skuStockList"`
}

type CartItemProductAttributeList struct {
	Id                         int64  `json:"id"`
	ProductAttributeCategoryId int64  `json:"productAttributeCategoryId"`
	Name                       string `json:"name"`
	SelectType                 int64  `json:"selectType"`
	InputType                  int64  `json:"inputType"`
	InputList                  string `json:"inputList"`
	Sort                       int64  `json:"sort"`
	FilterType                 int64  `json:"filterType"`
	SearchType                 int64  `json:"searchType"`
	RelatedStatus              int64  `json:"relatedStatus"`
	HandAddStatus              int64  `json:"handAddStatus"`
	Type                       int64  `json:"type"`
}

type CartItemSkuStockList struct {
	Id             int64   `json:"id"`
	ProductId      int64   `json:"productId"`
	SkuCode        string  `json:"skuCode"` // sku编码
	Price          float32 `json:"price"`
	Stock          int64   `json:"stock"`          // 库存
	LowStock       int64   `json:"lowStock"`       // 预警库存
	Pic            string  `json:"pic"`            // 展示图片
	Sale           int64   `json:"sale"`           // 销量
	PromotionPrice float32 `json:"promotionPrice"` // 单品促销价格
	LockStock      int64   `json:"lockStock"`      // 锁定库存
	SpData         string  `json:"spData"`         // 商品销售属性，json格式
}

type CartItemClearResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type CategoryReq struct {
	ParentId int64 `path:"parentId"` // 上级分类的编号：0表示一级分类
}

type CategoryResp struct {
	Code    int64          `json:"code"`
	Message string         `json:"message"`
	Data    []CategoryData `json:"data"`
}

type CategoryData struct {
	Id           int64  `json:"id"`
	ParentId     int64  `json:"parentId"` // 上级分类的编号：0表示一级分类
	Name         string `json:"name"`
	Level        int64  `json:"level"` // 分类级别：0->1级；1->2级
	ProductCount int64  `json:"productCount"`
	ProductUnit  string `json:"productUnit"`
	NavStatus    int64  `json:"navStatus"`  // 是否显示在导航栏：0->不显示；1->显示
	ShowStatus   int64  `json:"showStatus"` // 显示状态：0->不显示；1->显示
	Sort         int64  `json:"sort"`
	Icon         string `json:"icon"` // 图标
	Keywords     string `json:"keywords"`
	Description  string `json:"description"` // 描述
}

type HomeResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
	Data    Data   `json:"data"`
}

type Data struct {
	AdvertiseList      []AdvertiseList    `json:"advertiseList"`      //获取首页广告
	BrandList          []BrandList        `json:"brandList"`          //获取推荐品牌
	HomeFlashPromotion HomeFlashPromotion `json:"homeFlashPromotion"` //获取秒杀信息
	NewProductList     []ProductList      `json:"newProductList"`     //获取新品推荐
	HotProductList     []ProductList      `json:"hotProductList"`     //获取人气推荐
	SubjectList        []SubjectList      `json:"subjectList"`        //获取推荐专题
}

type SubjectList struct {
	CategoryId      int64  `json:"categoryId"`
	Title           string `json:"title"`
	Pic             string `json:"pic"`          // 专题主图
	ProductCount    int64  `json:"productCount"` // 关联产品数量
	RecommendStatus int64  `json:"recommendStatus"`
	CollectCount    int64  `json:"collectCount"`
	ReadCount       int64  `json:"readCount"`
	CommentCount    int64  `json:"commentCount"`
	AlbumPics       string `json:"albumPics"` // 画册图片用逗号分割
	Description     string `json:"description"`
	ShowStatus      int64  `json:"showStatus"` // 显示状态：0->不显示；1->显示
	Content         string `json:"content"`
	ForwardCount    int64  `json:"forwardCount"` // 转发数
	CategoryName    string `json:"categoryName"` // 专题分类名称
}

type AdvertiseList struct {
	ID         int64  `json:"id"`
	Name       string `json:"name"`
	Type       int64  `json:"type"`
	Pic        string `json:"pic"`
	StartTime  string `json:"startTime"`
	EndTime    string `json:"endTime"`
	Status     int64  `json:"status"`
	ClickCount int64  `json:"clickCount"`
	OrderCount int64  `json:"orderCount"`
	URL        string `json:"url"`
	Sort       int64  `json:"sort"`
}

type BrandList struct {
	ID                  int64  `json:"id"`
	Name                string `json:"name"`
	FirstLetter         string `json:"firstLetter"`
	Sort                int64  `json:"sort"`
	FactoryStatus       int64  `json:"factoryStatus"`
	ShowStatus          int64  `json:"showStatus"`
	ProductCount        int64  `json:"productCount"`
	ProductCommentCount int64  `json:"productCommentCount"`
	Logo                string `json:"logo"`
	BigPic              string `json:"bigPic"`
}

type HomeFlashPromotion struct {
	StartTime     string        `json:"startTime"`
	EndTime       string        `json:"endTime"`
	NextStartTime string        `json:"nextStartTime"`
	NextEndTime   string        `json:"nextEndTime"`
	ProductList   []ProductList `json:"productList"`
}

type ProductList struct {
	Id                         int64   `json:"id"`
	BrandId                    int64   `json:"brandId"`
	ProductCategoryId          int64   `json:"productCategoryId"`
	FeightTemplateId           int64   `json:"feightTemplateId"`
	ProductAttributeCategoryId int64   `json:"productAttributeCategoryId"`
	Name                       string  `json:"name"`
	Pic                        string  `json:"pic"`
	ProductSn                  string  `json:"productSn"`
	DeleteStatus               int64   `json:"deleteStatus"`
	PublishStatus              int64   `json:"publishStatus"`
	NewStatus                  int64   `json:"newStatus"`
	RecommandStatus            int64   `json:"recommandStatus"`
	VerifyStatus               int64   `json:"verifyStatus"`
	Sort                       int64   `json:"sort"`
	Sale                       int64   `json:"sale"`
	Price                      float64 `json:"price"`
	PromotionPrice             float64 `json:"promotionPrice,omitempty"`
	GiftGrowth                 int64   `json:"giftGrowth"`
	GiftPoint                  int64   `json:"giftPoint"`
	UsePointLimit              int64   `json:"usePointLimit"`
	SubTitle                   string  `json:"subTitle"`
	OriginalPrice              float64 `json:"originalPrice"`
	Stock                      int64   `json:"stock"`
	LowStock                   int64   `json:"lowStock"`
	Unit                       string  `json:"unit"`
	Weight                     float64 `json:"weight"`
	PreviewStatus              int64   `json:"previewStatus"`
	ServiceIDS                 string  `json:"serviceIds"`
	Keywords                   string  `json:"keywords"`
	Note                       string  `json:"note"`
	AlbumPics                  string  `json:"albumPics"`
	DetailTitle                string  `json:"detailTitle"`
	PromotionStartTime         string  `json:"promotionStartTime,omitempty"`
	PromotionEndTime           string  `json:"promotionEndTime,omitempty"`
	PromotionPerLimit          int64   `json:"promotionPerLimit"`
	PromotionType              int64   `json:"promotionType"`
	BrandName                  string  `json:"brandName"`
	ProductCategoryName        string  `json:"productCategoryName"`
	Description                string  `json:"description"`
}

type RecommendProductListReq struct {
	Current  int64 `json:"current,default=1"`
	PageSize int64 `json:"pageSize,default=10"`
}

type RecommendProductListResp struct {
	Code    int64         `json:"code"`
	Message string        `json:"message"`
	Data    []ProductList `json:"data"`
}

type RecommendBrandListReq struct {
	Current  int64 `json:"current,default=1"`
	PageSize int64 `json:"pageSize,default=10"`
}

type RecommendBrandListResp struct {
	Code    int64       `json:"code"`
	Message string      `json:"message"`
	Data    []BrandList `json:"data"`
}

type RecommendNewProductListReq struct {
	Current  int64 `json:"current,default=1"`
	PageSize int64 `json:"pageSize,default=10"`
}

type RecommendNewProductListResp struct {
	Code    int64         `json:"code"`
	Message string        `json:"message"`
	Data    []ProductList `json:"data"`
}

type RecommendHotProductListReq struct {
	Current  int64 `json:"current,default=1"`
	PageSize int64 `json:"pageSize,default=10"`
}

type RecommendHotProductListResp struct {
	Code    int64         `json:"code"`
	Message string        `json:"message"`
	Data    []ProductList `json:"data"`
}

type GenerateConfirmOrderReq struct {
	Ids []int64 `json:"ids,optional"`
}

type GenerateConfirmOrderResp struct {
	Code    int64            `json:"code"`
	Message string           `json:"message"`
	Data    OrderDetailModel `json:"data"`
}

type OrderDetailModel struct {
	CartPromotionItemList     []CartPromotionItemList    `json:"cartPromotionItemList"`
	MemberReceiveAddressList  []MemberReceiveAddressList `json:"memberReceiveAddressList"`
	CouponHistoryDetailList   interface{}                `json:"couponHistoryDetailList"`
	IntegrationConsumeSetting IntegrationConsumeSetting  `json:"integrationConsumeSetting"`
	MemberIntegration         int64                      `json:"memberIntegration"`
	CalcAmount                CalcAmount                 `json:"calcAmount"`
}

type CalcAmount struct {
	TotalAmount     float32 `json:"totalAmount"`
	FreightAmount   float32 `json:"freightAmount"`
	PromotionAmount float32 `json:"promotionAmount"`
	PayAmount       float32 `json:"payAmount"`
}

type CartPromotionItemList struct {
	Id                int64   `json:"id"`
	ProductId         int64   `json:"productId"`
	ProductSkuId      int64   `json:"productSkuId"`
	MemberId          int64   `json:"memberId"`
	Quantity          int64   `json:"quantity"`          // 购买数量
	Price             float32 `json:"price"`             // 添加到购物车的价格
	ProductPic        string  `json:"productPic"`        // 商品主图
	ProductName       string  `json:"productName"`       // 商品名称
	ProductSubTitle   string  `json:"productSubTitle"`   // 商品副标题（卖点）
	ProductSkuCode    string  `json:"productSkuCode"`    // 商品sku条码
	MemberNickname    string  `json:"memberNickname"`    // 会员昵称
	CreateDate        string  `json:"createDate"`        // 创建时间
	ModifyDate        string  `json:"modifyDate"`        // 修改时间
	DeleteStatus      int64   `json:"deleteStatus"`      // 是否删除
	ProductCategoryId int64   `json:"productCategoryId"` // 商品分类
	ProductBrand      string  `json:"productBrand"`
	ProductSn         string  `json:"productSn"`
	ProductAttr       string  `json:"productAttr"`      // 商品销售属性:[{"key":"颜色","value":"颜色"},{"key":"容量","value":"4G"}]
	PromotionMessage  string  `json:"promotionMessage"` //促销活动信息
	ReduceAmount      float32 `json:"reduceAmount"`     //促销活动减去的金额，针对每个商品
	RealStock         int64   `json:"realStock"`        //商品的真实库存（剩余库存-锁定库存）
	Integration       int64   `json:"integration"`      //购买商品赠送积分
	Growth            int64   `json:"growth"`           //购买商品赠送成长值
}

type IntegrationConsumeSetting struct {
	Id                 int64 `json:"id"`
	DeductionPerAmount int64 `json:"deductionPerAmount"`
	MaxPercentPerOrder int64 `json:"maxPercentPerOrder"`
	UseUnit            int64 `json:"useUnit"`
	CouponStatus       int64 `json:"couponStatus"`
}

type MemberReceiveAddressList struct {
	Id            int64  `json:"id"`
	MemberId      int64  `json:"memberId"`
	Name          string `json:"name"`
	PhoneNumber   string `json:"phoneNumber"`
	DefaultStatus int64  `json:"defaultStatus"`
	PostCode      string `json:"postCode"`
	Province      string `json:"province"`
	City          string `json:"city"`
	Region        string `json:"region"`
	DetailAddress string `json:"detailAddress"`
}

type GenerateOrderReq struct {
	CartIds                []int64 `json:"cartIds"`                //购物车id
	CouponId               int64   `json:"couponId"`               //优惠券id
	MemberReceiveAddressId int64   `json:"memberReceiveAddressId"` //
	PayType                int64   `json:"payType"`                //支付方式
	UseIntegration         int64   `json:"useIntegration"`         //使用的积分
}

type GenerateOrderResp struct {
	Code    int64             `json:"code"`
	Message string            `json:"message"`
	Data    GenerateOrderData `json:"data"`
}

type GenerateOrderData struct {
	Id                int64   `json:"id"`                // 订单id
	MemberId          int64   `json:"memberId"`          // 会员id
	MemberUsername    string  `json:"memberUserName"`    // 用户帐号
	TotalAmount       float32 `json:"totalAmount"`       // 订单总金额
	PayAmount         float32 `json:"payAmount"`         // 应付金额（实际支付金额）
	FreightAmount     float32 `json:"freightAmount"`     // 运费金额
	PromotionAmount   float32 `json:"promotionAmount"`   // 促销优化金额（促销价、满减、阶梯价）
	IntegrationAmount float32 `json:"integrationAmount"` // 积分抵扣金额
	CouponAmount      float32 `json:"couponAmount"`      // 优惠券抵扣金额
	DiscountAmount    float32 `json:"discountAmount"`    // 管理员后台调整订单使用的折扣金额
	PayType           int64   `json:"payType"`           // 支付方式：0->未支付；1->支付宝；2->微信
	SourceType        int64   `json:"sourceType"`        // 订单来源：0->PC订单；1->app订单
	Status            int64   `json:"status"`            // 订单状态：0->待付款；1->待发货；2->已发货；3->已完成；4->已关闭；5->无效订单
	OrderType         int64   `json:"orderType"`         // 订单类型：0->正常订单；1->秒杀订单
	Integration       int64   `json:"integration"`       // 可以获得的积分
	Growth            int64   `json:"growth"`            // 可以活动的成长值
	PromotionInfo     string  `json:"promotionInfo"`     // 活动信息
	Note              string  `json:"note"`              // 订单备注
	UseIntegration    int64   `json:"useIntegration"`    // 下单时使用的积分
}

type PayCallbackReq struct {
	OrderId   int64 `json:"orderId"`
	ProductId int64 `json:"productId"`
}

type PayCallbackResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type OrderListReq struct {
	Current  int64 `path:"current,default=1"`
	PageSize int64 `path:"pageSize,default=5"`
	Status   int64 `path:"status"` // 订单状态：0->待付款；1->待发货；2->已发货；3->已完成；4->已关闭；5->无效订单
}

type ListOrderData struct {
	Id                    int64               `json:"id"` // 订单id
	MemberId              int64               `json:"memberId"`
	CouponId              int64               `json:"couponId"`
	OrderSn               string              `json:"orderSn"`               // 订单编号
	CreateTime            string              `json:"createTime"`            // 提交时间
	MemberUsername        string              `json:"memberUserName"`        // 用户帐号
	TotalAmount           float64             `json:"totalAmount"`           // 订单总金额
	PayAmount             float64             `json:"payAmount"`             // 应付金额（实际支付金额）
	FreightAmount         float64             `json:"freightAmount"`         // 运费金额
	PromotionAmount       float64             `json:"promotionAmount"`       // 促销优化金额（促销价、满减、阶梯价）
	IntegrationAmount     float64             `json:"integrationAmount"`     // 积分抵扣金额
	CouponAmount          float64             `json:"couponAmount"`          // 优惠券抵扣金额
	DiscountAmount        float64             `json:"discountAmount"`        // 管理员后台调整订单使用的折扣金额
	PayType               int64               `json:"payType"`               // 支付方式：0->未支付；1->支付宝；2->微信
	SourceType            int64               `json:"sourceType"`            // 订单来源：0->PC订单；1->app订单
	Status                int64               `json:"status"`                // 订单状态：0->待付款；1->待发货；2->已发货；3->已完成；4->已关闭；5->无效订单
	OrderType             int64               `json:"orderType"`             // 订单类型：0->正常订单；1->秒杀订单
	DeliveryCompany       string              `json:"deliveryCompany"`       // 物流公司(配送方式)
	DeliverySn            string              `json:"deliverySn"`            // 物流单号
	AutoConfirmDay        int64               `json:"autoConfirmDay"`        // 自动确认时间（天）
	Integration           int64               `json:"integration"`           // 可以获得的积分
	Growth                int64               `json:"growth"`                // 可以活动的成长值
	PromotionInfo         string              `json:"promotionInfo"`         // 活动信息
	BillType              int64               `json:"billType"`              // 发票类型：0->不开发票；1->电子发票；2->纸质发票
	BillHeader            string              `json:"billHeader"`            // 发票抬头
	BillContent           string              `json:"billContent"`           // 发票内容
	BillReceiverPhone     string              `json:"billReceiverPhone"`     // 收票人电话
	BillReceiverEmail     string              `json:"billReceiverEmail"`     // 收票人邮箱
	ReceiverName          string              `json:"receiverName"`          // 收货人姓名
	ReceiverPhone         string              `json:"receiverPhone"`         // 收货人电话
	ReceiverPostCode      string              `json:"receiverPostCode"`      // 收货人邮编
	ReceiverProvince      string              `json:"receiverProvince"`      // 省份/直辖市
	ReceiverCity          string              `json:"receiverCity"`          // 城市
	ReceiverRegion        string              `json:"receiverRegion"`        // 区
	ReceiverDetailAddress string              `json:"receiverDetailAddress"` // 详细地址
	Note                  string              `json:"note"`                  // 订单备注
	ConfirmStatus         int64               `json:"confirmStatus"`         // 确认收货状态：0->未确认；1->已确认
	DeleteStatus          int64               `json:"deleteStatus"`          // 删除状态：0->未删除；1->已删除
	UseIntegration        int64               `json:"useIntegration"`        // 下单时使用的积分
	PaymentTime           string              `json:"paymentTime"`           // 支付时间
	DeliveryTime          string              `json:"deliveryTime"`          // 发货时间
	ReceiveTime           string              `json:"receiveTime"`           // 确认收货时间
	CommentTime           string              `json:"commentTime"`           // 评价时间
	ModifyTime            string              `json:"modifyTime"`            // 修改时间
	ListOrderItem         []ListOrderItemData `json:"orderItemList"`         // 商品数据
}

type ListOrderItemData struct {
	Id                int64   `json:"id"`
	OrderId           int64   `json:"orderId"` // 订单id
	OrderSn           string  `json:"orderSn"` // 订单编号
	ProductId         int64   `json:"productId"`
	ProductPic        string  `json:"productPic"`
	ProductName       string  `json:"productName"`
	ProductBrand      string  `json:"productBrand"`
	ProductSn         string  `json:"productSn"`
	ProductPrice      float32 `json:"productPrice"`      // 销售价格
	ProductQuantity   int64   `json:"productQuantity"`   // 购买数量
	ProductSkuId      int64   `json:"productSkuId"`      // 商品sku编号
	ProductSkuCode    string  `json:"productSkuCode"`    // 商品sku条码
	ProductCategoryId int64   `json:"productCategoryId"` // 商品分类id
	PromotionName     string  `json:"promotionName"`     // 商品促销名称
	PromotionAmount   float32 `json:"promotionAmount"`   // 商品促销分解金额
	CouponAmount      float32 `json:"couponAmount"`      // 优惠券优惠分解金额
	IntegrationAmount float32 `json:"integrationAmount"` // 积分优惠分解金额
	RealAmount        float32 `json:"realAmount"`        // 该商品经过优惠后的分解金额
	GiftIntegration   int64   `json:"giftIntegration"`
	GiftGrowth        int64   `json:"giftGrowth"`
	ProductAttr       string  `json:"productAttr"` // 商品销售属性:[{"key":"颜色","value":"颜色"},{"key":"容量","value":"4G"}]
}

type OrderListResp struct {
	Code    int64            `json:"code"`
	Message string           `json:"message"`
	Data    []*ListOrderData `json:"data"`
}

type OrderDetailReq struct {
	OrderId int64 `path:"orderId"`
}

type OrderDetailResp struct {
	Code    int64         `json:"code"`
	Message string        `json:"message"`
	Data    ListOrderData `json:"data"`
}

type CancelUserOrderReq struct {
	OrderId int64 `path:"orderId"`
}

type CancelUserOrderResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type ConfirmReceiveOrderReq struct {
	OrderId int64 `path:"orderId"`
}

type ConfirmReceiveOrderResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type DeleteOrderReq struct {
	OrderId int64 `path:"orderId"`
}

type DeleteOrderResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type ReturnApplyReq struct {
	OrderId          int64   `json:"orderId"`
	ProductId        int64   `json:"productId"`
	OrderSn          string  `json:"orderSn"`
	MemberUsername   string  `json:"memberUsername"`
	ReturnName       string  `json:"returnName"`
	ReturnPhone      string  `json:"returnPhone"`
	ProductPic       string  `json:"productPic"`
	ProductName      string  `json:"productName"`
	ProductBrand     string  `json:"productBrand"`
	ProductAttr      string  `json:"productAttr"`
	ProductCount     int64   `json:"productCount"`
	ProductPrice     float32 `json:"productPrice"`
	ProductRealPrice float32 `json:"productRealPrice"`
	Reason           string  `json:"reason"`
	Description      string  `json:"description"`
	ProofPics        string  `json:"proofPics"`
}

type ReturnApplyResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type QueryProductReq struct {
	Id int64 `path:"id"`
}

type QueryProductResp struct {
	Code    int64       `json:"code"`
	Message string      `json:"message"`
	Data    ProductData `json:"data"`
}

type ProductData struct {
	Product                   Product                     `json:"product"`
	Brand                     Brand                       `json:"brand"`
	ProductAttributeList      []ProductAttributeList      `json:"productAttributeList"`
	ProductAttributeValueList []ProductAttributeValueList `json:"productAttributeValueList"`
	SkuStockList              []SkuStockList              `json:"skuStockList"`
	ProductLadderList         []ProductLadderList         `json:"productLadderList"`
	ProductFullReductionList  []ProductFullReductionList  `json:"productFullReductionList"`
	CouponList                []CouponList                `json:"couponList"`
}

type Brand struct {
	Id                  int64  `json:"id"`
	Name                string `json:"name"`
	FirstLetter         string `json:"firstLetter"`
	Sort                int64  `json:"sort"`
	FactoryStatus       int64  `json:"factoryStatus"`
	ShowStatus          int64  `json:"showStatus"`
	ProductCount        int64  `json:"productCount"`
	ProductCommentCount int64  `json:"productCommentCount"`
	Logo                string `json:"logo"`
	BigPic              string `json:"bigPic"`
	BrandStory          string `json:"brandStory"`
}

type CouponList struct {
	Id           int64   `json:"id"`
	Type         int64   `json:"type"`
	Name         string  `json:"name"`
	Platform     int64   `json:"platform"`
	Count        int64   `json:"count"`
	Amount       float64 `json:"amount"`
	PerLimit     int64   `json:"perLimit"`
	MinPoint     float64 `json:"minPoint"`
	StartTime    string  `json:"startTime"`
	EndTime      string  `json:"endTime"`
	UseType      int64   `json:"useType"`
	PublishCount int64   `json:"publishCount"`
	UseCount     int64   `json:"useCount"`
	ReceiveCount int64   `json:"receiveCount"`
	EnableTime   string  `json:"enableTime"`
}

type Product struct {
	Id                         int64   `json:"id"`
	BrandId                    int64   `json:"brandId"`
	ProductCategoryId          int64   `json:"productCategoryId"`
	FeightTemplateId           int64   `json:"feightTemplateId"`
	ProductAttributeCategoryId int64   `json:"productAttributeCategoryId"`
	Name                       string  `json:"name"`
	Pic                        string  `json:"pic"`
	ProductSn                  string  `json:"productSn"`
	DeleteStatus               int64   `json:"deleteStatus"`
	PublishStatus              int64   `json:"publishStatus"`
	NewStatus                  int64   `json:"newStatus"`
	RecommandStatus            int64   `json:"recommandStatus"`
	VerifyStatus               int64   `json:"verifyStatus"`
	Sort                       int64   `json:"sort"`
	Sale                       int64   `json:"sale"`
	Price                      float64 `json:"price"`
	PromotionPrice             float64 `json:"promotionPrice"`
	GiftGrowth                 int64   `json:"giftGrowth"`
	GiftPoint                  int64   `json:"giftPoint"`
	UsePointLimit              int64   `json:"usePointLimit"`
	SubTitle                   string  `json:"subTitle"`
	OriginalPrice              float64 `json:"originalPrice"`
	Stock                      int64   `json:"stock"`
	LowStock                   int64   `json:"lowStock"`
	Unit                       string  `json:"unit"`
	Weight                     float64 `json:"weight"`
	PreviewStatus              int64   `json:"previewStatus"`
	ServiceIds                 string  `json:"serviceIds"`
	Keywords                   string  `json:"keywords"`
	Note                       string  `json:"note"`
	AlbumPics                  string  `json:"albumPics"`
	DetailTitle                string  `json:"detailTitle"`
	PromotionStartTime         string  `json:"promotionStartTime"`
	PromotionEndTime           string  `json:"promotionEndTime"`
	PromotionPerLimit          int64   `json:"promotionPerLimit"`
	PromotionType              int64   `json:"promotionType"`
	BrandName                  string  `json:"brandName"`
	ProductCategoryName        string  `json:"productCategoryName"`
	Description                string  `json:"description"`
	DetailDesc                 string  `json:"detailDesc"`
	DetailHtml                 string  `json:"detailHtml"`
	DetailMobileHtml           string  `json:"detailMobileHtml"`
}

type ProductAttributeList struct {
	Id                         int64  `json:"id"`
	ProductAttributeCategoryId int64  `json:"productAttributeCategoryId"`
	Name                       string `json:"name"`
	SelectType                 int64  `json:"selectType"`
	InputType                  int64  `json:"inputType"`
	InputList                  string `json:"inputList"`
	Sort                       int64  `json:"sort"`
	FilterType                 int64  `json:"filterType"`
	SearchType                 int64  `json:"searchType"`
	RelatedStatus              int64  `json:"relatedStatus"`
	HandAddStatus              int64  `json:"handAddStatus"`
	Type                       int64  `json:"type"`
}

type ProductAttributeValueList struct {
	Id                 int64  `json:"id"`
	ProductId          int64  `json:"productId"`
	ProductAttributeId int64  `json:"productAttributeId"`
	Value              string `json:"value"`
}

type ProductLadderList struct {
	Id        int64   `json:"id"`
	ProductId int64   `json:"productId"`
	Count     int64   `json:"count"`
	Discount  float32 `json:"discount"`
	Price     float32 `json:"price"`
}

type SkuStockList struct {
	Id             int64   `json:"id"`
	ProductId      int64   `json:"productId"`
	SkuCode        string  `json:"skuCode"` // sku编码
	Price          float32 `json:"price"`
	Stock          int64   `json:"stock"`          // 库存
	LowStock       int64   `json:"lowStock"`       // 预警库存
	Pic            string  `json:"pic"`            // 展示图片
	Sale           int64   `json:"sale"`           // 销量
	PromotionPrice float32 `json:"promotionPrice"` // 单品促销价格
	LockStock      int64   `json:"lockStock"`      // 锁定库存
	SpData         string  `json:"spData"`         // 商品销售属性，json格式
}

type ProductFullReductionList struct {
	Id          int64   `json:"id"`
	ProductId   int64   `json:"productId"`
	FullPrice   float32 `json:"fullPrice"`
	ReducePrice float32 `json:"reducePrice"`
}

type QueryProductListReq struct {
	Current           int64 `path:"current,default=1"`
	PageSize          int64 `path:"pageSize,default=10"`
	BrandId           int64 `path:"brandId,default=0"`
	ProductCategoryId int64 `path:"productCategoryId,default=0"`
}

type QueryProductListResp struct {
	Code    int64                  `json:"code"`
	Message string                 `json:"message"`
	Data    []QueryProductListData `json:"data"`
}

type QueryProductListData struct {
	Id                         int64   `json:"id"`
	BrandId                    int64   `json:"brandId"`
	ProductCategoryId          int64   `json:"productCategoryId"`
	FeightTemplateId           int64   `json:"feightTemplateId"`
	ProductAttributeCategoryId int64   `json:"productAttributeCategoryId"`
	Name                       string  `json:"name"`
	Pic                        string  `json:"pic"`
	ProductSn                  string  `json:"productSn"`
	DeleteStatus               int64   `json:"deleteStatus"`
	PublishStatus              int64   `json:"publishStatus"`
	NewStatus                  int64   `json:"newStatus"`
	RecommandStatus            int64   `json:"recommandStatus"`
	VerifyStatus               int64   `json:"verifyStatus"`
	Sort                       int64   `json:"sort"`
	Sale                       int64   `json:"sale"`
	Price                      float64 `json:"price"`
	PromotionPrice             float64 `json:"promotionPrice,omitempty"`
	GiftGrowth                 int64   `json:"giftGrowth"`
	GiftPoint                  int64   `json:"giftPoint"`
	UsePointLimit              int64   `json:"usePointLimit"`
	SubTitle                   string  `json:"subTitle"`
	OriginalPrice              float64 `json:"originalPrice"`
	Stock                      int64   `json:"stock"`
	LowStock                   int64   `json:"lowStock"`
	Unit                       string  `json:"unit"`
	Weight                     float64 `json:"weight"`
	PreviewStatus              int64   `json:"previewStatus"`
	ServiceIDS                 string  `json:"serviceIds"`
	Keywords                   string  `json:"keywords"`
	Note                       string  `json:"note"`
	AlbumPics                  string  `json:"albumPics"`
	DetailTitle                string  `json:"detailTitle"`
	PromotionStartTime         string  `json:"promotionStartTime,omitempty"`
	PromotionEndTime           string  `json:"promotionEndTime,omitempty"`
	PromotionPerLimit          int64   `json:"promotionPerLimit"`
	PromotionType              int64   `json:"promotionType"`
	BrandName                  string  `json:"brandName"`
	ProductCategoryName        string  `json:"productCategoryName"`
	Description                string  `json:"description"`
}

type AddProductCollectionReq struct {
	ProductId       int64   `json:"productId"`       // 商品id
	ProductName     string  `json:"productName"`     // 商品名称
	ProductPic      string  `json:"productPic"`      // 商品图片
	ProductSubTitle string  `json:"productSubTitle"` // 商品标题
	ProductPrice    float64 `json:"productPrice"`    // 商品价格
}

type AddProductCollectionResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type ProductCollectionDeleteReq struct {
	Id int64 `path:"id"`
}

type ProductCollectionDeleteResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type ProductCollectionListResp struct {
	Code    int64                   `json:"code"`
	Message string                  `json:"message"`
	Data    []ProductCollectionList `json:"data"` //收藏列表
}

type ProductCollectionList struct {
	Id              int64   `json:"id"`              // 编号
	MemberId        int64   `json:"memberId"`        // 会员id
	MemberNickName  string  `json:"memberNickName"`  // 会员姓名
	MemberIcon      string  `json:"memberIcon"`      // 会员头像
	ProductId       int64   `json:"productId"`       // 商品id
	ProductName     string  `json:"productName"`     // 商品名称
	ProductPic      string  `json:"productPic"`      // 商品图片
	ProductSubTitle string  `json:"productSubTitle"` // 商品标题
	ProductPrice    float64 `json:"productPrice"`    // 商品价格
	CreateTime      string  `json:"createTime"`      // 浏览时间
}

type ProductCollectionClearResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type AddReadHistoryReq struct {
	ProductId       int64   `json:"productId"`       // 商品id
	ProductName     string  `json:"productName"`     // 商品名称
	ProductPic      string  `json:"productPic"`      // 商品图片
	ProductSubTitle string  `json:"productSubTitle"` // 商品标题
	ProductPrice    float64 `json:"productPrice"`    // 商品价格
}

type AddReadHistoryResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type ReadHistoryDeleteReq struct {
	Id int64 `path:"id"`
}

type ReadHistoryDeleteResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type ReadHistoryListResp struct {
	Code    int64             `json:"code"`
	Message string            `json:"message"`
	Data    []ReadHistoryList `json:"data"` //浏览列表
}

type ReadHistoryList struct {
	Id              int64   `json:"id"`              // 编号
	MemberId        int64   `json:"memberId"`        // 会员id
	MemberNickName  string  `json:"memberNickName"`  // 会员姓名
	MemberIcon      string  `json:"memberIcon"`      // 会员头像
	ProductId       int64   `json:"productId"`       // 商品id
	ProductName     string  `json:"productName"`     // 商品名称
	ProductPic      string  `json:"productPic"`      // 商品图片
	ProductSubTitle string  `json:"productSubTitle"` // 商品标题
	ProductPrice    float64 `json:"productPrice"`    // 商品价格
	CreateTime      string  `json:"createTime"`      // 浏览时间
}

type ReadHistoryClearResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type AddCouponReq struct {
	CouponId int64 `json:"couponId"`
}

type AddCouponResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type ListCouponHistoryReq struct {
	UseStatus int64 `path:"useStatus,default=3"` // 使用状态：0->未使用；1->已使用；2->已过期
}

type ListCouponHistoryData struct {
	Id           int64   `json:"id"`
	Type         int64   `json:"type"` // 优惠券类型；0->全场赠券；1->会员赠券；2->购物赠券；3->注册赠券
	Name         string  `json:"name"`
	Platform     int64   `json:"platform"` // 使用平台：0->全部；1->移动；2->PC
	Count        int64   `json:"count"`    // 数量
	Amount       float64 `json:"amount"`   // 金额
	PerLimit     int64   `json:"perLimit"` // 每人限领张数
	MinPoint     float64 `json:"minPoint"` // 使用门槛；0表示无门槛
	StartTime    string  `json:"startTime"`
	EndTime      string  `json:"endTime"`
	UseType      int64   `json:"useType"`      // 使用类型：0->全场通用；1->指定分类；2->指定商品
	Note         string  `json:"note"`         // 备注
	PublishCount int64   `json:"publishCount"` // 发行数量
	UseCount     int64   `json:"useCount"`     // 已使用数量
	ReceiveCount int64   `json:"receiveCount"` // 领取数量
	EnableTime   string  `json:"enableTime"`   // 可以领取的日期
	Code         string  `json:"code"`         // 优惠码
	MemberLevel  int64   `json:"memberLevel"`  // 可领取的会员类型：0->无限时
}

type ListCouponHistoryResp struct {
	Code    int64                    `json:"code"`
	Message string                   `json:"message"`
	Data    []*ListCouponHistoryData `json:"data"`
}

type ListCouponReq struct {
	ProductId int64 `path:"productId"` // 商品id
}

type ListtCouponData struct {
	Id           int64   `json:"id"`
	Type         int64   `json:"type"` // 优惠券类型；0->全场赠券；1->会员赠券；2->购物赠券；3->注册赠券
	Name         string  `json:"name"`
	Platform     int64   `json:"platform"` // 使用平台：0->全部；1->移动；2->PC
	Count        int64   `json:"count"`    // 数量
	Amount       float64 `json:"amount"`   // 金额
	PerLimit     int64   `json:"perLimit"` // 每人限领张数
	MinPoint     float64 `json:"minPoint"` // 使用门槛；0表示无门槛
	StartTime    string  `json:"startTime"`
	EndTime      string  `json:"endTime"`
	UseType      int64   `json:"useType"`      // 使用类型：0->全场通用；1->指定分类；2->指定商品
	Note         string  `json:"note"`         // 备注
	PublishCount int64   `json:"publishCount"` // 发行数量
	UseCount     int64   `json:"useCount"`     // 已使用数量
	ReceiveCount int64   `json:"receiveCount"` // 领取数量
	EnableTime   string  `json:"enableTime"`   // 可以领取的日期
	Code         string  `json:"code"`         // 优惠码
	MemberLevel  int64   `json:"memberLevel"`  // 可领取的会员类型：0->无限时
}

type ListCouponResp struct {
	Code    int64              `json:"code"`
	Message string             `json:"message"`
	Data    []*ListtCouponData `json:"data"`
}

type CouponListByCartReq struct {
	UseStatus int64 `path:"useStatus"` // 使用状态-使用可用:0->不可用；1->可用
}

type CouponListByCartResp struct {
	Code    int64          `json:"code"`
	Message string         `json:"message"`
	Data    ListCouponData `json:"data"`
}

type ListCouponData struct {
	EnableList  interface{} `json:"enableList"`
	DisableList interface{} `json:"disableList"`
}

type BrandListResp struct {
	Code    int64           `json:"code"`
	Message string          `json:"message"`
	Data    []BrandListData `json:"data"`
}

type BrandListData struct {
	Id                  int64  `json:"id"`
	Name                string `json:"name"`
	FirstLetter         string `json:"firstLetter"`
	Sort                int64  `json:"sort"`
	FactoryStatus       int64  `json:"factoryStatus"`
	ShowStatus          int64  `json:"showStatus"`
	ProductCount        int64  `json:"productCount"`
	ProductCommentCount int64  `json:"productCommentCount"`
	Logo                string `json:"logo"`
	BigPic              string `json:"bigPic"`
}

type BrandDetailReq struct {
	BrandId int64 `path:"brandId"`
}

type BrandDetailResp struct {
	Code    int64           `json:"code"`
	Message string          `json:"message"`
	Data    BrandDetailData `json:"data"`
}

type BrandDetailData struct {
	Id                  int64              `json:"id"`
	Name                string             `json:"name"`
	FirstLetter         string             `json:"firstLetter"`
	Sort                int64              `json:"sort"`
	FactoryStatus       int64              `json:"factoryStatus"`
	ShowStatus          int64              `json:"showStatus"`
	ProductCount        int64              `json:"productCount"`
	ProductCommentCount int64              `json:"productCommentCount"`
	Logo                string             `json:"logo"`
	BigPic              string             `json:"bigPic"`
	BrandStory          string             `json:"brandStory"` // 品牌故事
	ProductList         []BrandProductList `json:"productList"`
}

type BrandProductList struct {
	Id                         int64   `json:"id"`
	BrandId                    int64   `json:"brandId"`
	ProductCategoryId          int64   `json:"productCategoryId"`
	FeightTemplateId           int64   `json:"feightTemplateId"`
	ProductAttributeCategoryId int64   `json:"productAttributeCategoryId"`
	Name                       string  `json:"name"`
	Pic                        string  `json:"pic"`
	ProductSn                  string  `json:"productSn"`
	DeleteStatus               int64   `json:"deleteStatus"`
	PublishStatus              int64   `json:"publishStatus"`
	NewStatus                  int64   `json:"newStatus"`
	RecommandStatus            int64   `json:"recommandStatus"`
	VerifyStatus               int64   `json:"verifyStatus"`
	Sort                       int64   `json:"sort"`
	Sale                       int64   `json:"sale"`
	Price                      float64 `json:"price"`
	PromotionPrice             float64 `json:"promotionPrice"`
	GiftGrowth                 int64   `json:"giftGrowth"`
	GiftPoint                  int64   `json:"giftPoint"`
	UsePointLimit              int64   `json:"usePointLimit"`
	SubTitle                   string  `json:"subTitle"`
	OriginalPrice              float64 `json:"originalPrice"`
	Stock                      int64   `json:"stock"`
	LowStock                   int64   `json:"lowStock"`
	Unit                       string  `json:"unit"`
	Weight                     float64 `json:"weight"`
	PreviewStatus              int64   `json:"previewStatus"`
	ServiceIDS                 string  `json:"serviceIds"`
	Keywords                   string  `json:"keywords"`
	Note                       string  `json:"note"`
	AlbumPics                  string  `json:"albumPics"`
	DetailTitle                string  `json:"detailTitle"`
	PromotionStartTime         string  `json:"promotionStartTime"`
	PromotionEndTime           string  `json:"promotionEndTime"`
	PromotionPerLimit          int64   `json:"promotionPerLimit"`
	PromotionType              int64   `json:"promotionType"`
	BrandName                  string  `json:"brandName"`
	ProductCategoryName        string  `json:"productCategoryName"`
	Description                string  `json:"description"`
}

type AddAttentionReq struct {
	BrandId   int64  `json:"brandId"`   // 品牌id
	BrandName string `json:"brandName"` // 品牌名称
	BrandLogo string `json:"brandLogo"` // 品牌Logo
	BrandCity string `json:"brandCity"` // 品牌所在城市
}

type AddAttentionResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type ListAttentionData struct {
	Id             int64  `json:"id"`
	MemberId       int64  `json:"memberId"`       // 会员id
	MemberNickName string `json:"memberNickName"` // 会员姓名
	MemberIcon     string `json:"memberIcon"`     // 会员头像
	BrandId        int64  `json:"brandId"`        // 品牌id
	BrandName      string `json:"brandName"`      // 品牌名称
	BrandLogo      string `json:"brandLogo"`      // 品牌Logo
	BrandCity      string `json:"brandCity"`      // 品牌所在城市
	CreateTime     string `json:"createTime"`     // 关注时间
}

type ListAttentionResp struct {
	Data    []ListAttentionData `json:"data"`
	Success bool                `json:"success"`
	Code    int64               `json:"code"`
	Message string              `json:"message"`
}

type ClearAttentionResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type DeleteAttentionReq struct {
	Id int64 `path:"id"`
}

type DeleteAttentionResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type OrderPayReq struct {
	OrderId int64  `json:"orderId"`
	Remark  string `json:"remark,optional"`
}

type OrderPayResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
	Data    string `json:"data"`
}

type OrderPayQueryReq struct {
	OrderId int64 `json:"orderId"`
}

type OrderPayQueryResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
	Data    string `json:"data"`
}
