// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1
// Source: pms.proto

package server

import (
	"context"

	"github.com/feihua/zero-admin/rpc/pms/internal/logic/productattributevalueservice"
	"github.com/feihua/zero-admin/rpc/pms/internal/svc"
	"github.com/feihua/zero-admin/rpc/pms/pmsclient"
)

type ProductAttributeValueServiceServer struct {
	svcCtx *svc.ServiceContext
	pmsclient.UnimplementedProductAttributeValueServiceServer
}

func NewProductAttributeValueServiceServer(svcCtx *svc.ServiceContext) *ProductAttributeValueServiceServer {
	return &ProductAttributeValueServiceServer{
		svcCtx: svcCtx,
	}
}

// 添加存储产品参数信息的表
func (s *ProductAttributeValueServiceServer) AddProductAttributeValue(ctx context.Context, in *pmsclient.AddProductAttributeValueReq) (*pmsclient.AddProductAttributeValueResp, error) {
	l := productattributevalueservicelogic.NewAddProductAttributeValueLogic(ctx, s.svcCtx)
	return l.AddProductAttributeValue(in)
}

// 删除存储产品参数信息的表
func (s *ProductAttributeValueServiceServer) DeleteProductAttributeValue(ctx context.Context, in *pmsclient.DeleteProductAttributeValueReq) (*pmsclient.DeleteProductAttributeValueResp, error) {
	l := productattributevalueservicelogic.NewDeleteProductAttributeValueLogic(ctx, s.svcCtx)
	return l.DeleteProductAttributeValue(in)
}

// 更新存储产品参数信息的表
func (s *ProductAttributeValueServiceServer) UpdateProductAttributeValue(ctx context.Context, in *pmsclient.UpdateProductAttributeValueReq) (*pmsclient.UpdateProductAttributeValueResp, error) {
	l := productattributevalueservicelogic.NewUpdateProductAttributeValueLogic(ctx, s.svcCtx)
	return l.UpdateProductAttributeValue(in)
}

// 查询存储产品参数信息的表列表
func (s *ProductAttributeValueServiceServer) QueryProductAttributeValueList(ctx context.Context, in *pmsclient.QueryProductAttributeValueListReq) (*pmsclient.QueryProductAttributeValueListResp, error) {
	l := productattributevalueservicelogic.NewQueryProductAttributeValueListLogic(ctx, s.svcCtx)
	return l.QueryProductAttributeValueList(in)
}
