// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: ums.proto

package memberbrandattentionservice

import (
	"context"

	"github.com/feihua/zero-admin/rpc/ums/umsclient"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddMemberBrandAttentionReq          = umsclient.AddMemberBrandAttentionReq
	AddMemberBrandAttentionResp         = umsclient.AddMemberBrandAttentionResp
	DeleteMemberBrandAttentionReq       = umsclient.DeleteMemberBrandAttentionReq
	DeleteMemberBrandAttentionResp      = umsclient.DeleteMemberBrandAttentionResp
	MemberBrandAttentionListData        = umsclient.MemberBrandAttentionListData
	QueryMemberBrandAttentionDetailReq  = umsclient.QueryMemberBrandAttentionDetailReq
	QueryMemberBrandAttentionDetailResp = umsclient.QueryMemberBrandAttentionDetailResp
	QueryMemberBrandAttentionListReq    = umsclient.QueryMemberBrandAttentionListReq
	QueryMemberBrandAttentionListResp   = umsclient.QueryMemberBrandAttentionListResp

	MemberBrandAttentionService interface {
		// 添加会员关注品牌
		AddMemberBrandAttention(ctx context.Context, in *AddMemberBrandAttentionReq, opts ...grpc.CallOption) (*AddMemberBrandAttentionResp, error)
		// 取消品牌关注/清空当前用户品牌关注列表
		DeleteMemberBrandAttention(ctx context.Context, in *DeleteMemberBrandAttentionReq, opts ...grpc.CallOption) (*DeleteMemberBrandAttentionResp, error)
		// 查询会员关注品牌详情
		QueryMemberBrandAttentionDetail(ctx context.Context, in *QueryMemberBrandAttentionDetailReq, opts ...grpc.CallOption) (*QueryMemberBrandAttentionDetailResp, error)
		// 查询会员关注品牌列表
		QueryMemberBrandAttentionList(ctx context.Context, in *QueryMemberBrandAttentionListReq, opts ...grpc.CallOption) (*QueryMemberBrandAttentionListResp, error)
	}

	defaultMemberBrandAttentionService struct {
		cli zrpc.Client
	}
)

func NewMemberBrandAttentionService(cli zrpc.Client) MemberBrandAttentionService {
	return &defaultMemberBrandAttentionService{
		cli: cli,
	}
}

// 添加会员关注品牌
func (m *defaultMemberBrandAttentionService) AddMemberBrandAttention(ctx context.Context, in *AddMemberBrandAttentionReq, opts ...grpc.CallOption) (*AddMemberBrandAttentionResp, error) {
	client := umsclient.NewMemberBrandAttentionServiceClient(m.cli.Conn())
	return client.AddMemberBrandAttention(ctx, in, opts...)
}

// 取消品牌关注/清空当前用户品牌关注列表
func (m *defaultMemberBrandAttentionService) DeleteMemberBrandAttention(ctx context.Context, in *DeleteMemberBrandAttentionReq, opts ...grpc.CallOption) (*DeleteMemberBrandAttentionResp, error) {
	client := umsclient.NewMemberBrandAttentionServiceClient(m.cli.Conn())
	return client.DeleteMemberBrandAttention(ctx, in, opts...)
}

// 查询会员关注品牌详情
func (m *defaultMemberBrandAttentionService) QueryMemberBrandAttentionDetail(ctx context.Context, in *QueryMemberBrandAttentionDetailReq, opts ...grpc.CallOption) (*QueryMemberBrandAttentionDetailResp, error) {
	client := umsclient.NewMemberBrandAttentionServiceClient(m.cli.Conn())
	return client.QueryMemberBrandAttentionDetail(ctx, in, opts...)
}

// 查询会员关注品牌列表
func (m *defaultMemberBrandAttentionService) QueryMemberBrandAttentionList(ctx context.Context, in *QueryMemberBrandAttentionListReq, opts ...grpc.CallOption) (*QueryMemberBrandAttentionListResp, error) {
	client := umsclient.NewMemberBrandAttentionServiceClient(m.cli.Conn())
	return client.QueryMemberBrandAttentionList(ctx, in, opts...)
}
