// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: ums.proto

package membertagrelationservice

import (
	"context"

	"github.com/feihua/zero-admin/rpc/ums/umsclient"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddMemberTagRelationReq          = umsclient.AddMemberTagRelationReq
	AddMemberTagRelationResp         = umsclient.AddMemberTagRelationResp
	MemberTagRelationListData        = umsclient.MemberTagRelationListData
	QueryMemberTagRelationDetailReq  = umsclient.QueryMemberTagRelationDetailReq
	QueryMemberTagRelationDetailResp = umsclient.QueryMemberTagRelationDetailResp
	QueryMemberTagRelationListReq    = umsclient.QueryMemberTagRelationListReq
	QueryMemberTagRelationListResp   = umsclient.QueryMemberTagRelationListResp

	MemberTagRelationService interface {
		// 添加会员标签关联
		AddMemberTagRelation(ctx context.Context, in *AddMemberTagRelationReq, opts ...grpc.CallOption) (*AddMemberTagRelationResp, error)
		// 查询会员标签关联详情
		QueryMemberTagRelationDetail(ctx context.Context, in *QueryMemberTagRelationDetailReq, opts ...grpc.CallOption) (*QueryMemberTagRelationDetailResp, error)
		// 查询会员标签关联列表
		QueryMemberTagRelationList(ctx context.Context, in *QueryMemberTagRelationListReq, opts ...grpc.CallOption) (*QueryMemberTagRelationListResp, error)
	}

	defaultMemberTagRelationService struct {
		cli zrpc.Client
	}
)

func NewMemberTagRelationService(cli zrpc.Client) MemberTagRelationService {
	return &defaultMemberTagRelationService{
		cli: cli,
	}
}

// 添加会员标签关联
func (m *defaultMemberTagRelationService) AddMemberTagRelation(ctx context.Context, in *AddMemberTagRelationReq, opts ...grpc.CallOption) (*AddMemberTagRelationResp, error) {
	client := umsclient.NewMemberTagRelationServiceClient(m.cli.Conn())
	return client.AddMemberTagRelation(ctx, in, opts...)
}

// 查询会员标签关联详情
func (m *defaultMemberTagRelationService) QueryMemberTagRelationDetail(ctx context.Context, in *QueryMemberTagRelationDetailReq, opts ...grpc.CallOption) (*QueryMemberTagRelationDetailResp, error) {
	client := umsclient.NewMemberTagRelationServiceClient(m.cli.Conn())
	return client.QueryMemberTagRelationDetail(ctx, in, opts...)
}

// 查询会员标签关联列表
func (m *defaultMemberTagRelationService) QueryMemberTagRelationList(ctx context.Context, in *QueryMemberTagRelationListReq, opts ...grpc.CallOption) (*QueryMemberTagRelationListResp, error) {
	client := umsclient.NewMemberTagRelationServiceClient(m.cli.Conn())
	return client.QueryMemberTagRelationList(ctx, in, opts...)
}
