// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4
// Source: oms.proto

package orderreturnreasonservice

import (
	"context"

	"github.com/feihua/zero-admin/rpc/oms/omsclient"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddCartItemReq                    = omsclient.AddCartItemReq
	AddCompanyAddressReq              = omsclient.AddCompanyAddressReq
	AddCompanyAddressResp             = omsclient.AddCompanyAddressResp
	AddOrderDeliveryReq               = omsclient.AddOrderDeliveryReq
	AddOrderDeliveryResp              = omsclient.AddOrderDeliveryResp
	AddOrderOperationLogReq           = omsclient.AddOrderOperationLogReq
	AddOrderOperationLogResp          = omsclient.AddOrderOperationLogResp
	AddOrderReq                       = omsclient.AddOrderReq
	AddOrderResp                      = omsclient.AddOrderResp
	AddOrderReturnReasonReq           = omsclient.AddOrderReturnReasonReq
	AddOrderReturnReasonResp          = omsclient.AddOrderReturnReasonResp
	AddOrderSettingReq                = omsclient.AddOrderSettingReq
	AddOrderSettingResp               = omsclient.AddOrderSettingResp
	CancelOrderReq                    = omsclient.CancelOrderReq
	CancelOrderResp                   = omsclient.CancelOrderResp
	CartItemData                      = omsclient.CartItemData
	CartItemResp                      = omsclient.CartItemResp
	CloseOrderReq                     = omsclient.CloseOrderReq
	CloseOrderResp                    = omsclient.CloseOrderResp
	CompanyAddressListData            = omsclient.CompanyAddressListData
	ConfirmOrderReq                   = omsclient.ConfirmOrderReq
	ConfirmOrderResp                  = omsclient.ConfirmOrderResp
	DeleteCartItemReq                 = omsclient.DeleteCartItemReq
	DeleteCompanyAddressReq           = omsclient.DeleteCompanyAddressReq
	DeleteCompanyAddressResp          = omsclient.DeleteCompanyAddressResp
	DeleteOrderDeliveryReq            = omsclient.DeleteOrderDeliveryReq
	DeleteOrderDeliveryResp           = omsclient.DeleteOrderDeliveryResp
	DeleteOrderReq                    = omsclient.DeleteOrderReq
	DeleteOrderResp                   = omsclient.DeleteOrderResp
	DeleteOrderReturnReasonReq        = omsclient.DeleteOrderReturnReasonReq
	DeleteOrderReturnReasonResp       = omsclient.DeleteOrderReturnReasonResp
	DeleteOrderReturnReq              = omsclient.DeleteOrderReturnReq
	DeleteOrderSettingReq             = omsclient.DeleteOrderSettingReq
	DeleteOrderSettingResp            = omsclient.DeleteOrderSettingResp
	DeliveryReq                       = omsclient.DeliveryReq
	DeliveryResp                      = omsclient.DeliveryResp
	OrderDeliveryListData             = omsclient.OrderDeliveryListData
	OrderItemData                     = omsclient.OrderItemData
	OrderListData                     = omsclient.OrderListData
	OrderOperationLogData             = omsclient.OrderOperationLogData
	OrderOptLogData                   = omsclient.OrderOptLogData
	OrderPaymentData                  = omsclient.OrderPaymentData
	OrderPaymentReq                   = omsclient.OrderPaymentReq
	OrderPaymentResp                  = omsclient.OrderPaymentResp
	OrderReturnData                   = omsclient.OrderReturnData
	OrderReturnItemData               = omsclient.OrderReturnItemData
	OrderReturnReasonListData         = omsclient.OrderReturnReasonListData
	OrderReturnReq                    = omsclient.OrderReturnReq
	OrderReturnResp                   = omsclient.OrderReturnResp
	OrderSettingListData              = omsclient.OrderSettingListData
	QueryCartItemDetailReq            = omsclient.QueryCartItemDetailReq
	QueryCartItemListReq              = omsclient.QueryCartItemListReq
	QueryCartItemListResp             = omsclient.QueryCartItemListResp
	QueryCompanyAddressDetailReq      = omsclient.QueryCompanyAddressDetailReq
	QueryCompanyAddressDetailResp     = omsclient.QueryCompanyAddressDetailResp
	QueryCompanyAddressListReq        = omsclient.QueryCompanyAddressListReq
	QueryCompanyAddressListResp       = omsclient.QueryCompanyAddressListResp
	QueryDefaultSettingReq            = omsclient.QueryDefaultSettingReq
	QueryOrderDeliveryDetailReq       = omsclient.QueryOrderDeliveryDetailReq
	QueryOrderDeliveryDetailResp      = omsclient.QueryOrderDeliveryDetailResp
	QueryOrderDeliveryListReq         = omsclient.QueryOrderDeliveryListReq
	QueryOrderDeliveryListResp        = omsclient.QueryOrderDeliveryListResp
	QueryOrderDetailReq               = omsclient.QueryOrderDetailReq
	QueryOrderDetailResp              = omsclient.QueryOrderDetailResp
	QueryOrderListReq                 = omsclient.QueryOrderListReq
	QueryOrderListResp                = omsclient.QueryOrderListResp
	QueryOrderOperationLogDetailReq   = omsclient.QueryOrderOperationLogDetailReq
	QueryOrderOperationLogListReq     = omsclient.QueryOrderOperationLogListReq
	QueryOrderOperationLogListResp    = omsclient.QueryOrderOperationLogListResp
	QueryOrderPaymentDetailReq        = omsclient.QueryOrderPaymentDetailReq
	QueryOrderPaymentListReq          = omsclient.QueryOrderPaymentListReq
	QueryOrderPaymentListResp         = omsclient.QueryOrderPaymentListResp
	QueryOrderReturnDetailReq         = omsclient.QueryOrderReturnDetailReq
	QueryOrderReturnListReq           = omsclient.QueryOrderReturnListReq
	QueryOrderReturnListResp          = omsclient.QueryOrderReturnListResp
	QueryOrderReturnReasonDetailReq   = omsclient.QueryOrderReturnReasonDetailReq
	QueryOrderReturnReasonDetailResp  = omsclient.QueryOrderReturnReasonDetailResp
	QueryOrderReturnReasonListReq     = omsclient.QueryOrderReturnReasonListReq
	QueryOrderReturnReasonListResp    = omsclient.QueryOrderReturnReasonListResp
	QueryOrderSettingDetailReq        = omsclient.QueryOrderSettingDetailReq
	QueryOrderSettingDetailResp       = omsclient.QueryOrderSettingDetailResp
	QueryOrderSettingListReq          = omsclient.QueryOrderSettingListReq
	QueryOrderSettingListResp         = omsclient.QueryOrderSettingListResp
	QueryTimeOutOrderListReq          = omsclient.QueryTimeOutOrderListReq
	ReleaseSkuStockLockData           = omsclient.ReleaseSkuStockLockData
	UpdateCartItemQuantityReq         = omsclient.UpdateCartItemQuantityReq
	UpdateCartItemReq                 = omsclient.UpdateCartItemReq
	UpdateCompanyAddressReq           = omsclient.UpdateCompanyAddressReq
	UpdateCompanyAddressResp          = omsclient.UpdateCompanyAddressResp
	UpdateCompanyAddressStatusReq     = omsclient.UpdateCompanyAddressStatusReq
	UpdateCompanyAddressStatusResp    = omsclient.UpdateCompanyAddressStatusResp
	UpdateOrderDeliveryReq            = omsclient.UpdateOrderDeliveryReq
	UpdateOrderDeliveryResp           = omsclient.UpdateOrderDeliveryResp
	UpdateOrderPaymentStatusReq       = omsclient.UpdateOrderPaymentStatusReq
	UpdateOrderReq                    = omsclient.UpdateOrderReq
	UpdateOrderResp                   = omsclient.UpdateOrderResp
	UpdateOrderReturnReasonReq        = omsclient.UpdateOrderReturnReasonReq
	UpdateOrderReturnReasonResp       = omsclient.UpdateOrderReturnReasonResp
	UpdateOrderReturnReasonStatusReq  = omsclient.UpdateOrderReturnReasonStatusReq
	UpdateOrderReturnReasonStatusResp = omsclient.UpdateOrderReturnReasonStatusResp
	UpdateOrderReturnStatusReq        = omsclient.UpdateOrderReturnStatusReq
	UpdateOrderSettingReq             = omsclient.UpdateOrderSettingReq
	UpdateOrderSettingResp            = omsclient.UpdateOrderSettingResp
	UpdateOrderSettingStatusReq       = omsclient.UpdateOrderSettingStatusReq
	UpdateOrderSettingStatusResp      = omsclient.UpdateOrderSettingStatusResp
	UpdateOrderStatusReq              = omsclient.UpdateOrderStatusReq
	UpdateOrderStatusResp             = omsclient.UpdateOrderStatusResp
	UpdateReceiverInfoResp            = omsclient.UpdateReceiverInfoResp

	OrderReturnReasonService interface {
		// 添加退货原因
		AddOrderReturnReason(ctx context.Context, in *AddOrderReturnReasonReq, opts ...grpc.CallOption) (*AddOrderReturnReasonResp, error)
		// 删除退货原因
		DeleteOrderReturnReason(ctx context.Context, in *DeleteOrderReturnReasonReq, opts ...grpc.CallOption) (*DeleteOrderReturnReasonResp, error)
		// 更新退货原因
		UpdateOrderReturnReason(ctx context.Context, in *UpdateOrderReturnReasonReq, opts ...grpc.CallOption) (*UpdateOrderReturnReasonResp, error)
		// 更新退货原因状态
		UpdateOrderReturnReasonStatus(ctx context.Context, in *UpdateOrderReturnReasonStatusReq, opts ...grpc.CallOption) (*UpdateOrderReturnReasonStatusResp, error)
		// 查询退货原因详情
		QueryOrderReturnReasonDetail(ctx context.Context, in *QueryOrderReturnReasonDetailReq, opts ...grpc.CallOption) (*QueryOrderReturnReasonDetailResp, error)
		// 查询退货原因列表
		QueryOrderReturnReasonList(ctx context.Context, in *QueryOrderReturnReasonListReq, opts ...grpc.CallOption) (*QueryOrderReturnReasonListResp, error)
	}

	defaultOrderReturnReasonService struct {
		cli zrpc.Client
	}
)

func NewOrderReturnReasonService(cli zrpc.Client) OrderReturnReasonService {
	return &defaultOrderReturnReasonService{
		cli: cli,
	}
}

// 添加退货原因
func (m *defaultOrderReturnReasonService) AddOrderReturnReason(ctx context.Context, in *AddOrderReturnReasonReq, opts ...grpc.CallOption) (*AddOrderReturnReasonResp, error) {
	client := omsclient.NewOrderReturnReasonServiceClient(m.cli.Conn())
	return client.AddOrderReturnReason(ctx, in, opts...)
}

// 删除退货原因
func (m *defaultOrderReturnReasonService) DeleteOrderReturnReason(ctx context.Context, in *DeleteOrderReturnReasonReq, opts ...grpc.CallOption) (*DeleteOrderReturnReasonResp, error) {
	client := omsclient.NewOrderReturnReasonServiceClient(m.cli.Conn())
	return client.DeleteOrderReturnReason(ctx, in, opts...)
}

// 更新退货原因
func (m *defaultOrderReturnReasonService) UpdateOrderReturnReason(ctx context.Context, in *UpdateOrderReturnReasonReq, opts ...grpc.CallOption) (*UpdateOrderReturnReasonResp, error) {
	client := omsclient.NewOrderReturnReasonServiceClient(m.cli.Conn())
	return client.UpdateOrderReturnReason(ctx, in, opts...)
}

// 更新退货原因状态
func (m *defaultOrderReturnReasonService) UpdateOrderReturnReasonStatus(ctx context.Context, in *UpdateOrderReturnReasonStatusReq, opts ...grpc.CallOption) (*UpdateOrderReturnReasonStatusResp, error) {
	client := omsclient.NewOrderReturnReasonServiceClient(m.cli.Conn())
	return client.UpdateOrderReturnReasonStatus(ctx, in, opts...)
}

// 查询退货原因详情
func (m *defaultOrderReturnReasonService) QueryOrderReturnReasonDetail(ctx context.Context, in *QueryOrderReturnReasonDetailReq, opts ...grpc.CallOption) (*QueryOrderReturnReasonDetailResp, error) {
	client := omsclient.NewOrderReturnReasonServiceClient(m.cli.Conn())
	return client.QueryOrderReturnReasonDetail(ctx, in, opts...)
}

// 查询退货原因列表
func (m *defaultOrderReturnReasonService) QueryOrderReturnReasonList(ctx context.Context, in *QueryOrderReturnReasonListReq, opts ...grpc.CallOption) (*QueryOrderReturnReasonListResp, error) {
	client := omsclient.NewOrderReturnReasonServiceClient(m.cli.Conn())
	return client.QueryOrderReturnReasonList(ctx, in, opts...)
}
