###用户登录
POST {{host}}/api/sys/user/login
Content-Type: application/json

{
  "account": "admin",
  "password": "123456"
}
> {%
    client.global.set("token", response.body.data.token);
%}

### 添加字典数据
POST {{host}}/api/sys/dictItem/addDictItem
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "dictSort": 2,
  "dictLabel": "公告1",
  "dictValue": "21",
  "dictType": "sys_notice_type",
  "cssClass": "1",
  "listClass": "1",
  "isDefault": "N",
  "status": 1,
  "remark": "公告"
}
### 删除字典数据
GET {{host}}/api/sys/dictItem/deleteDictItem?ids=6
Authorization: Bearer {{token}}


### 修改字典数据
POST {{host}}/api/sys/dictItem/updateDictItem
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id": 6,
  "dictSort": 2,
  "dictLabel": "公告11",
  "dictValue": "221",
  "dictType": "sys_notice_type",
  "cssClass": "1",
  "listClass": "1",
  "isDefault": "N",
  "status": 1,
  "remark": "公告",
  "createBy": "admin",
  "createTime": "2025-03-31 14:23:57",
  "updateBy": "",
  "updateTime": ""
}

### 修改字典数据状态
POST {{host}}/api/sys/dictItem/updateDictItemStatus
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "ids": [6],
  "status": 1
}

### 查询字典数据详情
GET {{host}}/api/sys/dictItem/queryDictItemDetail?id=6
Authorization: Bearer {{token}}


### 查询字典数据列表
GET {{host}}/api/sys/dictItem/queryDictItemList?dictType
Authorization: Bearer {{token}}
