###用户登录
POST {{host}}/api/sys/user/login
Content-Type: application/json

{
  "userName": "admin",
  "password": "123456"
}
> {% client.global.set("token", response.body.token); %}

### 获取个人信息
GET {{host}}/api/sys/user/info
Authorization: Bearer {{token}}

### 用户列表
POST {{host}}/api/sys/user/list
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "current": 1,
  "pageSize": 10
}