// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: sms.proto

package server

import (
	"context"

	"github.com/feihua/zero-admin/rpc/sms/internal/logic/homeadvertiseservice"
	"github.com/feihua/zero-admin/rpc/sms/internal/svc"
	"github.com/feihua/zero-admin/rpc/sms/smsclient"
)

type HomeAdvertiseServiceServer struct {
	svcCtx *svc.ServiceContext
	smsclient.UnimplementedHomeAdvertiseServiceServer
}

func NewHomeAdvertiseServiceServer(svcCtx *svc.ServiceContext) *HomeAdvertiseServiceServer {
	return &HomeAdvertiseServiceServer{
		svcCtx: svcCtx,
	}
}

// 添加首页轮播广告
func (s *HomeAdvertiseServiceServer) AddHomeAdvertise(ctx context.Context, in *smsclient.AddHomeAdvertiseReq) (*smsclient.AddHomeAdvertiseResp, error) {
	l := homeadvertiseservicelogic.NewAddHomeAdvertiseLogic(ctx, s.svcCtx)
	return l.AddHomeAdvertise(in)
}

// 删除首页轮播广告
func (s *HomeAdvertiseServiceServer) DeleteHomeAdvertise(ctx context.Context, in *smsclient.DeleteHomeAdvertiseReq) (*smsclient.DeleteHomeAdvertiseResp, error) {
	l := homeadvertiseservicelogic.NewDeleteHomeAdvertiseLogic(ctx, s.svcCtx)
	return l.DeleteHomeAdvertise(in)
}

// 更新首页轮播广告
func (s *HomeAdvertiseServiceServer) UpdateHomeAdvertise(ctx context.Context, in *smsclient.UpdateHomeAdvertiseReq) (*smsclient.UpdateHomeAdvertiseResp, error) {
	l := homeadvertiseservicelogic.NewUpdateHomeAdvertiseLogic(ctx, s.svcCtx)
	return l.UpdateHomeAdvertise(in)
}

// 更新首页轮播广告状态
func (s *HomeAdvertiseServiceServer) UpdateHomeAdvertiseStatus(ctx context.Context, in *smsclient.UpdateHomeAdvertiseStatusReq) (*smsclient.UpdateHomeAdvertiseStatusResp, error) {
	l := homeadvertiseservicelogic.NewUpdateHomeAdvertiseStatusLogic(ctx, s.svcCtx)
	return l.UpdateHomeAdvertiseStatus(in)
}

// 查询首页轮播广告详情
func (s *HomeAdvertiseServiceServer) QueryHomeAdvertiseDetail(ctx context.Context, in *smsclient.QueryHomeAdvertiseDetailReq) (*smsclient.QueryHomeAdvertiseDetailResp, error) {
	l := homeadvertiseservicelogic.NewQueryHomeAdvertiseDetailLogic(ctx, s.svcCtx)
	return l.QueryHomeAdvertiseDetail(in)
}

// 查询首页轮播广告列表
func (s *HomeAdvertiseServiceServer) QueryHomeAdvertiseList(ctx context.Context, in *smsclient.QueryHomeAdvertiseListReq) (*smsclient.QueryHomeAdvertiseListResp, error) {
	l := homeadvertiseservicelogic.NewQueryHomeAdvertiseListLogic(ctx, s.svcCtx)
	return l.QueryHomeAdvertiseList(in)
}
