drop table if exists sys_menu;
create table sys_menu
(
    id             bigint auto_increment comment '菜单id'
        primary key,
    menu_name           varchar(50)                         not null comment '菜单名称',
    parent_id      bigint                              not null comment '父菜单ID，一级菜单为0',
    menu_path            varchar(200)                        default ''                not null comment '前端路由',
    menu_perms          varchar(500)                        default ''                not null comment '权限标识',
    menu_type           int                                 not null comment '类型 0：目录,1：菜单,2：按钮,3：外链',
    menu_icon           varchar(50)                         default ''                not null comment '菜单图标',
    menu_sort   tinyint      default 0                 not null comment '菜单排序',
    create_by      varchar(50)                         not null comment '创建者',
    create_time    timestamp default CURRENT_TIMESTAMP not null comment '创建时间',
    update_by      varchar(50)                         default ''                not null comment '更新者',
    update_time datetime   null on update CURRENT_TIMESTAMP comment '更新时间',
    menu_status tinyint default 1                              not null comment '菜单状态',
    is_deleted    tinyint      default 1                 not null comment '是否删除  0：否  1：是',
    is_visible    tinyint      default 1                 not null comment '是否可见  0：否  1：是',
    remark      varchar(255) default ''                not null comment '备注信息',
    vue_path       varchar(64)                         default ''                not null comment 'vue系统的path',
    vue_component  varchar(64)                         default ''                not null comment 'vue的页面',
    vue_icon       varchar(64)                         default ''                not null comment 'vue的图标',
    vue_redirect   varchar(64)                         default ''                not null comment 'vue的路由重定向',
    background_url varchar(256)                        default ''                not null comment '接口地址'
)
    comment '菜单信息表';


INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (1, '欢迎', 0, '/welcome', '', 0, 'SmileOutlined', 1, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', 'HomeFilled', '', '');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (2, '系统管理', 0, '/system', '', 0, 'SettingOutlined', 2, 'liufeihua', current_time, 'liufeihua', current_time, 1, '/sys', 'Layout', 'Setting', '/sys/userList', '');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (3, '用户列表', 2, '/system/user/list', '', 1, '', 1, 'liufeihua', current_time, 'liufeihua', current_time, 1, 'userList', 'system/user/index', 'el-icon-user', '', '/api/sys/user/queryUserList,/api/sys/user/queryUserDetail');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (4, '角色列表', 2, '/system/role/list', '', 1, '', 2, 'liufeihua', current_time, 'liufeihua', current_time, 1, 'roleList', 'system/role/index', 'el-icon-female', '', '/api/sys/role/queryRoleList');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (5, '菜单列表', 2, '/system/menu/list', '', 1, '', 3, 'liufeihua', current_time, 'liufeihua', current_time, 1, 'resourcesList', 'system/resource/index', 'el-icon-postcard', '', '/api/sys/menu/queryMenuList');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (6, '部门管理', 2, '/system/dept/list', '', 1, '', 4, 'liufeihua', current_time, 'liufeihua', current_time, 1, 'deptList', 'system/dept/index', 'el-icon-bangzhu', '', '/api/sys/dept/queryDeptList');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (7, '字典管理', 2, '/system/dict/list', '', 1, '', 5, 'liufeihua', current_time, 'liufeihua', current_time, 1, 'dictList', 'system/dict/index', 'el-icon-delete-location', '', '/api/sys/dictType/queryDictTypeList');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (8, '日志管理', 0, '/log', '', 0, 'DeleteOutlined', 3, 'liufeihua', current_time, 'liufeihua', current_time, 1, '/log', 'Layout', 'Delete', '/log/loginLogList', '');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (9, '登录日志', 8, '/log/loginLog/list', '', 1, '', 3, 'liufeihua', current_time, 'liufeihua', current_time, 1, 'loginLogList', 'log/loginlog/index', 'el-icon-remove-outline', '', '/api/sys/log/queryLoginLogList');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (10, '操作日志', 8, '/log/sysLog/list', '', 1, '', 3, 'liufeihua', current_time, 'liufeihua', current_time, 1, 'sysLogList', 'log/syslog/index', 'el-icon-camera', '', '/api/sys/log/queryOperateLogList');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (11, '会员管理', 0, '/ums', '', 0, 'FrownOutlined', 3, 'liufeihua', current_time, 'liufeihua', current_time, 1, '/ums', 'Layout', 'Expand', '/ums/memberList', '');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (12, '会员列表', 11, '/ums/member/list', '', 1, '', 3, 'liufeihua', current_time, 'liufeihua', current_time, 1, 'memberList', 'ums/member/index', 'el-icon-camera', '', '/api/ums/member/queryMemberList');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (13, '会员等级', 11, '/ums/memberLevel/list', '', 1, '', 3, 'liufeihua', current_time, 'liufeihua', current_time, 1, 'memberLevelList', 'ums/member_level/index', 'el-icon-remove-outline', '', '/api/ums/level/queryMemberLevelList');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (14, '会员地址', 12, '', '', 2, '', 3, 'liufeihua', current_time, 'liufeihua', current_time, 1, 'memberAddressList', 'ums/member_address/index', 'el-icon-remove-outline', '', '/api/ums/address/queryMemberAddressList');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (15, '登录记录', 12, '', '', 2, '', 3, 'liufeihua', current_time, 'liufeihua', current_time, 1, 'memberLoginLogList', 'ums/member_login_log/index', 'el-icon-remove-outline', '', '/api/ums/queryMemberLoginLogList,/api/sys/log/queryStatisticsLoginLog');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (16, '商品管理', 0, '/pms', '', 0, 'GiftOutlined', 3, 'liufeihua', current_time, 'liufeihua', current_time, 1, '/pms', 'Layout', 'Coffee', '/pms/productList', '');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (17, '商品分类', 16, '/pms/productCategory/list', '', 1, '', 3, 'liufeihua', current_time, 'liufeihua', current_time, 1, 'productCategoryList', 'pms/product_category/index', 'el-icon-remove-outline', '', '/api/pms/category/queryProductCategoryList');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (18, '商品品牌', 16, '/pms/productBrand/list', '', 1, '', 3, 'liufeihua', current_time, 'liufeihua', current_time, 1, 'productBrandList', 'pms/product_brand/index', 'el-icon-remove-outline', '', '/api/pms/brand/queryProductBrandList');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (19, '商品列表', 16, '/pms/product/list', '', 1, '', 3, 'liufeihua', current_time, 'liufeihua', current_time, 1, 'productList', 'pms/product/index', 'el-icon-camera', '', '/api/pms/product/queryProductList');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (20, '订单管理', 0, '/oms', '', 0, 'DollarCircleOutlined', 3, 'liufeihua', current_time, 'liufeihua', current_time, 1, '/oms', 'Layout', 'ShoppingCart', '/oms/orderList', '');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (21, '订单设置', 20, '/oms/orderSetting/list', '', 1, '', 3, 'liufeihua', current_time, 'liufeihua', current_time, 1, 'orderSetting', 'oms/order_setting/index', 'el-icon-remove-outline', '', '/api/oms/setting/queryOrderSettingList');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (22, '退货列表', 20, '/oms/orderReturnApply/list', '', 1, '', 3, 'liufeihua', current_time, 'liufeihua', current_time, 1, 'orderReturnApplyList', 'oms/order_return_apply/index', 'el-icon-remove-outline', '', '/api/oms/returnApply/queryOrderReturnApplyList');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (23, '退货原因', 20, '/oms/orderReturnReason/list', '', 1, '', 3, 'liufeihua', current_time, 'liufeihua', current_time, 1, 'orderReturnReasonList', 'oms/order_return_reason/index', 'el-icon-remove-outline', '', '/api/oms/returnReason/queryOrderReturnReasonList');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (24, '订单列表', 20, '/oms/order/list', '', 1, '', 3, 'liufeihua', current_time, 'liufeihua', current_time, 1, 'orderList', 'oms/order/index', 'el-icon-camera', '', '/api/oms/order/queryOrderList');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (25, '营销管理', 0, '/sms', '', 0, 'AlertOutlined', 3, 'liufeihua', current_time, 'liufeihua', current_time, 1, '/sms', 'Layout', 'Postcard', '/sms/flashPromotionList', '');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (26, '秒杀活动', 25, '/sms/flashPromotion/list', '', 1, '', 3, 'liufeihua', current_time, 'liufeihua', current_time, 1, 'flashPromotionList', 'sms/flash_promotion/index', 'el-icon-camera', '', '/api/sms/flashPromotion/queryFlashPromotionList');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (27, '品牌推荐', 25, '/sms/homeBrand/list', '', 1, '', 3, 'liufeihua', current_time, 'liufeihua', current_time, 1, 'homeBrandList', 'sms/home_brand/index', 'el-icon-remove-outline', '', '/api/sms/homeBrand/queryHomeBrandList');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (28, '新品推荐', 25, '/sms/homeNewProduct/list', '', 1, '', 3, 'liufeihua', current_time, 'liufeihua', current_time, 1, 'homeNewProductList', 'sms/home_new_product/index', 'el-icon-remove-outline', '', '/api/sms/homeNewProduct/queryHomeNewProductList');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (29, '人气推荐', 25, '/sms/homeRecommendProduct/list', '', 1, '', 3, 'liufeihua', current_time, 'liufeihua', current_time, 1, 'homeRecommendProductList', 'sms/home_recommend_product/index', 'el-icon-remove-outline', '', '/api/sms/homeRecommendProduct/queryHomeRecommendProductList');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (30, '专题推荐', 25, '/sms/homeRecommendSubject/list', '', 1, '', 3, 'liufeihua', current_time, 'liufeihua', current_time, 1, 'homeRecommendSubjectList', 'sms/home_recommend_subject/index', 'el-icon-remove-outline', '', '/api/sms/homeRecommendSubject/queryHomeRecommendSubjectList');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (31, '广告列表', 25, '/sms/homeAdvertise/list', '', 1, '', 3, 'liufeihua', current_time, 'liufeihua', current_time, 1, 'homeAdvertiseList', 'sms/home_advertise/index', 'el-icon-remove-outline', '', '/api/sms/homeAdvertise/queryHomeAdvertiseList');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (32, '优惠券', 25, '/sms/coupon/list', '', 1, '', 3, 'liufeihua', current_time, 'liufeihua', current_time, 1, 'couponList', 'sms/coupon/index', 'el-icon-remove-outline', '', '/api/sms/coupon/queryCouponList,/api/sms/coupon/queryCouponDetail');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (33, '岗位管理', 2, '/system/post/list', '', 1, '', 6, 'liufeihua', current_time, 'liufeihua', current_time, 1, 'jobList', 'system/post/index', 'el-icon-delete-location', '', '/api/sys/post/queryPostList');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (34, '新增用户', 3, '', '', 2, '', 1, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/sys/user/addUser,/api/sys/user/queryDeptAndPostList');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (35, '更新用户', 3, '', '', 2, '', 2, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/sys/user/updateUser,/api/sys/user/queryDeptAndPostList');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (36, '删除用户', 3, '', '', 2, '', 3, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/sys/user/deleteUser');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (37, '新增角色', 4, '', '', 2, '', 1, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/sys/role/addRole');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (38, '更新角色', 4, '', '', 2, '', 2, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/sys/role/updateRole');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (39, '删除角色', 4, '', '', 2, '', 3, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/sys/role/deleteRole');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (40, '根据角色查询菜单', 4, '', '', 2, '', 4, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/sys/role/queryRoleMenuList');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (41, '根据角色更新菜单', 4, '', '', 2, '', 5, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/sys/role/updateRoleMenuList');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (42, '新增菜单', 5, '', '', 2, '', 1, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/sys/menu/addMenu');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (43, '更新菜单', 5, '', '', 2, '', 2, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/sys/menu/updateMenu');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (44, '删除菜单', 5, '', '', 2, '', 3, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/sys/menu/deleteMenu');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (45, '新增机构', 6, '', '', 2, '', 1, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/sys/dept/addDept');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (46, '更新机构', 6, '', '', 2, '', 2, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/sys/dept/updateDept');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (47, '删除机构', 6, '', '', 2, '', 3, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/sys/dept/deleteDept');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (48, '新增字典', 7, '', '', 2, '', 1, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/sys/dictType/addDictType');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (49, '更新字典', 7, '', '', 2, '', 2, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/sys/dictType/updateDictType');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (50, '删除字典', 7, '', '', 2, '', 3, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/sys/dictType/deleteDictType');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (51, '登录日志', 9, '', '', 2, '', 1, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/sys/log/deleteLoginLog');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (52, '操作日志', 10, '', '', 2, '', 1, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/sys/log/deleteOperateLog');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (53, '新增会员', 12, '', '', 2, '', 1, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/ums/member/addMember');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (54, '更新会员', 12, '', '', 2, '', 2, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/ums/member/updateMember');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (55, '删除会员', 12, '', '', 2, '', 3, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/ums/member/deleteMember');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (56, '新增会员等级', 13, '', '', 2, '', 1, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/ums/level/addMemberLevel');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (57, '更新会员等级', 13, '', '', 2, '', 2, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/ums/level/updateMemberLevel');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (58, '删除会员等级', 13, '', '', 2, '', 3, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/ums/level/deleteMemberLevel');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (59, '新增会员地址', 14, '', '', 2, '', 1, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/ums/address/add');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (60, '更新会员地址', 14, '', '', 2, '', 2, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/ums/address/update');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (61, '删除会员地址', 14, '', '', 2, '', 3, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/ums/address/delete');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (62, '删除登录记录', 15, '', '', 2, '', 3, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/ums/loginlog/delete');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (63, '新增商品类别', 17, '', '', 2, '', 1, 'liufeihua', '2023-12-01 16:28:32', 'liufeihua', current_time, 1, '', '', '', '', '/api/pms/category/addProductCategory');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (64, '更新商品类别', 17, '', '', 2, '', 2, 'liufeihua', '2023-12-01 16:28:32', 'liufeihua', current_time, 1, '', '', '', '', '/api/pms/category/updateProductCategory');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (65, '删除商品类别', 17, '', '', 2, '', 3, 'liufeihua', '2023-12-01 16:28:32', 'liufeihua', current_time, 1, '', '', '', '', '/api/pms/category/deleteProductCategory');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (66, '新增商品品牌', 18, '', '', 2, '', 1, 'liufeihua', '2023-12-01 16:28:32', 'liufeihua', current_time, 1, '', '', '', '', '/api/pms/brand/addProductBrand');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (67, '更新商品品牌', 18, '', '', 2, '', 2, 'liufeihua', '2023-12-01 16:28:32', 'liufeihua', current_time, 1, '', '', '', '', '/api/pms/brand/updateProductBrand');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (68, '删除商品品牌', 18, '', '', 2, '', 3, 'liufeihua', '2023-12-01 16:28:32', 'liufeihua', current_time, 1, '', '', '', '', '/api/pms/brand/deleteProductBrand');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (69, '新增商品', 19, '', '', 2, '', 1, 'liufeihua', '2023-12-01 16:28:32', 'liufeihua', current_time, 1, '', '', '', '', '/api/pms/product/add');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (70, '更新商品', 19, '', '', 2, '', 2, 'liufeihua', '2023-12-01 16:28:32', 'liufeihua', current_time, 1, '', '', '', '', '/api/pms/product/update');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (71, '删除商品', 19, '', '', 2, '', 3, 'liufeihua', '2023-12-01 16:28:32', 'liufeihua', current_time, 1, '', '', '', '', '/api/pms/product/delete');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (72, '新增订单设置', 21, '', '', 2, '', 1, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/oms/setting/addOrderSetting');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (73, '更新订单设置', 21, '', '', 2, '', 2, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/oms/setting/updateOrderSetting,/api/oms/setting/updateOrderSettingIsDefault,/api/oms/setting/updateOrderSettingStatus');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (74, '删除订单设置', 21, '', '', 2, '', 3, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/oms/setting/deleteOrderSetting');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (75, '新增退货', 22, '', '', 2, '', 1, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/oms/returnApply/addOrderReturnApply');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (76, '更新退货', 22, '', '', 2, '', 2, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/oms/returnApply/updateOrderReturnApply');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (77, '删除退货', 22, '', '', 2, '', 3, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/oms/returnApply/deleteOrderReturnApply');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (78, '新增退货原因', 23, '', '', 2, '', 1, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/oms/returnReason/addOrderReturnReason');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (79, '更新退货原因', 23, '', '', 2, '', 2, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/oms/returnReason/updateOrderReturnReason,/api/oms/returnReason/updateOrderReturnReasonStatus');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (80, '删除退货原因', 23, '', '', 2, '', 3, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/oms/returnReason/deleteOrderReturnReason');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (81, '新增订单', 24, '', '', 2, '', 1, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/oms/order/add');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (82, '更新订单', 24, '', '', 2, '', 2, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/oms/order/update');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (83, '删除订单', 24, '', '', 2, '', 3, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/oms/order/delete');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (84, '新增秒杀活动', 26, '', '', 2, '', 1, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/sms/flashPromotion/addFlashPromotion');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (85, '更新秒杀活动', 26, '', '', 2, '', 2, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/sms/flashPromotion/updateFlashPromotion,/api/sms/flashPromotion/updateFlashPromotionStatus');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (86, '删除秒杀活动', 26, '', '', 2, '', 3, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/sms/flashPromotion/deleteFlashPromotion');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (87, '新增品牌推荐', 27, '', '', 2, '', 1, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/sms/homeBrand/addHomeBrand');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (88, '修改推荐品牌排序', 27, '', '', 2, '', 2, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/sms/homeBrand/updateHomeBrandSort');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (89, '删除品牌推荐', 27, '', '', 2, '', 3, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/sms/homeBrand/deleteHomeBrand');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (90, '新增新品推荐', 28, '', '', 2, '', 1, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/sms/homeNewProduct/addHomeNewProduct');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (91, '更新新品推荐排序', 28, '', '', 2, '', 2, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/sms/homeNewProduct/updateNewProductSort');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (92, '删除新品推荐', 28, '', '', 2, '', 3, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/sms/homeNewProduct/deleteHomeNewProduct');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (93, '新增人气推荐', 29, '', '', 2, '', 1, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/sms/homeRecommendProduct/addHomeRecommendProduct');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (94, '更新人气推荐排序', 29, '', '', 2, '', 2, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/sms/homeRecommendProduct/updateRecommendProductSort');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (95, '删除人气推荐', 29, '', '', 2, '', 3, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/sms/homeRecommendProduct/deleteHomeRecommendProduct');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (96, '新增广告', 31, '', '', 2, '', 1, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/sms/homeAdvertise/addHomeAdvertise');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (97, '更新广告', 31, '', '', 2, '', 2, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/sms/homeAdvertise/updateHomeAdvertise');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (98, '删除广告', 31, '', '', 2, '', 3, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/sms/homeAdvertise/deleteHomeAdvertise');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (99, '新增优惠券', 32, '', '', 2, '', 1, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/sms/coupon/addCoupon');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (100, '更新优惠券', 32, '', '', 2, '', 2, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/sms/coupon/updateCoupon');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (101, '删除优惠券', 32, '', '', 2, '', 3, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/sms/coupon/deleteCoupon');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (102, '新增职位', 33, '', '', 2, '', 1, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/sys/post/addPost');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (103, '更新职位', 33, '', '', 2, '', 2, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/sys/post/updatePost,/api/sys/post/updatePostStatus');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (104, '删除职位', 33, '', '', 2, '', 3, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/sys/post/deletePost');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (105, '新增专题推荐', 30, '', '', 2, '', 1, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/sms/homeRecommendSubject/addHomeRecommendSubject');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (106, '更新专题推荐排序', 30, '', '', 2, '', 2, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/sms/homeRecommendSubject/updateRecommendSubjectSort');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (107, '删除专题推荐', 30, '', '', 2, '', 3, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/sms/homeRecommendSubject/deleteHomeRecommendSubject');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (108, '专题列表', 30, '', '', 2, '', 3, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/cms/subject/querySubjectList');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (109, '属性选项', 16, '/pms/attribute/list', '', 1, '', 3, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/pms/attribute/queryAttributeList');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (110, '新增属性选项', 109, '', '', 2, '', 1, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/pms/attribute/addAttribute');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (111, '更新属性选项', 109, '', '', 2, '', 2, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/pms/attribute/update');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (112, '删除属性选项', 109, '', '', 2, '', 3, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/pms/attribute/deleteAttribute');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (113, '属性分类', 16, '/pms/attributeCategory/list', '', 1, '', 3, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/pms/attributeCategory/queryCategoryWithAttrList');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (114, '新增属性分类', 113, '', '', 2, '', 1, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/pms/attributeCategory/addAttributeCategory');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (115, '更新属性分类', 113, '', '', 2, '', 2, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/pms/attributeCategory/updateAttributeCategory');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (116, '删除属性分类', 113, '', '', 2, '', 3, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/pms/attributeCategory/deleteAttributeCategory');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (117, '地址管理', 20, '/oms/companyAddress/list', '', 1, '', 3, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/oms/companyAddress/queryCompanyAddressList');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url)VALUES (118, '查询商品优选', 19, '', '', 2, '', 3, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '','', '/api/cms/prefrenceArea/queryPreferredAreaList');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (119, '上传文件', 3, '', '', 2, '', 4, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/sys/upload');

INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (120, '登陆日志统计', 9, '', '', 2, '', 1, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/sys/log/statisticsLoginLog');

INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (121, '添加公司地址', 117, '', '', 2, '', 3, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/oms/companyAddress/addCompanyAddress');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (122, '删除查询公司地址', 117, '', '', 2, '', 3, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/oms/companyAddress/deleteCompanyAddress');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (123, '修改公司地址', 117, '', '', 2, '', 3, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/oms/companyAddress/updateCompanyAddress,/api/oms/companyAddress/updateCompanyAddressReceiveStatus,/api/oms/companyAddress/updateCompanyAddressSendStatus');

INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (124, '批量修改推荐品牌状态', 27, '', '', 2, '', 2, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/sms/homeBrand/updateHomeBrandStatus');

INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (125, '批量更新厂家制造商状态', 18, '', '', 2, '', 3, 'liufeihua', '2023-12-01 16:28:32', 'liufeihua', current_time, 1, '', '', '', '', '/api/pms/brand/updateBrandFactoryStatus');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (126, '批量更新显示状态', 18, '', '', 2, '', 3, 'liufeihua', '2023-12-01 16:28:32', 'liufeihua', current_time, 1, '', '', '', '', '/api/pms/brand/updateBrandShowStatus');

INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (127, '更新首页轮播广告状态', 31, '', '', 2, '', 3, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/sms/homeAdvertise/updateHomeAdvertiseStatus');

INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (128, '批量修改推荐状态', 28, '', '', 2, '', 2, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/sms/homeNewProduct/updateNewProductStatus');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (129, '批量人气推荐状态', 29, '', '', 2, '', 2, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/sms/homeRecommendProduct/updateRecommendProductStatus');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (130, '批量修改推荐状态', 30, '', '', 2, '', 2, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/sms/homeRecommendSubject/updateRecommendSubjectStatus');

INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (131, '优惠券领取', 32, '', '', 2, '', 3, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/sms/couponHistory/queryCouponHistoryList');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (132, '批量更新退货原因状态', 23, '', '', 2, '', 2, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/oms/returnReason/updateReturnReasonStatus');

INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url, is_visible) VALUES (133, '限时购场次', 25, '/sms/flashPromotionSession/list', '', 1, '', 3, 'liufeihua', current_time, 'liufeihua', current_time, 1, 'flashPromotionList', 'sms/flash_promotion/index', 'el-icon-camera', '', '/api/sms/flashPromotionSession/queryFlashPromotionSessionList', 0);
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (134, '新增限时购场次', 133, '', '', 2, '', 1, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/sms/flashPromotionSession/addFlashPromotionSession');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (135, '更新限时购场次', 133, '', '', 2, '', 2, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/sms/flashPromotionSession/updateFlashPromotionSession,/api/sms/flashPromotionSession/updateSessionStatus');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (136, '删除限时购场次', 133, '', '', 2, '', 3, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/sms/flashPromotionSession/deleteFlashPromotionSession');

INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (137, '分页查询场次关联及商品', 26, '', '', 2, '', 1, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/sms/flashPromotionProductRelation/queryFlashPromotionProductRelationList');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (138, '添加限时购和商品关系', 26, '', '', 2, '', 1, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/sms/flashPromotionProductRelation/addFlashPromotionProductRelation');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (139, '删除限时购和商品关系', 26, '', '', 2, '', 2, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/sms/flashPromotionProductRelation/deleteFlashPromotionProductRelation');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (140, '更新限时购和商品关系', 26, '', '', 2, '', 3, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/sms/flashPromotionProductRelation/updateFlashPromotionProductRelation');

INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (141, '查询商品详情', 19, '', '', 2, '', 3, 'liufeihua', '2023-12-01 16:28:32', 'liufeihua', current_time, 1, '', '', '', '', '/api/pms/product/queryProductDetail');


INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (142, '会员任务', 11, '/ums/memberTask/list', '', 1, '', 3, 'liufeihua', current_time, 'liufeihua', current_time, 1, 'memberLevelList', 'ums/member_level/index', 'el-icon-remove-outline', '', '/api/ums/task/queryMemberTaskList');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (143, '新增会员任务', 142, '', '', 2, '', 1, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/ums/task/addMemberTask');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (144, '更新会员任务', 142, '', '', 2, '', 2, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/ums/task/updateMemberTask,/api/ums/task/updateMemberTaskStatus');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (145, '删除会员任务', 142, '', '', 2, '', 3, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/ums/task/deleteMemberTask');

INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (146, '会员标签', 11, '/ums/memberTag/list', '', 1, '', 3, 'liufeihua', current_time, 'liufeihua', current_time, 1, 'memberLevelList', 'ums/member_level/index', 'el-icon-remove-outline', '', '/api/ums/tag/queryMemberTagList');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (147, '新增会员标签', 146, '', '', 2, '', 1, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/ums/tag/addMemberTag');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (148, '更新会员标签', 146, '', '', 2, '', 2, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/ums/tag/updateMemberTag,/api/ums/tag/updateMemberTagStatus');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (149, '删除会员标签', 146, '', '', 2, '', 3, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/ums/tag/deleteMemberTag');

INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (150, '统计信息', 11, '/ums/statistics/list', '', 1, '', 3, 'liufeihua', current_time, 'liufeihua', current_time, 1, 'memberLevelList', 'ums/member_level/index', 'el-icon-remove-outline', '', '/api/ums/statistics/queryMemberStatisticsInfoList,/api/ums/statistics/queryMemberStatisticsDetail');

INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (151, '会员成长规则', 11, '/ums/memberRule/list', '', 1, '', 3, 'liufeihua', current_time, 'liufeihua', current_time, 1, 'memberLevelList', 'ums/member_level/index', 'el-icon-remove-outline', '', '/api/ums/ruleSetting/queryMemberRuleSettingList');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (152, '新增会员成长规则', 151, '', '', 2, '', 1, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/ums/ruleSetting/addMemberRuleSetting');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (153, '更新会员成长规则', 151, '', '', 2, '', 2, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/ums/ruleSetting/updateMemberRuleSetting,/api/ums/ruleSetting/updateMemberRuleSettingStatus');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (154, '删除会员成长规则', 151, '', '', 2, '', 3, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/ums/ruleSetting/deleteMemberRuleSetting');


INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (155, '积分消费设置', 11, '/ums/integrationConsumeSetting/list', '', 1, '', 3, 'liufeihua', current_time, 'liufeihua', current_time, 1, 'memberLevelList', 'ums/member_level/index', 'el-icon-remove-outline', '', '/api/ums/integrationConsumeSetting/queryIntegrationConsumeSettingList');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (156, '新增积分消费设置', 155, '', '', 2, '', 1, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/ums/integrationConsumeSetting/addIntegrationConsumeSetting');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (157, '更新积分消费设置', 155, '', '', 2, '', 2, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/ums/integrationConsumeSetting/updateIntegrationConsumeSetting,/api/ums/integrationConsumeSetting/updateIntegrationConsumeSettingStatus');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (158, '删除积分消费设置', 155, '', '', 2, '', 3, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/ums/integrationConsumeSetting/deleteIntegrationConsumeSetting');


INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (159, '查询会员的登录日志', 12, '', '', 2, '', 3, 'liufeihua', current_time, 'liufeihua', current_time, 1, 'memberAddressList', 'ums/member_address/index', 'el-icon-remove-outline', '', '/api/ums/member/queryMemberLoginLogList');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (160, '查询会员成长值变化', 12, '', '', 2, '', 3, 'liufeihua', current_time, 'liufeihua', current_time, 1, 'memberAddressList', 'ums/member_address/index', 'el-icon-remove-outline', '', '/api/ums/member/queryGrowthChangeHistoryList');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (161, '查询会员积分变化', 12, '', '', 2, '', 3, 'liufeihua', current_time, 'liufeihua', current_time, 1, 'memberAddressList', 'ums/member_address/index', 'el-icon-remove-outline', '', '/api/ums/member/queryIntegrationChangeHistoryList');

INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (162, '查询用户角色关联', 3, '', '', 2, '', 4, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/sys/user/queryUserRoleList');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (163, '更新用户角色关联', 3, '', '', 2, '', 5, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/sys/user/updateUserRoleList');

INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url, is_visible) VALUES (164, '字典项', 2, '/sys/integrationConsumeSetting/list', '', 1, '', 3, 'liufeihua', current_time, 'liufeihua', current_time, 1, 'memberLevelList', 'ums/member_level/index', 'el-icon-remove-outline', '', '/api/sys/dictItem/queryDictItemList', 0);
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (165, '新增字典项', 164, '', '', 2, '', 1, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/sys/dictItem/addDictItem');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (166, '更新字典项', 164, '', '', 2, '', 2, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/sys/dictItem/updateDictItem');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (167, '删除字典项', 164, '', '', 2, '', 3, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/sys/dictItem/deleteDictItem');

INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (168, '查询角色的用户关联', 4, '', '', 2, '', 1, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/sys/role/queryRoleUserList');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (169, '更新角色的用户关联', 4, '', '', 2, '', 2, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/sys/role/updateRoleUserList');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (170, '取消授权', 4, '', '', 2, '', 3, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/sys/role/cancelAuthorization');

INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (171, '查询公司地址详情', 117, '', '', 2, '', 3, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/oms/companyAddress/queryCompanyAddressDetail');

INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (172, '查询部门详情', 6, '', '', 2, '', 1, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/sys/dept/queryDeptDetail');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (173, '修改部门状态', 6, '', '', 2, '', 1, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/sys/dept/updateDeptStatus');

INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (174, '查询字典详情', 7, '', '', 2, '', 1, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/sys/dictType/queryDictTypeDetail');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (175, '修改字典状态', 7, '', '', 2, '', 1, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/sys/dictType/updateDictTypeStatus');

INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (176, '查询字典数据详情', 164, '', '', 2, '', 1, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/sys/dictItem/queryDictItemDetail');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (177, '修改字典数据状态', 164, '', '', 2, '', 1, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/sys/dictItem/updateDictItemStatus');

INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (178, '查询登录日志详情', 51, '', '', 2, '', 1, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/sys/log/queryLoginLogDetail');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (179, '查询操作日志详情', 51, '', '', 2, '', 1, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/sys/log/queryOperateLogDetail');

INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (180, '查询岗位详情', 33, '', '', 2, '', 1, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/sys/post/queryPostDetail');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (181, '修改岗位状态', 33, '', '', 2, '', 1, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/sys/post/updatePostStatus');

INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (182, '查询角色详情', 4, '', '', 2, '', 1, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/sys/role/queryRoleDetail');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (183, '修改角色状态', 4, '', '', 2, '', 1, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/sys/role/updateRoleStatus');

INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (184, '查询用户详情', 3, '', '', 2, '', 2, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/sys/user/queryUserDetail');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (185, '更新用户状态', 3, '', '', 2, '', 2, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/sys/user/updateUserStatus');

INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (186, '查询菜单详情', 5, '', '', 2, '', 2, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/sys/menu/queryMenuDetail');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (187, '更新菜单状态', 5, '', '', 2, '', 2, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/sys/menu/updateMenuStatus');

INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (188, '查询会员等级详情', 13, '', '', 2, '', 3, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/ums/level/queryMemberLevelDetail');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (189, '更新会员等级状态', 13, '', '', 2, '', 3, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/ums/level/updateMemberLevelStatus');

INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (190, '查询会员详情', 12, '', '', 2, '', 3, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/ums/member/queryMemberDetail');
INSERT INTO sys_menu (id, menu_name, parent_id, menu_path, menu_perms, menu_type, menu_icon, menu_sort, create_by, create_time, update_by, update_time, is_deleted, vue_path, vue_component, vue_icon, vue_redirect, background_url) VALUES (191, '更新会员状态', 12, '', '', 2, '', 3, 'liufeihua', current_time, 'liufeihua', current_time, 1, '', '', '', '', '/api/ums/member/updateMemberStatus');


