// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1
// Source: ums.proto

package server

import (
	"context"

	"github.com/feihua/zero-admin/rpc/ums/internal/logic/membermembertagrelationservice"
	"github.com/feihua/zero-admin/rpc/ums/internal/svc"
	"github.com/feihua/zero-admin/rpc/ums/umsclient"
)

type MemberMemberTagRelationServiceServer struct {
	svcCtx *svc.ServiceContext
	umsclient.UnimplementedMemberMemberTagRelationServiceServer
}

func NewMemberMemberTagRelationServiceServer(svcCtx *svc.ServiceContext) *MemberMemberTagRelationServiceServer {
	return &MemberMemberTagRelationServiceServer{
		svcCtx: svcCtx,
	}
}

// 添加用户和标签关系表
func (s *MemberMemberTagRelationServiceServer) AddMemberMemberTagRelation(ctx context.Context, in *umsclient.AddMemberMemberTagRelationReq) (*umsclient.AddMemberMemberTagRelationResp, error) {
	l := membermembertagrelationservicelogic.NewAddMemberMemberTagRelationLogic(ctx, s.svcCtx)
	return l.AddMemberMemberTagRelation(in)
}

// 删除用户和标签关系表
func (s *MemberMemberTagRelationServiceServer) DeleteMemberMemberTagRelation(ctx context.Context, in *umsclient.DeleteMemberMemberTagRelationReq) (*umsclient.DeleteMemberMemberTagRelationResp, error) {
	l := membermembertagrelationservicelogic.NewDeleteMemberMemberTagRelationLogic(ctx, s.svcCtx)
	return l.DeleteMemberMemberTagRelation(in)
}

// 查询用户和标签关系表列表
func (s *MemberMemberTagRelationServiceServer) QueryMemberMemberTagRelationList(ctx context.Context, in *umsclient.QueryMemberMemberTagRelationListReq) (*umsclient.QueryMemberMemberTagRelationListResp, error) {
	l := membermembertagrelationservicelogic.NewQueryMemberMemberTagRelationListLogic(ctx, s.svcCtx)
	return l.QueryMemberMemberTagRelationList(in)
}
