apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-api
  namespace: zero-admin
  labels:
    app: consumer-api
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: consumer-api
  template:
    metadata:
      labels:
        app: consumer-api
    spec:
      serviceAccountName: koobe
      containers:
        - name: consumer-api
          image: consumer-api:0.0.1
          ports:
            - containerPort: 8087
          envFrom:
            - configMapRef:
                name: zero-admin-config

---
apiVersion: v1
kind: Service
metadata:
  name: consumer-api-svc
  namespace: zero-admin
  labels:
    app: consumer-api-svc
spec:
  ports:
    - port: 8087
      name: consumer-api
      targetPort: 8087
  selector:
    app: consumer-api
  type: NodePort
