apiVersion: apps/v1
kind: Deployment
metadata:
  name: oms-rpc
  namespace: zero-admin
  labels:
    app: oms-rpc
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: oms-rpc
  template:
    metadata:
      labels:
        app: oms-rpc
    spec:
      containers:
        - name: oms-rpc
          image: oms-rpc:0.0.1
          ports:
            - containerPort: 8083

---
apiVersion: v1
kind: Service
metadata:
  name: oms-rpc-svc
  namespace: zero-admin
  labels:
    app: oms-rpc-svc
spec:
  ports:
    - port: 8083
      name: oms-rpc
      targetPort: 8083
  selector:
    app: oms-rpc
