// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2

package handler

import (
	"net/http"

	brand "github.com/feihua/zero-admin/api/web/internal/handler/brand"
	cart "github.com/feihua/zero-admin/api/web/internal/handler/cart"
	category "github.com/feihua/zero-admin/api/web/internal/handler/category"
	home "github.com/feihua/zero-admin/api/web/internal/handler/home"
	memberaddress "github.com/feihua/zero-admin/api/web/internal/handler/member/address"
	membermember "github.com/feihua/zero-admin/api/web/internal/handler/member/member"
	product "github.com/feihua/zero-admin/api/web/internal/handler/product"
	"github.com/feihua/zero-admin/api/web/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/queryBrandList",
				Handler: brand.BrandListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/brand"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/addCart",
				Handler: cart.CartItemAddHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/clear",
				Handler: cart.CarItemClearHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/deleteCart",
				Handler: cart.CartItemDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/product",
				Handler: cart.CartProductHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/promotionList",
				Handler: cart.CarItemtListPromotionHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/queryCartList",
				Handler: cart.CarItemListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/updateAttr",
				Handler: cart.CartUpdateAttrHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/updateQuantity",
				Handler: cart.CartUpdateQuantityHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/cart"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/queryProductCateList",
				Handler: category.QueryProductCateListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/category"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/index",
				Handler: home.HomeIndexHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/home"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/addMemberAddress",
				Handler: memberaddress.AddMemberAddressHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/deleteMemberAddress",
				Handler: memberaddress.DeleteMemberAddressHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/queryMemberAddressDetail",
				Handler: memberaddress.QueryMemberAddressDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/queryMemberAddressList",
				Handler: memberaddress.QueryMemberAddressListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/updateMemberAddress",
				Handler: memberaddress.UpdateMemberAddressHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/updateMemberAddressStatus",
				Handler: memberaddress.UpdateMemberAddressStatusHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/member/address"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: membermember.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: membermember.RegisterHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/member"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/info",
				Handler: membermember.InfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/updateMember",
				Handler: membermember.UpdateMemberHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/updatePassword",
				Handler: membermember.UpdatePasswordHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/member"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/queryProduct",
				Handler: product.QueryProductHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/queryProductList",
				Handler: product.QueryProductListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/product"),
	)
}
