drop table if exists pms_product_spu;
CREATE TABLE `pms_product_spu` (
                               `id`              BIGINT          NOT NULL AUTO_INCREMENT,
                               `name`            VARCHAR(200)    NOT NULL COMMENT '商品名称',
                               `category_id`     BIGINT          NOT NULL COMMENT '商品分类ID',
                               `brand_id`        BIGINT          NOT NULL COMMENT '品牌ID',
                               `unit`            VARCHAR(20)     NOT NULL COMMENT '单位',
                               `weight`          DECIMAL(10,2)   NULL COMMENT '重量(kg)',
                               `keywords`        VARCHAR(255)    NULL COMMENT '关键词',
                               `brief`           VARCHAR(255)    NULL COMMENT '简介',
                               `description`     TEXT            NULL COMMENT '详细描述',
                               `album_pics`      VARCHAR(1000)   NULL COMMENT '画册图片，最多8张，以逗号分割',
                               `main_pic`        VARCHAR(255)    NOT NULL COMMENT '主图',
                               `price_range`     VARCHAR(100)    NULL COMMENT '价格区间',
                               `publish_status`  TINYINT(1)      NOT NULL DEFAULT 0 COMMENT '上架状态：0-下架，1-上架',
                               `sort`            INT             NOT NULL DEFAULT 0 COMMENT '排序',
                               `sales`           INT             NOT NULL DEFAULT 0 COMMENT '销量',
                               `create_time`     DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
                               `update_time`     DATETIME(3)     NULL ON UPDATE CURRENT_TIMESTAMP(3),
                               `creator_id`      BIGINT          NOT NULL COMMENT '创建人ID',
                               `updater_id`      BIGINT          NULL COMMENT '更新人ID',
                               `is_deleted`      TINYINT(1)      NOT NULL DEFAULT 0 COMMENT '是否删除',
                               PRIMARY KEY (`id`),
                               KEY `idx_category` (`category_id`, `is_deleted`),
                               KEY `idx_brand` (`brand_id`, `is_deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商品SPU表';