// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: ums.proto

package memberproductcategoryrelationservice

import (
	"context"

	"github.com/feihua/zero-admin/rpc/ums/umsclient"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddMemberProductCategoryRelationReq        = umsclient.AddMemberProductCategoryRelationReq
	AddMemberProductCategoryRelationResp       = umsclient.AddMemberProductCategoryRelationResp
	MemberProductCategoryRelationListData      = umsclient.MemberProductCategoryRelationListData
	QueryMemberProductCategoryRelationListReq  = umsclient.QueryMemberProductCategoryRelationListReq
	QueryMemberProductCategoryRelationListResp = umsclient.QueryMemberProductCategoryRelationListResp

	MemberProductCategoryRelationService interface {
		// 添加会员与产品分类关系表（用户喜欢的分类）
		AddMemberProductCategoryRelation(ctx context.Context, in *AddMemberProductCategoryRelationReq, opts ...grpc.CallOption) (*AddMemberProductCategoryRelationResp, error)
		// 查询会员与产品分类关系表（用户喜欢的分类）列表
		QueryMemberProductCategoryRelationList(ctx context.Context, in *QueryMemberProductCategoryRelationListReq, opts ...grpc.CallOption) (*QueryMemberProductCategoryRelationListResp, error)
	}

	defaultMemberProductCategoryRelationService struct {
		cli zrpc.Client
	}
)

func NewMemberProductCategoryRelationService(cli zrpc.Client) MemberProductCategoryRelationService {
	return &defaultMemberProductCategoryRelationService{
		cli: cli,
	}
}

// 添加会员与产品分类关系表（用户喜欢的分类）
func (m *defaultMemberProductCategoryRelationService) AddMemberProductCategoryRelation(ctx context.Context, in *AddMemberProductCategoryRelationReq, opts ...grpc.CallOption) (*AddMemberProductCategoryRelationResp, error) {
	client := umsclient.NewMemberProductCategoryRelationServiceClient(m.cli.Conn())
	return client.AddMemberProductCategoryRelation(ctx, in, opts...)
}

// 查询会员与产品分类关系表（用户喜欢的分类）列表
func (m *defaultMemberProductCategoryRelationService) QueryMemberProductCategoryRelationList(ctx context.Context, in *QueryMemberProductCategoryRelationListReq, opts ...grpc.CallOption) (*QueryMemberProductCategoryRelationListResp, error) {
	client := umsclient.NewMemberProductCategoryRelationServiceClient(m.cli.Conn())
	return client.QueryMemberProductCategoryRelationList(ctx, in, opts...)
}
