// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: sms.proto

package homeadvertiseservice

import (
	"context"

	"github.com/feihua/zero-admin/rpc/sms/smsclient"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddCouponRecordReq                 = smsclient.AddCouponRecordReq
	AddCouponRecordResp                = smsclient.AddCouponRecordResp
	AddCouponReq                       = smsclient.AddCouponReq
	AddCouponResp                      = smsclient.AddCouponResp
	AddCouponScopeData                 = smsclient.AddCouponScopeData
	AddCouponScopeReq                  = smsclient.AddCouponScopeReq
	AddCouponScopeResp                 = smsclient.AddCouponScopeResp
	AddCouponTypeReq                   = smsclient.AddCouponTypeReq
	AddCouponTypeResp                  = smsclient.AddCouponTypeResp
	AddHomeAdvertiseReq                = smsclient.AddHomeAdvertiseReq
	AddHomeAdvertiseResp               = smsclient.AddHomeAdvertiseResp
	AddSeckillActivityReq              = smsclient.AddSeckillActivityReq
	AddSeckillActivityResp             = smsclient.AddSeckillActivityResp
	AddSeckillProductData              = smsclient.AddSeckillProductData
	AddSeckillProductReq               = smsclient.AddSeckillProductReq
	AddSeckillProductResp              = smsclient.AddSeckillProductResp
	AddSeckillReservationReq           = smsclient.AddSeckillReservationReq
	AddSeckillReservationResp          = smsclient.AddSeckillReservationResp
	AddSeckillSessionReq               = smsclient.AddSeckillSessionReq
	AddSeckillSessionResp              = smsclient.AddSeckillSessionResp
	CouponListData                     = smsclient.CouponListData
	CouponRecordListData               = smsclient.CouponRecordListData
	CouponScopeData                    = smsclient.CouponScopeData
	CouponScopeListData                = smsclient.CouponScopeListData
	CouponTypeListData                 = smsclient.CouponTypeListData
	DeleteCouponRecordReq              = smsclient.DeleteCouponRecordReq
	DeleteCouponRecordResp             = smsclient.DeleteCouponRecordResp
	DeleteCouponReq                    = smsclient.DeleteCouponReq
	DeleteCouponResp                   = smsclient.DeleteCouponResp
	DeleteCouponScopeReq               = smsclient.DeleteCouponScopeReq
	DeleteCouponScopeResp              = smsclient.DeleteCouponScopeResp
	DeleteCouponTypeReq                = smsclient.DeleteCouponTypeReq
	DeleteCouponTypeResp               = smsclient.DeleteCouponTypeResp
	DeleteHomeAdvertiseReq             = smsclient.DeleteHomeAdvertiseReq
	DeleteHomeAdvertiseResp            = smsclient.DeleteHomeAdvertiseResp
	DeleteSeckillActivityReq           = smsclient.DeleteSeckillActivityReq
	DeleteSeckillActivityResp          = smsclient.DeleteSeckillActivityResp
	DeleteSeckillProductReq            = smsclient.DeleteSeckillProductReq
	DeleteSeckillProductResp           = smsclient.DeleteSeckillProductResp
	DeleteSeckillReservationReq        = smsclient.DeleteSeckillReservationReq
	DeleteSeckillReservationResp       = smsclient.DeleteSeckillReservationResp
	DeleteSeckillSessionReq            = smsclient.DeleteSeckillSessionReq
	DeleteSeckillSessionResp           = smsclient.DeleteSeckillSessionResp
	HomeAdvertiseListData              = smsclient.HomeAdvertiseListData
	QueryCouponByCodeReq               = smsclient.QueryCouponByCodeReq
	QueryCouponByCodeResp              = smsclient.QueryCouponByCodeResp
	QueryCouponByScopeIdReq            = smsclient.QueryCouponByScopeIdReq
	QueryCouponByScopeIdResp           = smsclient.QueryCouponByScopeIdResp
	QueryCouponData                    = smsclient.QueryCouponData
	QueryCouponDetailReq               = smsclient.QueryCouponDetailReq
	QueryCouponDetailResp              = smsclient.QueryCouponDetailResp
	QueryCouponListReq                 = smsclient.QueryCouponListReq
	QueryCouponListResp                = smsclient.QueryCouponListResp
	QueryCouponRecordDetailReq         = smsclient.QueryCouponRecordDetailReq
	QueryCouponRecordDetailResp        = smsclient.QueryCouponRecordDetailResp
	QueryCouponRecordListReq           = smsclient.QueryCouponRecordListReq
	QueryCouponRecordListResp          = smsclient.QueryCouponRecordListResp
	QueryCouponScopeDetailReq          = smsclient.QueryCouponScopeDetailReq
	QueryCouponScopeDetailResp         = smsclient.QueryCouponScopeDetailResp
	QueryCouponScopeListReq            = smsclient.QueryCouponScopeListReq
	QueryCouponScopeListResp           = smsclient.QueryCouponScopeListResp
	QueryCouponTypeDetailReq           = smsclient.QueryCouponTypeDetailReq
	QueryCouponTypeDetailResp          = smsclient.QueryCouponTypeDetailResp
	QueryCouponTypeListReq             = smsclient.QueryCouponTypeListReq
	QueryCouponTypeListResp            = smsclient.QueryCouponTypeListResp
	QueryFlashPromotionListByDateResp  = smsclient.QueryFlashPromotionListByDateResp
	QueryHomeAdvertiseDetailReq        = smsclient.QueryHomeAdvertiseDetailReq
	QueryHomeAdvertiseDetailResp       = smsclient.QueryHomeAdvertiseDetailResp
	QueryHomeAdvertiseListReq          = smsclient.QueryHomeAdvertiseListReq
	QueryHomeAdvertiseListResp         = smsclient.QueryHomeAdvertiseListResp
	QueryMemberCouponListReq           = smsclient.QueryMemberCouponListReq
	QueryMemberCouponListResp          = smsclient.QueryMemberCouponListResp
	QuerySeckillActivityDetailReq      = smsclient.QuerySeckillActivityDetailReq
	QuerySeckillActivityDetailResp     = smsclient.QuerySeckillActivityDetailResp
	QuerySeckillActivityListByDateReq  = smsclient.QuerySeckillActivityListByDateReq
	QuerySeckillActivityListReq        = smsclient.QuerySeckillActivityListReq
	QuerySeckillActivityListResp       = smsclient.QuerySeckillActivityListResp
	QuerySeckillProductBySkuIdReq      = smsclient.QuerySeckillProductBySkuIdReq
	QuerySeckillProductDetailReq       = smsclient.QuerySeckillProductDetailReq
	QuerySeckillProductDetailResp      = smsclient.QuerySeckillProductDetailResp
	QuerySeckillProductListReq         = smsclient.QuerySeckillProductListReq
	QuerySeckillProductListResp        = smsclient.QuerySeckillProductListResp
	QuerySeckillReservationDetailReq   = smsclient.QuerySeckillReservationDetailReq
	QuerySeckillReservationDetailResp  = smsclient.QuerySeckillReservationDetailResp
	QuerySeckillReservationListReq     = smsclient.QuerySeckillReservationListReq
	QuerySeckillReservationListResp    = smsclient.QuerySeckillReservationListResp
	QuerySeckillSessionDetailReq       = smsclient.QuerySeckillSessionDetailReq
	QuerySeckillSessionDetailResp      = smsclient.QuerySeckillSessionDetailResp
	QuerySeckillSessionListByTimeReq   = smsclient.QuerySeckillSessionListByTimeReq
	QuerySeckillSessionListByTimeResp  = smsclient.QuerySeckillSessionListByTimeResp
	QuerySeckillSessionListReq         = smsclient.QuerySeckillSessionListReq
	QuerySeckillSessionListResp        = smsclient.QuerySeckillSessionListResp
	SeckillActivityListData            = smsclient.SeckillActivityListData
	SeckillProductListData             = smsclient.SeckillProductListData
	SeckillReservationListData         = smsclient.SeckillReservationListData
	SeckillSessionListData             = smsclient.SeckillSessionListData
	UpdateCouponRecordReq              = smsclient.UpdateCouponRecordReq
	UpdateCouponRecordResp             = smsclient.UpdateCouponRecordResp
	UpdateCouponReq                    = smsclient.UpdateCouponReq
	UpdateCouponResp                   = smsclient.UpdateCouponResp
	UpdateCouponScopeReq               = smsclient.UpdateCouponScopeReq
	UpdateCouponScopeResp              = smsclient.UpdateCouponScopeResp
	UpdateCouponStatusReq              = smsclient.UpdateCouponStatusReq
	UpdateCouponStatusResp             = smsclient.UpdateCouponStatusResp
	UpdateCouponTypeReq                = smsclient.UpdateCouponTypeReq
	UpdateCouponTypeResp               = smsclient.UpdateCouponTypeResp
	UpdateCouponTypeStatusReq          = smsclient.UpdateCouponTypeStatusReq
	UpdateCouponTypeStatusResp         = smsclient.UpdateCouponTypeStatusResp
	UpdateHomeAdvertiseReq             = smsclient.UpdateHomeAdvertiseReq
	UpdateHomeAdvertiseResp            = smsclient.UpdateHomeAdvertiseResp
	UpdateHomeAdvertiseStatusReq       = smsclient.UpdateHomeAdvertiseStatusReq
	UpdateHomeAdvertiseStatusResp      = smsclient.UpdateHomeAdvertiseStatusResp
	UpdateSeckillActivityReq           = smsclient.UpdateSeckillActivityReq
	UpdateSeckillActivityResp          = smsclient.UpdateSeckillActivityResp
	UpdateSeckillActivityStatusReq     = smsclient.UpdateSeckillActivityStatusReq
	UpdateSeckillActivityStatusResp    = smsclient.UpdateSeckillActivityStatusResp
	UpdateSeckillProductReq            = smsclient.UpdateSeckillProductReq
	UpdateSeckillProductResp           = smsclient.UpdateSeckillProductResp
	UpdateSeckillProductStatusReq      = smsclient.UpdateSeckillProductStatusReq
	UpdateSeckillProductStatusResp     = smsclient.UpdateSeckillProductStatusResp
	UpdateSeckillReservationReq        = smsclient.UpdateSeckillReservationReq
	UpdateSeckillReservationResp       = smsclient.UpdateSeckillReservationResp
	UpdateSeckillReservationStatusReq  = smsclient.UpdateSeckillReservationStatusReq
	UpdateSeckillReservationStatusResp = smsclient.UpdateSeckillReservationStatusResp
	UpdateSeckillSessionReq            = smsclient.UpdateSeckillSessionReq
	UpdateSeckillSessionResp           = smsclient.UpdateSeckillSessionResp
	UpdateSeckillSessionStatusReq      = smsclient.UpdateSeckillSessionStatusReq
	UpdateSeckillSessionStatusResp     = smsclient.UpdateSeckillSessionStatusResp

	HomeAdvertiseService interface {
		// 添加首页轮播广告
		AddHomeAdvertise(ctx context.Context, in *AddHomeAdvertiseReq, opts ...grpc.CallOption) (*AddHomeAdvertiseResp, error)
		// 删除首页轮播广告
		DeleteHomeAdvertise(ctx context.Context, in *DeleteHomeAdvertiseReq, opts ...grpc.CallOption) (*DeleteHomeAdvertiseResp, error)
		// 更新首页轮播广告
		UpdateHomeAdvertise(ctx context.Context, in *UpdateHomeAdvertiseReq, opts ...grpc.CallOption) (*UpdateHomeAdvertiseResp, error)
		// 更新首页轮播广告状态
		UpdateHomeAdvertiseStatus(ctx context.Context, in *UpdateHomeAdvertiseStatusReq, opts ...grpc.CallOption) (*UpdateHomeAdvertiseStatusResp, error)
		// 查询首页轮播广告详情
		QueryHomeAdvertiseDetail(ctx context.Context, in *QueryHomeAdvertiseDetailReq, opts ...grpc.CallOption) (*QueryHomeAdvertiseDetailResp, error)
		// 查询首页轮播广告列表
		QueryHomeAdvertiseList(ctx context.Context, in *QueryHomeAdvertiseListReq, opts ...grpc.CallOption) (*QueryHomeAdvertiseListResp, error)
	}

	defaultHomeAdvertiseService struct {
		cli zrpc.Client
	}
)

func NewHomeAdvertiseService(cli zrpc.Client) HomeAdvertiseService {
	return &defaultHomeAdvertiseService{
		cli: cli,
	}
}

// 添加首页轮播广告
func (m *defaultHomeAdvertiseService) AddHomeAdvertise(ctx context.Context, in *AddHomeAdvertiseReq, opts ...grpc.CallOption) (*AddHomeAdvertiseResp, error) {
	client := smsclient.NewHomeAdvertiseServiceClient(m.cli.Conn())
	return client.AddHomeAdvertise(ctx, in, opts...)
}

// 删除首页轮播广告
func (m *defaultHomeAdvertiseService) DeleteHomeAdvertise(ctx context.Context, in *DeleteHomeAdvertiseReq, opts ...grpc.CallOption) (*DeleteHomeAdvertiseResp, error) {
	client := smsclient.NewHomeAdvertiseServiceClient(m.cli.Conn())
	return client.DeleteHomeAdvertise(ctx, in, opts...)
}

// 更新首页轮播广告
func (m *defaultHomeAdvertiseService) UpdateHomeAdvertise(ctx context.Context, in *UpdateHomeAdvertiseReq, opts ...grpc.CallOption) (*UpdateHomeAdvertiseResp, error) {
	client := smsclient.NewHomeAdvertiseServiceClient(m.cli.Conn())
	return client.UpdateHomeAdvertise(ctx, in, opts...)
}

// 更新首页轮播广告状态
func (m *defaultHomeAdvertiseService) UpdateHomeAdvertiseStatus(ctx context.Context, in *UpdateHomeAdvertiseStatusReq, opts ...grpc.CallOption) (*UpdateHomeAdvertiseStatusResp, error) {
	client := smsclient.NewHomeAdvertiseServiceClient(m.cli.Conn())
	return client.UpdateHomeAdvertiseStatus(ctx, in, opts...)
}

// 查询首页轮播广告详情
func (m *defaultHomeAdvertiseService) QueryHomeAdvertiseDetail(ctx context.Context, in *QueryHomeAdvertiseDetailReq, opts ...grpc.CallOption) (*QueryHomeAdvertiseDetailResp, error) {
	client := smsclient.NewHomeAdvertiseServiceClient(m.cli.Conn())
	return client.QueryHomeAdvertiseDetail(ctx, in, opts...)
}

// 查询首页轮播广告列表
func (m *defaultHomeAdvertiseService) QueryHomeAdvertiseList(ctx context.Context, in *QueryHomeAdvertiseListReq, opts ...grpc.CallOption) (*QueryHomeAdvertiseListResp, error) {
	client := smsclient.NewHomeAdvertiseServiceClient(m.cli.Conn())
	return client.QueryHomeAdvertiseList(ctx, in, opts...)
}
