// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4
// Source: cms.proto

package server

import (
	"context"

	"github.com/feihua/zero-admin/rpc/cms/cmsclient"
	"github.com/feihua/zero-admin/rpc/cms/internal/logic/preferredareaproductrelationservice"
	"github.com/feihua/zero-admin/rpc/cms/internal/svc"
)

type PreferredAreaProductRelationServiceServer struct {
	svcCtx *svc.ServiceContext
	cmsclient.UnimplementedPreferredAreaProductRelationServiceServer
}

func NewPreferredAreaProductRelationServiceServer(svcCtx *svc.ServiceContext) *PreferredAreaProductRelationServiceServer {
	return &PreferredAreaProductRelationServiceServer{
		svcCtx: svcCtx,
	}
}

// 添加优选专区和产品关系表
func (s *PreferredAreaProductRelationServiceServer) AddPreferredAreaProductRelation(ctx context.Context, in *cmsclient.AddPreferredAreaProductRelationReq) (*cmsclient.AddPreferredAreaProductRelationResp, error) {
	l := preferredareaproductrelationservicelogic.NewAddPreferredAreaProductRelationLogic(ctx, s.svcCtx)
	return l.AddPreferredAreaProductRelation(in)
}

// 查询优选专区和产品关系表列表
func (s *PreferredAreaProductRelationServiceServer) QueryPreferredAreaProductRelationList(ctx context.Context, in *cmsclient.QueryPreferredAreaProductRelationListReq) (*cmsclient.QueryPreferredAreaProductRelationListResp, error) {
	l := preferredareaproductrelationservicelogic.NewQueryPreferredAreaProductRelationListLogic(ctx, s.svcCtx)
	return l.QueryPreferredAreaProductRelationList(in)
}
