### app会员登录
POST {{host}}/api/member/login
Content-Type: application/json

{
  "mobile": "18613030352",
  "password": "123456"
}
> {% client.global.set("token", response.body.data.token); %}

### 购物车信息
GET {{host}}/api/cart/list
Authorization: Bearer {{token}}