### app会员登录
POST {{host}}/api/member/login
Content-Type: application/json

{
  "mobile": "18613030352",
  "password": "123456"
}
> {% client.global.set("token", response.body.data.token); %}


### 获取会员个人的优惠券
GET {{host}}/api/member/coupon/list/0
Authorization: Bearer {{token}}

### 获取登录会员购物车的相关优惠券
GET {{host}}/api/member/coupon/listByCart/1
Authorization: Bearer {{token}}