### app会员登录
POST {{host}}/api/member/login
Content-Type: application/json

{
  "mobile": "18613030352",
  "password": "123456"
}
> {% client.global.set("token", response.body.data.token); %}

### 获取订单列表
GET {{host}}/api/order/orderList/0/1
Authorization: Bearer {{token}}

### 获取订单详情
GET {{host}}/api/order/orderDetail/27
Authorization: Bearer {{token}}

### 根据购物车信息生成确认单信息
POST {{host}}/api/order/generateConfirmOrder
Content-Type: application/json
Authorization: Bearer {{token}}

//{
//  "ids": [27]
//}

### 根据购物车信息生成订单
POST {{host}}/api/order/generateOrder
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "memberReceiveAddressId": 0,
  "couponId": 0,
  "useIntegration": 0,
  "payType": 0,
  "cartIds": [
    "Long"
  ]
}