// Code generated by goctl. DO NOT EDIT.
// Source: ums.proto

package server

import (
	"context"

	"github.com/feihua/zero-admin/rpc/ums/internal/logic/memberreceiveaddressservice"
	"github.com/feihua/zero-admin/rpc/ums/internal/svc"
	"github.com/feihua/zero-admin/rpc/ums/umsclient"
)

type MemberReceiveAddressServiceServer struct {
	svcCtx *svc.ServiceContext
	umsclient.UnimplementedMemberReceiveAddressServiceServer
}

func NewMemberReceiveAddressServiceServer(svcCtx *svc.ServiceContext) *MemberReceiveAddressServiceServer {
	return &MemberReceiveAddressServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *MemberReceiveAddressServiceServer) MemberReceiveAddressAdd(ctx context.Context, in *umsclient.MemberReceiveAddressAddReq) (*umsclient.MemberReceiveAddressAddResp, error) {
	l := memberreceiveaddressservicelogic.NewMemberReceiveAddressAddLogic(ctx, s.svcCtx)
	return l.MemberReceiveAddressAdd(in)
}

func (s *MemberReceiveAddressServiceServer) MemberReceiveAddressList(ctx context.Context, in *umsclient.MemberReceiveAddressListReq) (*umsclient.MemberReceiveAddressListResp, error) {
	l := memberreceiveaddressservicelogic.NewMemberReceiveAddressListLogic(ctx, s.svcCtx)
	return l.MemberReceiveAddressList(in)
}

func (s *MemberReceiveAddressServiceServer) MemberReceiveAddressUpdate(ctx context.Context, in *umsclient.MemberReceiveAddressUpdateReq) (*umsclient.MemberReceiveAddressUpdateResp, error) {
	l := memberreceiveaddressservicelogic.NewMemberReceiveAddressUpdateLogic(ctx, s.svcCtx)
	return l.MemberReceiveAddressUpdate(in)
}

func (s *MemberReceiveAddressServiceServer) MemberReceiveAddressDelete(ctx context.Context, in *umsclient.MemberReceiveAddressDeleteReq) (*umsclient.MemberReceiveAddressDeleteResp, error) {
	l := memberreceiveaddressservicelogic.NewMemberReceiveAddressDeleteLogic(ctx, s.svcCtx)
	return l.MemberReceiveAddressDelete(in)
}

func (s *MemberReceiveAddressServiceServer) MemberReceiveAddressQueryDetail(ctx context.Context, in *umsclient.MemberReceiveAddressQueryDetailReq) (*umsclient.MemberReceiveAddressQueryDetailResp, error) {
	l := memberreceiveaddressservicelogic.NewMemberReceiveAddressQueryDetailLogic(ctx, s.svcCtx)
	return l.MemberReceiveAddressQueryDetail(in)
}
