// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1
// Source: pms.proto

package productcategoryservice

import (
	"context"

	"github.com/feihua/zero-admin/rpc/pms/pmsclient"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddBrandReq                                   = pmsclient.AddBrandReq
	AddBrandResp                                  = pmsclient.AddBrandResp
	AddCommentReplayReq                           = pmsclient.AddCommentReplayReq
	AddCommentReplayResp                          = pmsclient.AddCommentReplayResp
	AddCommentReq                                 = pmsclient.AddCommentReq
	AddCommentResp                                = pmsclient.AddCommentResp
	AddFeightTemplateReq                          = pmsclient.AddFeightTemplateReq
	AddFeightTemplateResp                         = pmsclient.AddFeightTemplateResp
	AddProductAttributeCategoryReq                = pmsclient.AddProductAttributeCategoryReq
	AddProductAttributeCategoryResp               = pmsclient.AddProductAttributeCategoryResp
	AddProductAttributeReq                        = pmsclient.AddProductAttributeReq
	AddProductAttributeResp                       = pmsclient.AddProductAttributeResp
	AddProductAttributeValueReq                   = pmsclient.AddProductAttributeValueReq
	AddProductAttributeValueResp                  = pmsclient.AddProductAttributeValueResp
	AddProductCategoryAttributeRelationReq        = pmsclient.AddProductCategoryAttributeRelationReq
	AddProductCategoryAttributeRelationResp       = pmsclient.AddProductCategoryAttributeRelationResp
	AddProductCategoryReq                         = pmsclient.AddProductCategoryReq
	AddProductCategoryResp                        = pmsclient.AddProductCategoryResp
	AddProductCollectReq                          = pmsclient.AddProductCollectReq
	AddProductCollectResp                         = pmsclient.AddProductCollectResp
	AddProductFullReductionReq                    = pmsclient.AddProductFullReductionReq
	AddProductFullReductionResp                   = pmsclient.AddProductFullReductionResp
	AddProductLadderReq                           = pmsclient.AddProductLadderReq
	AddProductLadderResp                          = pmsclient.AddProductLadderResp
	AddProductOperateLogReq                       = pmsclient.AddProductOperateLogReq
	AddProductOperateLogResp                      = pmsclient.AddProductOperateLogResp
	AddProductReq                                 = pmsclient.AddProductReq
	AddProductResp                                = pmsclient.AddProductResp
	AddProductVertifyRecordReq                    = pmsclient.AddProductVertifyRecordReq
	AddProductVertifyRecordResp                   = pmsclient.AddProductVertifyRecordResp
	AddSkuStockReq                                = pmsclient.AddSkuStockReq
	AddSkuStockResp                               = pmsclient.AddSkuStockResp
	BrandData                                     = pmsclient.BrandData
	BrandListData                                 = pmsclient.BrandListData
	CommentListData                               = pmsclient.CommentListData
	CommentReplayListData                         = pmsclient.CommentReplayListData
	DeleteBrandReq                                = pmsclient.DeleteBrandReq
	DeleteBrandResp                               = pmsclient.DeleteBrandResp
	DeleteCommentReplayReq                        = pmsclient.DeleteCommentReplayReq
	DeleteCommentReplayResp                       = pmsclient.DeleteCommentReplayResp
	DeleteCommentReq                              = pmsclient.DeleteCommentReq
	DeleteCommentResp                             = pmsclient.DeleteCommentResp
	DeleteFeightTemplateReq                       = pmsclient.DeleteFeightTemplateReq
	DeleteFeightTemplateResp                      = pmsclient.DeleteFeightTemplateResp
	DeleteProductAttributeCategoryReq             = pmsclient.DeleteProductAttributeCategoryReq
	DeleteProductAttributeCategoryResp            = pmsclient.DeleteProductAttributeCategoryResp
	DeleteProductAttributeReq                     = pmsclient.DeleteProductAttributeReq
	DeleteProductAttributeResp                    = pmsclient.DeleteProductAttributeResp
	DeleteProductAttributeValueReq                = pmsclient.DeleteProductAttributeValueReq
	DeleteProductAttributeValueResp               = pmsclient.DeleteProductAttributeValueResp
	DeleteProductCategoryReq                      = pmsclient.DeleteProductCategoryReq
	DeleteProductCategoryResp                     = pmsclient.DeleteProductCategoryResp
	DeleteProductCollectReq                       = pmsclient.DeleteProductCollectReq
	DeleteProductCollectResp                      = pmsclient.DeleteProductCollectResp
	DeleteProductFullReductionReq                 = pmsclient.DeleteProductFullReductionReq
	DeleteProductFullReductionResp                = pmsclient.DeleteProductFullReductionResp
	DeleteProductLadderReq                        = pmsclient.DeleteProductLadderReq
	DeleteProductLadderResp                       = pmsclient.DeleteProductLadderResp
	DeleteProductOperateLogReq                    = pmsclient.DeleteProductOperateLogReq
	DeleteProductOperateLogResp                   = pmsclient.DeleteProductOperateLogResp
	DeleteProductReq                              = pmsclient.DeleteProductReq
	DeleteProductResp                             = pmsclient.DeleteProductResp
	DeleteProductVertifyRecordReq                 = pmsclient.DeleteProductVertifyRecordReq
	DeleteProductVertifyRecordResp                = pmsclient.DeleteProductVertifyRecordResp
	DeleteSkuStockReq                             = pmsclient.DeleteSkuStockReq
	DeleteSkuStockResp                            = pmsclient.DeleteSkuStockResp
	FeightTemplateListData                        = pmsclient.FeightTemplateListData
	LockSkuStockLockData                          = pmsclient.LockSkuStockLockData
	LockSkuStockLockReq                           = pmsclient.LockSkuStockLockReq
	LockSkuStockLockResp                          = pmsclient.LockSkuStockLockResp
	MemberPriceList                               = pmsclient.MemberPriceList
	MemberPriceListData                           = pmsclient.MemberPriceListData
	ProductAttributeCategoryListData              = pmsclient.ProductAttributeCategoryListData
	ProductAttributeData                          = pmsclient.ProductAttributeData
	ProductAttributeDataList                      = pmsclient.ProductAttributeDataList
	ProductAttributeListData                      = pmsclient.ProductAttributeListData
	ProductAttributeValueData                     = pmsclient.ProductAttributeValueData
	ProductAttributeValueList                     = pmsclient.ProductAttributeValueList
	ProductAttributeValueListData                 = pmsclient.ProductAttributeValueListData
	ProductCategoryAttributeRelationListData      = pmsclient.ProductCategoryAttributeRelationListData
	ProductCategoryListData                       = pmsclient.ProductCategoryListData
	ProductCollectListData                        = pmsclient.ProductCollectListData
	ProductFullReductionData                      = pmsclient.ProductFullReductionData
	ProductFullReductionList                      = pmsclient.ProductFullReductionList
	ProductFullReductionListData                  = pmsclient.ProductFullReductionListData
	ProductLadderData                             = pmsclient.ProductLadderData
	ProductLadderList                             = pmsclient.ProductLadderList
	ProductLadderListData                         = pmsclient.ProductLadderListData
	ProductListData                               = pmsclient.ProductListData
	ProductOperateLogListData                     = pmsclient.ProductOperateLogListData
	ProductVertifyRecordListData                  = pmsclient.ProductVertifyRecordListData
	QueryBrandDetailReq                           = pmsclient.QueryBrandDetailReq
	QueryBrandDetailResp                          = pmsclient.QueryBrandDetailResp
	QueryBrandListByIdsReq                        = pmsclient.QueryBrandListByIdsReq
	QueryBrandListReq                             = pmsclient.QueryBrandListReq
	QueryBrandListResp                            = pmsclient.QueryBrandListResp
	QueryByproductCategoryIdData                  = pmsclient.QueryByproductCategoryIdData
	QueryByproductCategoryIdReq                   = pmsclient.QueryByproductCategoryIdReq
	QueryByproductCategoryIdResp                  = pmsclient.QueryByproductCategoryIdResp
	QueryCommentDetailReq                         = pmsclient.QueryCommentDetailReq
	QueryCommentDetailResp                        = pmsclient.QueryCommentDetailResp
	QueryCommentListReq                           = pmsclient.QueryCommentListReq
	QueryCommentListResp                          = pmsclient.QueryCommentListResp
	QueryCommentReplayDetailReq                   = pmsclient.QueryCommentReplayDetailReq
	QueryCommentReplayDetailResp                  = pmsclient.QueryCommentReplayDetailResp
	QueryCommentReplayListReq                     = pmsclient.QueryCommentReplayListReq
	QueryCommentReplayListResp                    = pmsclient.QueryCommentReplayListResp
	QueryFeightTemplateDetailReq                  = pmsclient.QueryFeightTemplateDetailReq
	QueryFeightTemplateDetailResp                 = pmsclient.QueryFeightTemplateDetailResp
	QueryFeightTemplateListReq                    = pmsclient.QueryFeightTemplateListReq
	QueryFeightTemplateListResp                   = pmsclient.QueryFeightTemplateListResp
	QueryProductAttributeCategoryListReq          = pmsclient.QueryProductAttributeCategoryListReq
	QueryProductAttributeCategoryListResp         = pmsclient.QueryProductAttributeCategoryListResp
	QueryProductAttributeListReq                  = pmsclient.QueryProductAttributeListReq
	QueryProductAttributeListResp                 = pmsclient.QueryProductAttributeListResp
	QueryProductAttributeValueListReq             = pmsclient.QueryProductAttributeValueListReq
	QueryProductAttributeValueListResp            = pmsclient.QueryProductAttributeValueListResp
	QueryProductByIdsReq                          = pmsclient.QueryProductByIdsReq
	QueryProductCategoryAttributeRelationListReq  = pmsclient.QueryProductCategoryAttributeRelationListReq
	QueryProductCategoryAttributeRelationListResp = pmsclient.QueryProductCategoryAttributeRelationListResp
	QueryProductCategoryDetailReq                 = pmsclient.QueryProductCategoryDetailReq
	QueryProductCategoryDetailResp                = pmsclient.QueryProductCategoryDetailResp
	QueryProductCategoryListReq                   = pmsclient.QueryProductCategoryListReq
	QueryProductCategoryListResp                  = pmsclient.QueryProductCategoryListResp
	QueryProductCategoryListTreeData              = pmsclient.QueryProductCategoryListTreeData
	QueryProductCategoryListTreeResp              = pmsclient.QueryProductCategoryListTreeResp
	QueryProductCategoryTreeListReq               = pmsclient.QueryProductCategoryTreeListReq
	QueryProductCollectDetailReq                  = pmsclient.QueryProductCollectDetailReq
	QueryProductCollectDetailResp                 = pmsclient.QueryProductCollectDetailResp
	QueryProductCollectListReq                    = pmsclient.QueryProductCollectListReq
	QueryProductCollectListResp                   = pmsclient.QueryProductCollectListResp
	QueryProductDetailByIdReq                     = pmsclient.QueryProductDetailByIdReq
	QueryProductDetailByIdResp                    = pmsclient.QueryProductDetailByIdResp
	QueryProductFullReductionListReq              = pmsclient.QueryProductFullReductionListReq
	QueryProductFullReductionListResp             = pmsclient.QueryProductFullReductionListResp
	QueryProductLadderDetailReq                   = pmsclient.QueryProductLadderDetailReq
	QueryProductLadderDetailResp                  = pmsclient.QueryProductLadderDetailResp
	QueryProductLadderListReq                     = pmsclient.QueryProductLadderListReq
	QueryProductLadderListResp                    = pmsclient.QueryProductLadderListResp
	QueryProductListReq                           = pmsclient.QueryProductListReq
	QueryProductListResp                          = pmsclient.QueryProductListResp
	QueryProductOperateLogDetailReq               = pmsclient.QueryProductOperateLogDetailReq
	QueryProductOperateLogDetailResp              = pmsclient.QueryProductOperateLogDetailResp
	QueryProductOperateLogListReq                 = pmsclient.QueryProductOperateLogListReq
	QueryProductOperateLogListResp                = pmsclient.QueryProductOperateLogListResp
	QueryProductVertifyRecordDetailReq            = pmsclient.QueryProductVertifyRecordDetailReq
	QueryProductVertifyRecordDetailResp           = pmsclient.QueryProductVertifyRecordDetailResp
	QueryProductVertifyRecordListReq              = pmsclient.QueryProductVertifyRecordListReq
	QueryProductVertifyRecordListResp             = pmsclient.QueryProductVertifyRecordListResp
	QuerySkuStockByProductSkuIdReq                = pmsclient.QuerySkuStockByProductSkuIdReq
	QuerySkuStockDetailReq                        = pmsclient.QuerySkuStockDetailReq
	QuerySkuStockDetailResp                       = pmsclient.QuerySkuStockDetailResp
	QuerySkuStockListReq                          = pmsclient.QuerySkuStockListReq
	QuerySkuStockListResp                         = pmsclient.QuerySkuStockListResp
	ReleaseSkuStockLockData                       = pmsclient.ReleaseSkuStockLockData
	ReleaseSkuStockLockReq                        = pmsclient.ReleaseSkuStockLockReq
	ReleaseSkuStockLockResp                       = pmsclient.ReleaseSkuStockLockResp
	SkuStockData                                  = pmsclient.SkuStockData
	SkuStockList                                  = pmsclient.SkuStockList
	SkuStockListData                              = pmsclient.SkuStockListData
	UpdateBrandFactoryStatusReq                   = pmsclient.UpdateBrandFactoryStatusReq
	UpdateBrandRecommendStatusReq                 = pmsclient.UpdateBrandRecommendStatusReq
	UpdateBrandReq                                = pmsclient.UpdateBrandReq
	UpdateBrandResp                               = pmsclient.UpdateBrandResp
	UpdateBrandShowStatusReq                      = pmsclient.UpdateBrandShowStatusReq
	UpdateBrandStatusResp                         = pmsclient.UpdateBrandStatusResp
	UpdateCommentReplayReq                        = pmsclient.UpdateCommentReplayReq
	UpdateCommentReplayResp                       = pmsclient.UpdateCommentReplayResp
	UpdateCommentReq                              = pmsclient.UpdateCommentReq
	UpdateCommentResp                             = pmsclient.UpdateCommentResp
	UpdateFeightTemplateReq                       = pmsclient.UpdateFeightTemplateReq
	UpdateFeightTemplateResp                      = pmsclient.UpdateFeightTemplateResp
	UpdateProductAttributeCategoryReq             = pmsclient.UpdateProductAttributeCategoryReq
	UpdateProductAttributeCategoryResp            = pmsclient.UpdateProductAttributeCategoryResp
	UpdateProductAttributeValueReq                = pmsclient.UpdateProductAttributeValueReq
	UpdateProductAttributeValueResp               = pmsclient.UpdateProductAttributeValueResp
	UpdateProductCategoryReq                      = pmsclient.UpdateProductCategoryReq
	UpdateProductCategoryResp                     = pmsclient.UpdateProductCategoryResp
	UpdateProductCategoryStatusReq                = pmsclient.UpdateProductCategoryStatusReq
	UpdateProductCategoryStatusResp               = pmsclient.UpdateProductCategoryStatusResp
	UpdateProductLadderReq                        = pmsclient.UpdateProductLadderReq
	UpdateProductLadderResp                       = pmsclient.UpdateProductLadderResp
	UpdateProductReq                              = pmsclient.UpdateProductReq
	UpdateProductResp                             = pmsclient.UpdateProductResp
	UpdateProductStatusReq                        = pmsclient.UpdateProductStatusReq
	UpdateProductStatusResp                       = pmsclient.UpdateProductStatusResp
	UpdateProductVertifyRecordReq                 = pmsclient.UpdateProductVertifyRecordReq
	UpdateProductVertifyRecordResp                = pmsclient.UpdateProductVertifyRecordResp
	UpdateProductVertifyRecordStatusReq           = pmsclient.UpdateProductVertifyRecordStatusReq
	UpdateProductVertifyRecordStatusResp          = pmsclient.UpdateProductVertifyRecordStatusResp
	UpdateSkuStockData                            = pmsclient.UpdateSkuStockData
	UpdateSkuStockReq                             = pmsclient.UpdateSkuStockReq
	UpdateSkuStockResp                            = pmsclient.UpdateSkuStockResp

	ProductCategoryService interface {
		// 添加产品分类
		AddProductCategory(ctx context.Context, in *AddProductCategoryReq, opts ...grpc.CallOption) (*AddProductCategoryResp, error)
		// 删除产品分类
		DeleteProductCategory(ctx context.Context, in *DeleteProductCategoryReq, opts ...grpc.CallOption) (*DeleteProductCategoryResp, error)
		// 更新产品分类
		UpdateProductCategory(ctx context.Context, in *UpdateProductCategoryReq, opts ...grpc.CallOption) (*UpdateProductCategoryResp, error)
		// 更新商品分类导航显示状态
		UpdateCategoryNavStatus(ctx context.Context, in *UpdateProductCategoryStatusReq, opts ...grpc.CallOption) (*UpdateProductCategoryStatusResp, error)
		// 更新商品分类显示状态
		UpdateCategoryShowStatus(ctx context.Context, in *UpdateProductCategoryStatusReq, opts ...grpc.CallOption) (*UpdateProductCategoryStatusResp, error)
		// 查询产品分类详情
		QueryProductCategoryDetail(ctx context.Context, in *QueryProductCategoryDetailReq, opts ...grpc.CallOption) (*QueryProductCategoryDetailResp, error)
		// 查询产品分类列表
		QueryProductCategoryList(ctx context.Context, in *QueryProductCategoryListReq, opts ...grpc.CallOption) (*QueryProductCategoryListResp, error)
		// 查询商品分类（tree）
		QueryProductCategoryTreeList(ctx context.Context, in *QueryProductCategoryTreeListReq, opts ...grpc.CallOption) (*QueryProductCategoryListTreeResp, error)
	}

	defaultProductCategoryService struct {
		cli zrpc.Client
	}
)

func NewProductCategoryService(cli zrpc.Client) ProductCategoryService {
	return &defaultProductCategoryService{
		cli: cli,
	}
}

// 添加产品分类
func (m *defaultProductCategoryService) AddProductCategory(ctx context.Context, in *AddProductCategoryReq, opts ...grpc.CallOption) (*AddProductCategoryResp, error) {
	client := pmsclient.NewProductCategoryServiceClient(m.cli.Conn())
	return client.AddProductCategory(ctx, in, opts...)
}

// 删除产品分类
func (m *defaultProductCategoryService) DeleteProductCategory(ctx context.Context, in *DeleteProductCategoryReq, opts ...grpc.CallOption) (*DeleteProductCategoryResp, error) {
	client := pmsclient.NewProductCategoryServiceClient(m.cli.Conn())
	return client.DeleteProductCategory(ctx, in, opts...)
}

// 更新产品分类
func (m *defaultProductCategoryService) UpdateProductCategory(ctx context.Context, in *UpdateProductCategoryReq, opts ...grpc.CallOption) (*UpdateProductCategoryResp, error) {
	client := pmsclient.NewProductCategoryServiceClient(m.cli.Conn())
	return client.UpdateProductCategory(ctx, in, opts...)
}

// 更新商品分类导航显示状态
func (m *defaultProductCategoryService) UpdateCategoryNavStatus(ctx context.Context, in *UpdateProductCategoryStatusReq, opts ...grpc.CallOption) (*UpdateProductCategoryStatusResp, error) {
	client := pmsclient.NewProductCategoryServiceClient(m.cli.Conn())
	return client.UpdateCategoryNavStatus(ctx, in, opts...)
}

// 更新商品分类显示状态
func (m *defaultProductCategoryService) UpdateCategoryShowStatus(ctx context.Context, in *UpdateProductCategoryStatusReq, opts ...grpc.CallOption) (*UpdateProductCategoryStatusResp, error) {
	client := pmsclient.NewProductCategoryServiceClient(m.cli.Conn())
	return client.UpdateCategoryShowStatus(ctx, in, opts...)
}

// 查询产品分类详情
func (m *defaultProductCategoryService) QueryProductCategoryDetail(ctx context.Context, in *QueryProductCategoryDetailReq, opts ...grpc.CallOption) (*QueryProductCategoryDetailResp, error) {
	client := pmsclient.NewProductCategoryServiceClient(m.cli.Conn())
	return client.QueryProductCategoryDetail(ctx, in, opts...)
}

// 查询产品分类列表
func (m *defaultProductCategoryService) QueryProductCategoryList(ctx context.Context, in *QueryProductCategoryListReq, opts ...grpc.CallOption) (*QueryProductCategoryListResp, error) {
	client := pmsclient.NewProductCategoryServiceClient(m.cli.Conn())
	return client.QueryProductCategoryList(ctx, in, opts...)
}

// 查询商品分类（tree）
func (m *defaultProductCategoryService) QueryProductCategoryTreeList(ctx context.Context, in *QueryProductCategoryTreeListReq, opts ...grpc.CallOption) (*QueryProductCategoryListTreeResp, error) {
	client := pmsclient.NewProductCategoryServiceClient(m.cli.Conn())
	return client.QueryProductCategoryTreeList(ctx, in, opts...)
}
